fix(git-type): disable git-type if detected
talamer/console pull request #106
Opened 2019-05-20 10:11 UTC by invincibleJai

Tracks ## https://jira.coreos.com/browse/ODC-706

Scenario: 

- user provides git url as : "https://github.com/eclipse/che-plugin-registry/"
- As git type is GitHub (able to identify with regex) show git type field as "GitHub" and disable/hide it
- If at any point in time user changes git url to "http://source.ibm.com/" 
- As git type is not undentified so show/enable git type field as user can change it as per their choice

GIF ::  

![gitType](https://user-images.githubusercontent.com/5129024/58014036-8a84cf00-7b15-11e9-9374-2520435c730f.gif)

2019-05-20 10:13 UTC, invincibleJai commented
@christianvogt @rohitkrai03 PTAL, have raised the PR. Currently, have disabled it can even hide if that's the ask, can close it if not needed as the issue is still under discussion

2019-05-20 12:24 UTC, christianvogt commented
Talk to UX about disabling vs hiding. I'm inclined to hide it. The user shouldn't care to even see this value as it's an implementation details.

2019-05-20 13:58 UTC, serenamarie125 commented
Please hide versus disable!  thanks @invincibleJai

2019-05-20 15:36 UTC, rohitkrai03 requested changes

2019-05-20 15:36 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  isGitTypeVisible: boolean;
Why have another variable just to check if a component is visible or not? We can control visibility of the component using the already present state value. If there is a valid `GitType` don't show the dropdown.

2019-05-20 16:09 UTC, invincibleJai commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  isGitTypeVisible: boolean;
@rohitkrai03  Even I thought initially same but with `GitType` it won't cover below scenario

- User types git url as "https://abc.com"
- So we would show gitType as it would be empty
- now user selects gitType as GitLab then as gitType would be have a value which would update the state which inturn hide gitType field as we would depend on GitType

WDYT?

2019-05-20 16:32 UTC, sbose78 commented
build and deploy

2019-05-20 16:32 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit22.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-106-openshift-console.apps.rohit22.devcluster.openshift.com

2019-05-21 10:16 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  isGitTypeVisible: boolean;
Ok. That does make sense.

2019-05-21 18:14 UTC, rohitkrai03 approved these changes
LGTM

2019-05-21 18:15 UTC, merged