[WIP]Functional test(first): Perspective Switcher
talamer/console pull request #108
Opened 2019-05-20 16:10 UTC by sanketpathak

first functional test for the devconsole.

2019-05-21 06:44 UTC, rohitkrai03 commented
build and deploy

2019-05-21 08:32 UTC, rohitkrai03 commented
build and deploy

2019-05-21 08:35 UTC, rohitkrai03 commented
build and deploy

2019-05-21 11:55 UTC, ppitonak requested changes

2019-05-21 11:55 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +export const devPerspective = element(by.xpath('//li[@class= \'pf-c-nav__item odc-mega-menu-item\']//a[.//text()= \'Developer\']'))
Why did you use xpath insted of css selectors?

2019-05-21 11:55 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  browser.sleep(3000);
You should wait until something specific happens, not for a specific period of time.

2019-05-21 11:55 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  await browser.wait(until.elementToBeClickable(switcher),5000);
extract the constant into a variable

2019-05-21 11:55 UTC, ppitonak commented on frontend/integration-tests/tests/devconsole/perspective-switcher.ts
> +        await perspectiveSwitcher('dev');
IMHO the name of the function should be a verb, not a noun.

2019-05-21 11:55 UTC, ppitonak commented on frontend/integration-tests/tests/devconsole/perspective-switcher.ts
> +        await perspectiveSwitcher('admin');
1. I miss some `expect`s
2. I miss other cases, i.e. I'm in default view and switch to dev, I'm on a random admin view and switch to dev, I'm on random dev view and swith to dev, dev->admin->dev (not sure about this one), admin -> dev -> admin (not sure)

2019-05-22 06:42 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  browser.sleep(3000);
I'm using wait in the later part of the code but it wasn't working without delaying it for a specific period of time that's why I have used sleep

2019-05-22 06:53 UTC, sanketpathak commented on frontend/integration-tests/tests/devconsole/perspective-switcher.ts
> +        await perspectiveSwitcher('admin');
1. Actually, it was a WIP PR so I will be adding expects,  WIP was removed to build and deploy it on a cluster as you can see from the above comments
2. This is just a basic test for changing between the perspective. For other cases like dev->admin->dev or admin -> dev -> admin it can easily happen by using the perspesctiveSwitcher function with the required view as an argument. If I am missing something here let me know

2019-05-22 06:55 UTC, gajanan194 commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +export const devPerspective = element(by.xpath('//li[@class= \'pf-c-nav__item odc-mega-menu-item\']//a[.//text()= \'Developer\']'))
These are the relative XPaths and are more accurate than others. If we don't get the relative XPaths, then we will shift to CSS selector. Relative XPath will get a high priority than the CSS selector.  Is it okay?

2019-05-22 06:56 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +export const devPerspective = element(by.xpath('//li[@class= \'pf-c-nav__item odc-mega-menu-item\']//a[.//text()= \'Developer\']'))
Css selectors were not giving proper results, that's why I have used XPath

2019-05-24 07:15 UTC, invincibleJai commented
build and deploy

2019-05-24 13:23 UTC, sbose78 commented
build and deploy

2019-05-24 13:23 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.tkurian9.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-108-openshift-console.apps.tkurian9.devcluster.openshift.com

2019-05-30 05:11 UTC, rgarg1 commented
@sanketpathak Are the tests passing? Can you attach the test run report pls.

2019-05-30 07:33 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +export const devPerspective = element(by.xpath('//li[@class= \'pf-c-nav__item odc-mega-menu-item\']//a[.//text()= \'Developer\']'))
It should be identical to `element(by.cssContainingText('li.pf-c-nav__item.odc-mega-menu-item a', 'Developer'))`

2019-05-30 07:44 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  browser.sleep(3000);
1. What happens when `perspective` is set to something non-valid? Use enum instead
2. I can accept the use of `browser.sleep` only in exceptional cases (e.g. a bug in Protractor/Selenium/browser). In this case `perspectiveSwitcher` should click the nav button in header, wait **until mega menu is visible**, click the menu item and wait **unitl mega menu disappears**
3. the functions should be renamed to `switchPerspective`

2019-05-30 07:45 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  await browser.wait(until.elementToBeClickable(switcher),5000);
still not done

2019-05-30 07:48 UTC, ppitonak commented on frontend/integration-tests/tests/devconsole/perspective-switcher.ts
> +        await perspectiveSwitcher('admin');
still missing expects

2019-05-30 07:58 UTC, ppitonak requested changes
Will this test run with admin account or regular user's account?

2019-05-30 07:58 UTC, ppitonak commented on frontend/integration-tests/tests/devconsole/perspective-switcher.ts
> +describe('perspectiveSwitcher', () => {
1. everybody refers to this functionality as "Mega menu" so the test should reflect that
2. `perspective-switcher.ts` doesn't follow naming conventions, it should be something like `mega-menu.scenario.ts`
3. be more descriptive in first params of `describe` and `it`, have a look on other scenarios

2019-05-30 07:58 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +export const devPerspective = element(by.xpath('//li[@class= \'pf-c-nav__item odc-mega-menu-item\']//a[.//text()= \'Developer\']'))
It should be identical to `element(by.cssContainingText('li.pf-c-nav__item.odc-mega-menu-item a', 'Developer'))`

2019-05-30 07:58 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  browser.sleep(3000);
1. What happens when `perspective` is set to something non-valid? Use enum instead
2. I can accept the use of `browser.sleep` only in exceptional cases (e.g. a bug in Protractor/Selenium/browser). In this case `switchPerspective` should click the nav button in header, wait **until mega menu is visible**, click the menu item and wait **unitl mega menu disappears**

2019-05-30 07:58 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  await browser.wait(until.elementToBeClickable(switcher),5000);
still not done

2019-05-30 07:58 UTC, ppitonak commented on frontend/integration-tests/tests/devconsole/perspective-switcher.ts
> +        expect(devPerspective.getText()).toContain('Developer');
IMHO this is wrong expectation... following my previous comment, `switchPerspective` should wait until mega menu disappears. Here, you should check that menu contains menu items relevant to developers and *doesn't* contain menu items for admins (not all so that we don't have to update the test too often)

2019-05-30 09:04 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  await browser.wait(until.elementToBeClickable(switcher),5000);
I've not extracted constant into a variable because if you see in other files they have used constants only, so to maintain homogeneity I didn't change it.

2019-05-30 13:55 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/perspective-switcher-view.ts
> +  await browser.wait(until.elementToBeClickable(switcher),5000);
I don't understand your comment

2019-06-05 14:17 UTC, sanketpathak commented
build and deploy

2019-06-05 14:17 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit31.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-108-openshift-console.apps.rohit31.devcluster.openshift.com

2019-06-06 17:28 UTC, sanketpathak commented
build and deploy

2019-06-11 11:02 UTC, ppitonak requested changes

2019-06-11 11:02 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +/* eslint-disable no-undef, no-unused-vars */
Plese format this file

2019-06-11 13:09 UTC, ppitonak requested changes

2019-06-11 13:09 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +  await browser.ready;
What is the purpose of this?

2019-06-11 13:09 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export let switchPerspective = async function(perspective: string) {
Why is the parameter of type `string` and not enum?

2019-06-11 13:09 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export enum PerspectiveUpdateStatus {
I don't like the name of this enum

2019-06-11 13:09 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +  Admin = " Admin Perspective",
Since you used `Developer`, I would use also `Administrator` as in UI instead of Admin

2019-06-11 13:09 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +  MultiModalManager = "Multi-Modal Perspective"
1. What is this? Is it supposed to represent the `Multi-Cluster Manager` menu item? 
2. You didn't implement this item in `switchPerspective` so I would omit it for now in enum

2019-06-11 13:09 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export const devPerspective = $$("li.pf-c-nav__item.odc-mega-menu-item").filter(
Why such a complicated construct? There is [helper method](https://www.protractortest.org/#/api?view=ProtractorBy.prototype.cssContainingText) in Protractor for that.

You just need something like `export const devPerspective = element(by.cssContainingText("li.pf-c-nav__item.odc-mega-menu-item", "Developer"));

2019-06-11 13:09 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export const adminPerspective = $$(
1. The same as `devPerspective` variable.
2. This is an implementation detail, you should **not** export this constant (+ it will force you to write test correctly ;) )

2019-06-11 13:20 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export enum PerspectiveUpdateStatus {
What type of name do you expect?

2019-06-11 13:34 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +  MultiModalManager = "Multi-Modal Perspective"
As I said it's a structural PR so I have left this area for unattended for future changes.

2019-06-11 13:35 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export const devPerspective = $$("li.pf-c-nav__item.odc-mega-menu-item").filter(
I tried that but it was not working so used this.

2019-06-11 13:36 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export enum PerspectiveUpdateStatus {
Since it's input to `switchPerspective` function, one option is to call it simply `Perspective`.

Another option is to make it more general, something like `MegaMenuItem` but then I would rename `switchPerspective` function.

It's up to team to decide. I personally would go for first one for simplicity. No matter what you choose, it has nothing to do with update or status

2019-06-11 19:13 UTC, christianvogt commented
I hope this is being used as a general approach PR because the perspective switcher and mega menu are going to change when we merge into console.

Also we should be keying off `data-test-id` for test automation where possible. This may mean that we should be adding such IDs to help identify items for tests. The IDs should be added in such a way that one could create a test using these IDs and have the underlying DOM structure completely change but the IDs are still relevant for interacting with relevant controls on the page. This is better than using class names which are designed for styling and cannot always be maintained through refactoring and style changes.

2019-06-12 03:00 UTC, sbose78 commented
build and deploy

2019-06-12 03:00 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rgarg13.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-108-openshift-console.apps.rgarg13.devcluster.openshift.com

2019-06-12 08:31 UTC, ppitonak requested changes

2019-06-12 08:31 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +      await
What is this?

2019-06-12 09:44 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +  await browser.ready;
It waits for the browser to load

2019-06-12 09:46 UTC, sanketpathak commented
@christianvogt Yes it's just a structural PR for enabling a testing framework for the devconsole, it can be edited as per the need. Regarding `data-test-id` I haven't used it in this, as it's just a basic test and its presence is limited to certain files. I agree with you on using `data-test-id` for testing structure as it simplifies the process as well as effective with the changing DOMs. but for this, it's just a starting point for functional tests of devconsole

2019-06-12 10:03 UTC, sanketpathak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export enum PerspectiveUpdateStatus {
Alright, `Perspective` it is...

2019-06-12 10:32 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +  await browser.ready;
Why do you need that? `browser.get` already waits for page to load and it's not used in any other test scenario

2019-06-12 12:03 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +  MultiModalManager = "Multi-Modal Perspective"
Do not add anything that you don't need immediately

2019-06-12 12:04 UTC, ppitonak commented on frontend/integration-tests/views/devconsole-view/mega-menu.view.ts
> +export const devPerspective = $$("li.pf-c-nav__item.odc-mega-menu-item").filter(
It does work

2019-06-12 12:06 UTC, ppitonak commented
@christianvogt how will the mega menu change after merging into console?

@sanketpathak I still object to merging half-baked PRs. Even if it's just an initial config for tests, it should contain at least one fully-functional passing test.

2019-06-12 15:52 UTC, christianvogt commented
@ppitonak UX and PF couldn't decided on the mega menu. We initially implemented according to the UX design. The intent was for PF to adopt it. But PF didn't like the design and then did something else. Later they changed their minds again and now it's a completely different location but similar look and feel inside a drop down menu.
We have a temporary perspective selector in console while we wait for the PF design. They are committed to doing implementation for our 4.2 release.

So this slide out menu is going away as soon as we move out of our repo.

2019-06-14 08:22 UTC, sanketpathak commented
build and deploy

2019-06-14 08:22 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit37.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-108-openshift-console.apps.rohit37.devcluster.openshift.com

2019-06-21 15:48 UTC, closed without merging