feat(codebases): Adding codebases section to devops console
talamer/console pull request #11
Opened 2019-03-04 07:45 UTC by abhinandan13jan

Adding codebase to devopsconsole to fetch the extended APIs. Included the yaml files required to create the resources.
@rohit: please review

2019-03-05 18:21 UTC, christianvogt commented
@abhinandan13jan please rebase and add remove the temp menu item from admin console

2019-03-06 06:26 UTC, abhinandan13jan commented
@christianvogt rebased and removed navlink for 'codebase'

2019-03-06 15:58 UTC, christianvogt commented
@abhinandan13jan please rebase with `master-next` there is no dev console nav in your PR.

2019-03-06 16:11 UTC, christianvogt commented
@abhinandan13jan i cannot dive into the details of the specific resource. In OS console, the names of the resources are clickable to go to their details pages.

2019-03-06 16:46 UTC, christianvogt requested changes
Also run the linter.

2019-03-06 16:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +    <p>{s.spec.codebase}</p>
This should be an external link.

2019-03-06 16:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +    <p>{s.metadata.name}</p>
This should a `ResourceLink`

2019-03-06 16:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const Details = ({obj: s}) => <div className="co-m-pane__body">
Not sure how to test this in the UI and some other parts of this file. The data here doesn't seem to needed for codebases. Is this a copy with left over code?

2019-03-06 16:46 UTC, christianvogt commented on frontend/public/extend/devconsole/routes.tsx
> +const getCodebaseRedirection = () => {
This should be generic much like it is done in OS console so other pages can use the same mechanism.

2019-03-06 16:46 UTC, christianvogt commented on frontend/public/extend/devconsole/routes.tsx
> +  console.log(getActiveNamespace());
Remove `console.log`

2019-03-07 05:46 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const Details = ({obj: s}) => <div className="co-m-pane__body">
yes, this is left over code.
I have kept some of the codes in the PR which are actually unused as of now. However, later on if we might have to show 'Details', we will be able to use it. Should I keep those code or remove it?
I am working on the other changes suggested

2019-03-07 09:59 UTC, rohitkrai03 requested changes

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/components/resource-pages.ts
> +  ComponentModel
Why is this named `ComponentModel`?

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/components/utils/link.jsx
> +export const namespacedPrefixes = ['/search', '/status', '/k8s', '/overview', '/catalog', '/provisionedservices', '/operators', '/operatormanagement', '/devconsole/codebases'];
I don't think this is needed here as the route for codebases is defined in dev console routes.

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +import * as _ from 'lodash-es';
This is should be `.tsx` file instead of `.jsx`. Also, name the should be `CodebaseList.tsx`. Follow proper naming conventions while naming react components and files.

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentHeader = props => <ListHeader>
Why is the component named `ComponentHeader`? Shouldn't it be `CodebasesHeader` or `CodebasesListHeader`?

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentHeader = props => <ListHeader>
Also use parentheses to wrap multiline JSX return statements. 
```suggestion
const ComponentHeader = (props) => (
  <ListHeader>
  </ListHeader>
)
```

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentHeader = props => <ListHeader>
Add prop types using typescript interfaces. Also add proper type definitions for your components.
```suggestion
const ComponentHeader: React.FunctionComponent = (props: HeaderProps) => (
  <ListHeader>
)
```

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentHeader = props => <ListHeader>
Add prop types using typescript interfaces. Also add proper type definitions for your components.
```suggestion
const ComponentHeader: React.FunctionComponent<HeaderProps> = (props: HeaderProps) => (
  <ListHeader>
)
```

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentPage = props => <ListPage canCreate={false} ListComponent={ComponentList} {...props} />;
Why does `CodebaseList.tsx` file exports three different components named `ComponentList`,  `ComponentPage` and `ComponentDetailsPage`? We should have one main component p[er file and use `export default <ComponentName>`

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/pages/ViewCodebase.jsx
> +import * as _ from 'lodash-es';
Use `.tsx` files only for creating any component. Also, names of the files inside `pages` folder should be simple like `Codebases.tsx`. The corresponding component name should be then `CodebasesPage` signifying that the component is a page component.

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/routes.tsx
>    {
Please rebase with `master-next` branch. The namespace has been changed from `/devconsole` to `/devops`

2019-03-07 09:59 UTC, rohitkrai03 commented on frontend/public/models/index.ts
> +export const ComponentModel: K8sKind = {
This should ideally be inside devconsole folder and imported from there. And should the name be `CodebaseModel`?

2019-03-07 10:09 UTC, abhinandan13jan commented on frontend/public/components/resource-pages.ts
> +  ComponentModel
@rohitkrai03 as per GitSRC POC(CRD), the resources have been put up as Kind:"Component". I am adhering to the in use naming convention - <kind>Model

2019-03-07 10:10 UTC, abhinandan13jan commented on frontend/public/components/utils/link.jsx
> +export const namespacedPrefixes = ['/search', '/status', '/k8s', '/overview', '/catalog', '/provisionedservices', '/operators', '/operatormanagement', '/devconsole/codebases'];
@rohitkrai03 :This is for activating the namespaceBar (top-left component) which is specified in app.jsx

2019-03-07 10:14 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentPage = props => <ListPage canCreate={false} ListComponent={ComponentList} {...props} />;
@rohitkrai03 there are two different full page views rendered by the component one being ComponentDetailsPage which is activated in a different route as per the existing architecture, and ComponentList and ComponentPage are being consumed by 'resource-page' to render the respective list in another route as per the existing architecture

2019-03-07 10:18 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/routes.tsx
> +const getCodebaseRedirection = () => {
added as generic

2019-03-07 10:18 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +    <p>{s.metadata.name}</p>
added as ResourceLink

2019-03-07 17:54 UTC, christianvogt commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentHeader = props => <ListHeader>
Run prettier!

2019-03-07 17:57 UTC, christianvogt commented on frontend/public/extend/devconsole/components/codebases/codebaselist.jsx
> +const ComponentPage = props => <ListPage canCreate={false} ListComponent={ComponentList} {...props} />;
This is a clone of the console code where they put a lot in a single file.
Moving forward we should strive to have a single component per file. These can be grouped in a sub-dir.
Single component per file is a best practice. It's ok to have some internal components within the same file but ideally we separate out every component into separate files.

I know this isn't something that console is doing but some of their files are also large and hard to understand. We're going to work with console and other teams as we strive for closer integration to align on conventions.

2019-03-07 17:58 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/ViewCodebase.jsx
> +import * as _ from 'lodash-es';
Also, importing all of lodash is bad. Only import the parts that you need.

2019-03-07 17:58 UTC, christianvogt commented on frontend/public/models/index.ts
> +export const ComponentModel: K8sKind = {
I think the name reflects the crd.

2019-03-10 11:18 UTC, abhinandan13jan commented
@christianvogt @rohitkrai03 

- Separated  out to one component one file. Moved all code to tsx. 
- Added CodebaseProps interface to Codebases.tsx. 
- Put up genric redirection logic in getRedirection() function in routes.tsx. 
- Separated Custom resources to individual files for better access. Use oc create -f <path> --namespace=<namespace> to apply different resources.
- Updated components to CodebaseList, CodebasePage etc from ComponentList, ComponentPage and exported as default.
- Kept name ComponentModel as is as per the Resource naming convention. Please note once we have the final CRD and Resources in place we will have to update this anyway
Please review

2019-03-14 02:45 UTC, joshuawilson commented
It doesn't look like you rebased it properly.

2019-03-14 12:15 UTC, abhinandan13jan commented
closing with new PR in place
https://github.com/talamer/console/pull/14/

2019-03-14 12:15 UTC, closed without merging