feat(Advanced-Options): add pure component for Scaling
talamer/console pull request #118
Opened 2019-05-30 12:11 UTC by debsmita1

This PR includes:

- A  pure component for Advanced Options: Scaling
- The Number Spinner for field `Replicas` displays an error when non-integer or negative integer is entered

![Scaling](https://user-images.githubusercontent.com/22490998/58631952-bc5e1880-8301-11e9-8d00-b5367bf364bd.gif)

Refer Jira Story : https://jira.coreos.com/browse/ODC-821

2019-05-30 13:51 UTC, rohitkrai03 commented
@debsmita1 Don't integrate into git import form right now, that whole file is going to go away or re-written from scratch. The story is just about creating the component.

2019-05-30 18:51 UTC, sahil143 reviewed
@debsmita1 Scaling shouldn't allow values below zero if they are not valid. Disable the `-` button when value hits zero or accepts the minimum valid value as a prop.
![Peek 2019-05-31 00-15](https://user-images.githubusercontent.com/9278015/58656166-6dcc7080-8339-11e9-9e03-45de2dc4ad70.gif)

2019-05-31 17:13 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  replicas: string;
Is there anything specific that this is typed as a 'string' and not as a 'number'?

2019-06-03 16:57 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  replicas: string;
Changed it to `number`

2019-06-03 18:08 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +        <h2 className="odc-scaling">
We need common components for these form headers. Is there not already one available?

2019-06-03 18:08 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +          <ControlLabel>Replicas</ControlLabel>
Does this label get linked to the form field? ie. when you click it does it focus on the number input?

2019-06-03 18:08 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +        <h2 className="odc-scaling">Scaling</h2>
Need common components for headings so we do not all create custom CSS.

2019-06-04 08:08 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +        <h2 className="odc-scaling">Scaling</h2>
Used `Title` patternfly component https://github.com/talamer/console/pull/118/commits/4b235476926e963291946907f926f3fe335f40dc

2019-06-04 08:09 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +          <ControlLabel>Replicas</ControlLabel>
Fixed it by adding `controlId` in the `FormGroup` https://github.com/talamer/console/pull/118/commits/4b235476926e963291946907f926f3fe335f40dc

2019-06-04 08:09 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +        <h2 className="odc-scaling">
Used `Title` patternfly component https://github.com/talamer/console/pull/118/commits/4b235476926e963291946907f926f3fe335f40dc

2019-06-04 12:15 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +        <Text className="odc-scaling-info" component={TextVariants.h5}>Replicas are scaled manually based on CPU usage.</Text>
Why is this anything other than normal text?
Can we remove this `odc-scaling-info`?
@rohitkrai03 please work with the rest of the team making forms to align on a set of common patterns to adhere to. I don't see why any one form component would need custom styles.

2019-06-05 12:02 UTC, christianvogt commented
By validating on the fly in the render function, the parent form will never know of the validation state.
We should create utilities for each form component to support validating form fields. The parent form can use these utilities to manage form validation. This would mean that the field errors need to be given as props.
@rohitkrai03 please align with the team on the approach for form components so that we are all doing the same thing and it fits with what you propose with formik

2019-06-05 12:04 UTC, rohitkrai03 requested changes

2019-06-05 12:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +        <Text className="odc-scaling-info" component={TextVariants.h5}>Replicas are scaled manually based on CPU usage.</Text>
@debsmita1 Why are you using some components from `Patternfly 4` and some from `Patternfly 3`? I think it should be a consistent experience and right now we are using patternfly 3 for forms so it makes sense to use it everywhere in the forms.

2019-06-05 12:07 UTC, rohitkrai03 commented
@christianvogt Yes, i agree with the validation method. The forms can just provide a utility function to validate the fields and then it can be used by parent form to validate the fields. Formik has both the options of validating whole form at once and field level validation. Some of the fields would need field level validation such as Git URl which needs async call for git source analysis and build tool detection.

2019-06-05 13:24 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +        <Text className="odc-scaling-info" component={TextVariants.h5}>Replicas are scaled manually based on CPU usage.</Text>
Replaced the `Text` component with `div` https://github.com/talamer/console/commit/ad90aaa52292b1bfcc76a3d620460b238ee5b98a

2019-06-05 13:37 UTC, rohitkrai03 requested changes

2019-06-05 13:37 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +    props.onChange(event.currentTarget.valueAsNumber, props.replicaError);
Why are you sending props.replicaError with `onChange`?

2019-06-05 13:37 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +    props.onChange(_.toInteger(props.replicas) + operation, props.replicaError);
Same as above.

2019-06-05 13:37 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +const Scaling: React.FC<ScalingProps> = (props) => {
Destructure the props here.

2019-06-05 13:41 UTC, rohitkrai03 requested changes

2019-06-05 13:41 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +          onChange={onChangeData}
`NumberSpinner` component doesn't accept or use `onChange`. So you can remove this.

2019-06-05 13:41 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +          changeValueBy={changeValueBy}
```suggestion
          changeValueBy={(operation: number) => onChange(_.toInteger(replicas) + operation)}
```

2019-06-05 14:19 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +          changeValueBy={changeValueBy}
Done https://github.com/talamer/console/commit/016aa32a785bc1e8032f0e610309e203573399d7

2019-06-05 14:22 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +const Scaling: React.FC<ScalingProps> = (props) => {
Done 016aa32

2019-06-05 14:23 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +    props.onChange(event.currentTarget.valueAsNumber, props.replicaError);
Removed it 016aa32

2019-06-05 14:25 UTC, debsmita1 commented
@rohitkrai03 The `onChange` prop in the `NumberSpinner` is used in cases where user enter values manually

2019-06-05 15:19 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +  replicaError: string;
`replicaError` and `replica` should be optional.

2019-06-05 15:19 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +export const isPositiveInteger = (replicas: number) => {
This is fine for now to be here. We can align the validation strategy with other form sections as @rohitkrai03 completes the formik integration.

2019-06-05 16:12 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/Scaling.tsx
> +  replicaError: string;
Done

2019-06-05 16:37 UTC, rohitkrai03 approved these changes
LGTM

2019-06-05 16:37 UTC, merged