number input widget
talamer/console pull request #119
Opened 2019-05-31 00:36 UTC by christianvogt

@debsmita1 

Here's a number input that prevents the user from inputing numbers beyond a certain range.
If it's useful at all we can look at adding the functionality to console.

cc @rohitkrai03

2019-05-31 10:59 UTC, rohitkrai03 requested changes

2019-05-31 10:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/NumberInput.tsx
> +export default class NumberSpinner extends React.Component<NumberInputProps, State> {
Filename and components are different. Maybe rename the file to `NumberSpinner.tsx`?

2019-05-31 10:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/NumberInput.tsx
> +export default class NumberSpinner extends React.Component<NumberInputProps, State> {
Also prop type name `NumberInputProps` -> `NumberSpinnerProps`

2019-05-31 10:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/NumberInput.tsx
> +          className={cx('fa fa-minus-square co-m-number-spinner__down-icon', { disabled })}
Use `@patternfly/react-icons` instead of font awesome. Also, i don't see any CSS file defining `co-m-number-spinner__down-icon` class

2019-05-31 10:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/NumberInput.tsx
> +          className={cx(className, 'co-m-number-spinner__input')}
Where is the styles for `co-m-number-spinner__input` defined?

2019-05-31 10:59 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/NumberInput.tsx
> +          className={cx('fa fa-plus-square co-m-number-spinner__up-icon', { disabled })}
Same as above.

2019-05-31 11:01 UTC, rohitkrai03 commented
@christianvogt Is it just for showing something as an example here for us or @debsmita1 to build or its a PR to get it in our code?

2019-05-31 13:01 UTC, christianvogt commented
@rohitkrai03 yes it was just an example :P i spent very little time doing this. I just brought in the logic from my widgets and hooked it up to the console number-spinner. 
Only if it seems valid will I spend more time on it.

2019-05-31 17:03 UTC, abhinandan13jan commented
@christianvogt @rohitkrai03 Although I am out of context here will like to make a quick suggestion. If we plan to setup `upper` and `lower` limits for the input fields, we might want to consider the server side `supported range` for data, unless all values are exclusively treated as 'strings' as we see in the yamls.
I faced a classic case in OSIO
https://github.com/openshiftio/openshift.io/issues/4267

2019-06-14 20:38 UTC, sbose78 commented
`build and deploy`

2020-08-20 16:31 UTC, closed without merging