Add unit tests for temp switcher menu
talamer/console pull request #12
Opened 2019-03-06 10:30 UTC by divyanshiGupta

Task : https://jira.coreos.com/browse/ODC-127

2019-03-06 17:13 UTC, christianvogt requested changes
Also please run the linter.

2019-03-06 17:13 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +  let _isNavOpen: boolean = false;
Remove. This is unnecessary if you simplify the creation of the `PerspectiveSwitcher`.

2019-03-06 17:13 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +  const _onNavToggle = () => {
Remove for same reason as above.

2019-03-06 17:13 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +        isNavOpen={_isNavOpen}
If you want to create this in the `beforeEach`, then use static values as the initial render. Otherwise render directly within the test case itself or create a function accepting props to pass to the switcher.

I see that console has adopted the pattern of rendering the the `wrapper` in `beforeEach` and using `setProps` to change the `props`. However this is not always the best approach as initial rendering vs prop updates are two different paths. For most components they yield the same result so the choice is often arbitrary.

Rendering the component in the test itself is often more clear to the reader of test.

2019-03-06 17:13 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +  it('should have devops and admin console nav links', () => {
Not sure how much value this test adds as it simply tests "is there an arbitrary element with an `id`". Wherein the `id` has no significant value other than as a locator.

A test should perform a comparison of some significant piece of data.

2019-03-06 17:13 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +    _onNavToggle();
This really is not needed, as the following line can pass in `true` as the value.

2019-03-07 09:21 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +        isNavOpen={_isNavOpen}
> Rendering the component in the test itself is often more clear to the reader of test.

So initially I did it this way but then I thought adding it in before each will be a better approach as rendering of switcher is one thing that is common between all the test cases and in that way I do not need to add same lines of code in each test. But if we want to pass static values then it would be better to add it in each test case.

2019-03-07 09:25 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +  it('should have devops and admin console nav links', () => {
I just wanted to test if the devops and admin perspective links get rendered properly and I was not sure how to do that. So I thought of adding ids to the respective links and then check if the links exist or not. I will remove this test.

2019-03-07 14:53 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +          id="devops"
These `id`s are no longer needed.

2019-03-07 21:39 UTC, christianvogt approved these changes

2019-03-07 21:40 UTC, merged