add build config option component
talamer/console pull request #120
Opened 2019-05-31 10:03 UTC by vikram-raj

Story - https://jira.coreos.com/browse/ODC-819

This change adds build configuration pure component.

```Typescript
<BuildConfig
  onConfigureWebhookChange={this.onConfigureWebhookChange}
  onAutomaticallyBuildChange={this.onAutomaticallyBuildChange}
  onLaunchFirstBuildChange={this.onLaunchFirstBuildChange}
  onEnviromentVariableChange={this.onEnviromentVariableChange} />
```

2019-05-31 11:08 UTC, rohitkrai03 requested changes

2019-05-31 11:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +  onConfigureWebhookChange = () => {}
What is this function declaration for?

2019-05-31 11:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +  render() {
You can convert this to a function component `React.FC<BuildConfigProps>` since all the props are just callbacks. No need to use `React.PureComponent`.

2019-05-31 11:16 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +  onConfigureWebhookChange = () => {}
This is not required. I forgot to remove it.

2019-05-31 11:32 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +  render() {
Agree, Changed it to a functional component.

2019-06-03 13:33 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +          <FieldLevelHelp content="A build configuration describes how to build your deployable image. This includes your source, the base builder image, and when to launch new builds." />
UX doesn't want us to add the help links right now.

2019-06-03 13:33 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.scss
> +  &__header {
If we do need custom styles, I'd prefer we use shared components for each section.

2019-06-03 13:33 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +  onEnviromentVariableChange: (obj: Object) => void;
Need a proper type and not `Object`

2019-06-03 13:33 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/__tests__/BuildConfig.spec.tsx
> +    expect(buildConfig).toBeTruthy();
Not a very useful test :P
if anything the tests should simulate field changes to test that the callbacks were executed properly.

2019-06-03 13:33 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +      <div className="odc-build-config__env-variable">
`odc-build-config__env-variable` isn't defined anywhere. Remove the custom class.

2019-06-03 13:33 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +          <input type="checkbox" id="configure-webhook" onChange={onConfigureWebhookChange} />
I don't like the use of static IDs here. But I suppose it's ok for now. For future it would be good to create a re-usable component that provides the label and input and assigns appropriate IDs that get generated and globally unique.
PF4 has something like this I believe but we cannot use it yet ;/ Maybe look at their API when we do this.

2019-06-03 13:59 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +          <FieldLevelHelp content="A build configuration describes how to build your deployable image. This includes your source, the base builder image, and when to launch new builds." />
I will remove this help link. Because of this help text, I am using the HTML tags for the form field. Now, I can use the ```Checkbox``` component from ```patternfly/react-core```.

2019-06-05 05:12 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +          <input type="checkbox" id="configure-webhook" onChange={onConfigureWebhookChange} />
Replaced this HTML input and label tags with Checkbox component which defines in console utils.

2019-06-05 05:13 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +      <div className="odc-build-config__env-variable">
removed this unused class.

2019-06-05 07:09 UTC, divyanshiGupta requested changes

2019-06-05 07:09 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +    this.state = {
@vikram-raj this component is not a pure component as this is maintaining a state but this should be a pure component as the state will be maintained by the parent. Also you can simply create this as a Function Component once you remove the state.

2019-06-05 10:02 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +    this.state = {
Done. Changed it to a pure component.

2019-06-05 16:51 UTC, divyanshiGupta requested changes

2019-06-05 16:51 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +      <Checkbox
You can also use `Checkbox` form pf3, so when we will migrate to pf4 we have to just change the import.

2019-06-05 16:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +import { EnvironmentPage } from './../../../../../public/components/environment';
You went up one dir too far. Doesn't need too include the `public` dir.

2019-06-05 16:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +  onEnviromentVariableChange: (obj: NameValueType | NameValueFormType) => void;
The param is an array of values.
```suggestion
  onEnviromentVariableChange: (envPairs: (NameValueType | NameValueFormType)[]) => void;
```

2019-06-05 16:53 UTC, christianvogt commented
Also run prettier on the file.

2019-06-06 08:09 UTC, divyanshiGupta approved these changes
@vikram-raj code looks good to me. Just one thing, in `BuildConfig.tsx` there is no space between the interfaces, fix that.

2019-06-06 12:55 UTC, christianvogt commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +interface BuildConfigProps {
Where's the prop for supplying the env vars?
Probably not needed right now but future plans was to attempt to reuse the same form for an edit scenario in which case we will want to prefill the form.

2019-06-09 21:00 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/build-config/BuildConfig.tsx
> +interface BuildConfigProps {
Added prop to take buildConfig.

2019-06-09 21:01 UTC, vikram-raj commented
Updated the PR. Please review it again @christianvogt @rohitkrai03

2019-06-10 09:36 UTC, rohitkrai03 approved these changes
LGTM

2019-06-10 09:37 UTC, merged