Pipeline actions
talamer/console pull request #121
Opened 2019-05-31 13:09 UTC by abhinandan13jan

This PR covers the pipeline action stories
https://jira.coreos.com/browse/ODC-893
https://jira.coreos.com/browse/ODC-987 
https://jira.coreos.com/browse/ODC-848
https://jira.coreos.com/browse/ODC-847
To validate the working of the functions:
1. Run the `install_pipeline_pipelines.sh` from `devconsole/shared/yamls/pipelines
2. Check `PipelineList`, `PipelineDetailsPage` and `PipelineRunsList` for the actions

![Screenshot from 2019-05-31 18-27-43](https://user-images.githubusercontent.com/24852534/58707480-b71cce80-83d2-11e9-9951-1923706a287d.png)
![Screenshot from 2019-05-31 18-27-53](https://user-images.githubusercontent.com/24852534/58707481-b71cce80-83d2-11e9-89e7-aa13e7da3e3d.png)
![Screenshot from 2019-05-31 18-27-59](https://user-images.githubusercontent.com/24852534/58707482-b7b56500-83d2-11e9-968f-d35a062dfe15.png)
![Screenshot from 2019-05-31 18-28-13](https://user-images.githubusercontent.com/24852534/58707483-b7b56500-83d2-11e9-8d2e-f3b531724302.png)
![Screenshot from 2019-05-31 18-28-24](https://user-images.githubusercontent.com/24852534/58707484-b7b56500-83d2-11e9-8b53-43af2270129a.png)
![Screenshot from 2019-05-31 18-28-53](https://user-images.githubusercontent.com/24852534/58707486-b84dfb80-83d2-11e9-9c5a-e16c25659eb9.png)
![Screenshot from 2019-05-31 18-29-13](https://user-images.githubusercontent.com/24852534/58707487-b84dfb80-83d2-11e9-9bc9-a473389a06f7.png)

2019-06-03 09:33 UTC, divyanshiGupta requested changes

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +}
Add a new line after this

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +interface Props {
Can you change `Props` to `PipelineRowProps` ?

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +interface States {
`State` -> `PipelineRowState`

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +}
Add a line after this

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +          {pipeline.latestRun && pipeline.latestRun.metadata && pipeline.latestRun.metadata.name ? (
You can do this 
```
{pipeline.latestRun && pipeline.latestRun.metadata && pipeline.latestRun.metadata.name 
  && <ResourceLink kind="PipelineRun" name={pipeline.latestRun.metadata.name} namespace={pipeline.latestRun.metadata.namespace}/>}
```

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/yamls/pipelines/pipelinerun.yaml
> +  selfLink: ""
Add a new line at the end of the file

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/yamls/pipelines/resources.yaml
> +  selfLink: ""
Add a new line at the end of the file

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/yamls/pipelines/task.yaml
> +---
Add a new line at the end of the file

2019-06-03 09:33 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/yamls/pipelines/taskrun.yaml
> +
Add a new line at the end of the file

2019-06-03 13:05 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +}
changed

2019-06-03 13:05 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +interface Props {
changed

2019-06-03 13:05 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +interface States {
changed

2019-06-03 13:05 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +}
done

2019-06-03 13:06 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +          {pipeline.latestRun && pipeline.latestRun.metadata && pipeline.latestRun.metadata.name ? (
I know what you suggest is a better approach but in this case I need to output "-" for the else case

2019-06-03 13:06 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/shared/yamls/pipelines/pipelinerun.yaml
> +  selfLink: ""
done

2019-06-03 13:06 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/shared/yamls/pipelines/resources.yaml
> +  selfLink: ""
done

2019-06-03 13:06 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/shared/yamls/pipelines/task.yaml
> +---
done

2019-06-03 13:06 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/shared/yamls/pipelines/taskrun.yaml
> +
done

2019-06-03 13:07 UTC, abhinandan13jan commented
@divyanshiGupta Thanks for the suggestions. Made the changes. Please review.

2019-06-03 18:22 UTC, divyanshiGupta commented
@abhinandan13jan one test in `pipeline-augment.spec.ts` is failing
```
 PipelineAugment test gcorrect data is augmented › 2. expect additional resources to be added using latest run

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      "apple-1-run2"
    Received:
      "apple-1-run1"
```

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +const PipelineRow = (props: PipelineRowProps) => {
use `React.FC< PipelineRowProps>`

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +interface PipelineRowStates {
Doesn't look like this state is even used. Remove it.

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +class PipelineRow extends React.PureComponent<PipelineRowProps, PipelineRowStates> {
If state isn't used. Change to `React.FC< PipelineRowProps>`

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelines/__tests__/pipeline-actions.spec.ts
> +  it('1. expect label to be "Trigger Last Run" when latestRun is available', () => {
Numbering tests is not a pattern we follow.
See examples https://mochajs.org/ for test names.
`it('expects label to be "Trigger Last Run" when latestRun is available'`
The function name `it` is read as part of the name `it expects ...`
Most often a test case starts with `it('should...` but that's not a hard rule.

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +    console.error('Unable to create new PipelineRun. Mising "metadata" in ', pipeline);
```suggestion
    console.error('Unable to create new PipelineRun. Missing "metadata" in ', pipeline);
```

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +          !window.location.href.endsWith('/Runs')
These `window.location.href` checks are bad. The caller of `triggerPipeline` should setup the redirect URL based on it's knowledge of where it wants to go.

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      k8sGet(PipelineModel, pipelineRun.spec.pipelineRef.name, pipelineRun.metadata.namespace).then(
This call shouldn't be necessary in order to create a new pipeline run from an existing one. Everything should be present already in the pipeline run no?

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +            labelSelector: { 'tekton.dev/pipeline': res.metadata.name },
`res.metadata.name` === `pipelineRun.spec.pipelineRef.name` ?

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +              newPipelineRun(res, {
I know you created `newPipelineRun` to take the `pipeline` instance, but is that even necessary? Seems to me like it wouldn't be.

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        !window.location.href.endsWith('/Runs')
These window.location.href checks are bad. The caller of triggerPipeline should setup the redirect URL based on it's knowledge of where it wants to go.

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      label: <div className="dropdown__disabled">Stop Pipeline</div>,
```suggestion
      label: <div className="dropdown__disabled">Stop Pipeline Run</div>,
```

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +    return (kind, obj) => ({
Missing types.

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +  return (kind, obj) => ({
missing Types

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +export const stopPipelineRun = (pipelineRun: PipelineRun): Function => {
Return `Function` should be properly typed.

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      params: pipeline.spec && pipeline.spec.params ? pipeline.spec.params : null,
Why is this coming from the `pipeline`? Shouldn't this come from `latestRun`?

2019-06-04 03:18 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +  location.href = resourceUrl;
use `history.push` instead where `history` comes from the `utils` package

2019-06-04 18:11 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      params: pipeline.spec && pipeline.spec.params ? pipeline.spec.params : null,
yes, my bad

2019-06-04 18:11 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +  location.href = resourceUrl;
done

2019-06-04 18:11 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +export const stopPipelineRun = (pipelineRun: PipelineRun): Function => {
typed

2019-06-04 18:11 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +  return (kind, obj) => ({
added types

2019-06-04 18:11 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +    return (kind, obj) => ({
added types

2019-06-04 18:12 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +          !window.location.href.endsWith('/Runs')
updated

2019-06-04 18:12 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        !window.location.href.endsWith('/Runs')
updated

2019-06-04 18:27 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +            labelSelector: { 'tekton.dev/pipeline': res.metadata.name },
updated

2019-06-04 18:28 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +              newPipelineRun(res, {
This is to make sure that in case there is any missing `field` param,reference,resources,namespace,label in `PipelineRun`, the gap is bridged by the `fields` from the `Pipeline`. But you are right these all will be present. I'll do a thorough testing and check if we can entirely rely on PipelineRun details. Let it be like this, I'll do the necessary testing and update in next sprint if not tomorrow.

2019-06-04 18:28 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      k8sGet(PipelineModel, pipelineRun.spec.pipelineRef.name, pipelineRun.metadata.namespace).then(
This is to make sure that in case there is any missing `field` param,reference,resources,namespace,label in `PipelineRun`, the gap is bridged by the `fields` from the `Pipeline`. But you are right these all will be present. I'll do a thorough testing and check if we can entirely rely on PipelineRun details. Let it be like this, I'll do the necessary testing and update in next sprint if not tomorrow.

2019-06-04 18:39 UTC, abhinandan13jan commented
@christianvogt I have made all the changes required and left a remark for the pipeline fetching that is happening right now. Please review.
@divyanshiGupta Please review the changes requested by you.

2019-06-04 21:10 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +              newPipelineRun(res, {
My thought here is that if I'm re-running a pipeline I expect it to utilize all the same parameters as originally run. Please confirm with the tekton team the expected behavior.

2019-06-05 06:02 UTC, divyanshiGupta approved these changes

2019-06-05 07:27 UTC, karthikjeeyar commented
@abhinandan13jan  Please try to run in AWS cluster or CRC, I get errors in console while trying in AWS cluster.

2019-06-05 11:34 UTC, rohitkrai03 approved these changes
LGTM

2019-06-05 11:34 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/pipelines/PipelineDetailsPage.tsx
> +interface PipelineDetailsPageProps extends DetailsPageProps {}
Why extend this interface if you are not adding anything here? Just use `DetailsPageProps`

2019-06-05 11:45 UTC, abhinandan13jan commented
> @abhinandan13jan Please try to run in AWS cluster or CRC, I get errors in console while trying in AWS cluster.

@karthikjeeyar  As discussed, it works after pulling from the latest commits

2019-06-05 12:01 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineDetailsPage.tsx
> +interface PipelineDetailsPageProps extends DetailsPageProps {}
updated. Initially was using some additional props but forgot to remove the extended class after removing them. Thanks for pointing out. :)

2019-06-05 12:31 UTC, invincibleJai commented
build and deploy

2019-06-05 12:31 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit31.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-121-openshift-console.apps.rohit31.devcluster.openshift.com

2019-06-05 15:58 UTC, serenamarie125 submitted a review, later dismissed
@abhinandan13jan please change the "Trigger" action on the Pipeline Run to "Rerun".

2019-06-05 16:00 UTC, christianvogt reviewed
Rename `PipelinerunModel` to `PipelineRunModel`

2019-06-05 16:00 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +        <div className="dropdown-kebab-pf">
The kebab should not be inside a column. Look at the admin console pages for reference. This is causing the kebab to be mis-aligned:
![image](https://user-images.githubusercontent.com/14068621/58969452-ba72da00-8785-11e9-886d-5514b7cf3c22.png)

2019-06-05 16:00 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        if (redirectURL && redirectURL !== '') {
Remove `redirectURL !== ''` as this is already covered by the first condition.

2019-06-05 16:00 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      k8sList(PipelinerunModel, {
I'm confused why you are fetching other pipeline runs in order to re-run the one you already reference.

2019-06-05 16:00 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +        <div className="dropdown-kebab-pf">
kebab should not be inside of a column.

2019-06-05 16:00 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +    label: 'Trigger',
```suggestion
    label: 'Rerun',
```

2019-06-05 16:00 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +                name: getLatestRun({ data: listres }, 'creationTimestamp').metadata.name,
If we are re-running the same pipeline run again, why are you getting the name of another pipeline run?

2019-06-10 12:07 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +        <div className="dropdown-kebab-pf">
updated

2019-06-10 12:08 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        if (redirectURL && redirectURL !== '') {
removed

2019-06-10 12:17 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      k8sList(PipelinerunModel, {
I was trying to get the `metadat.name` of the `latest run` in order to create a new run with `name` `latestRun-naming-logic`. As PipelineRuns are immutable we cannot  `rerun/restart` a `PipelineRun`, instead create a new `pipelinerun`. Using any `existing names` would create conflicts while creating the new PipelineRun

Right now I've changed the logic to first remove/delete the selected `PipelineRun` and then create a new `PipelineRun`. However in the current case the original `PipelineRun` object itentified by {resourceVersion:uniquenumber} will be lost and a new `PipelineRun` with the same name will be created.

2019-06-10 12:18 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +        <div className="dropdown-kebab-pf">
moved and placed it as per the existing pattern

2019-06-10 12:19 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +    label: 'Trigger',
Updated

2019-06-10 12:23 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +                name: getLatestRun({ data: listres }, 'creationTimestamp').metadata.name,
fixed

2019-06-10 12:26 UTC, abhinandan13jan commented
@christianvogt @serenamarie125 Renamed `PipelinerunModel` to `PipelineRunModel` and `Trigger` to 'Rerun` for pipelineRuns

2019-06-10 16:25 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      k8sList(PipelinerunModel, {
@abhinandan13jan we should not be removing the old pipeline. Maybe I should have been more clear. I was curious why we needed the pipeline and couldn't use the pipeline run to retrieve the information we need to create a new pipeline run.

2019-06-11 07:42 UTC, abhinandan13jan commented
@serenamarie125 @christianvogt I've made the  required changes as per the discussion in Pipeline channel. Please approve and merge the PR as this is blocking the PipelineRunVisualization PR by @karthikjeeyar . I will be able to make the visual changes like label name from rerun->trigger in the next sprint.

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelines/PipelineDetailsPage.tsx
> +    k8sGet(PipelineModel, this.props.name, this.props.namespace).then((res) => {
This can become stale if you aren't using firehose. 
If a pipeline later has a pipeline run, then the menu action for rerun pipeline will remain disabled.

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +  redirectURL: string,
```suggestion
  redirectURL?: string,
```
So you can provide a null value instead of an empty string.

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +    basePath = '/dev/k8s';
In one case, the URL ends with a slash and in the other case it doesn't.

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +  redirectURL: string,
```suggestion
  redirectURL?: string,
```
So you can provide a null value instead of an empty string.

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        redirectToResourceList(redirectURL);
Should we not wait to redirect?

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +      if (redirectURL && redirectURL !== '') {
```suggestion
      if (redirectURL) {
```

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +                name: getLatestRun({ data: listres }, 'creationTimestamp').metadata.name,
Why is this not just `pipelineRun.metadata.name` + random suffix or `pipelineRun.spec.pipelineRef.name` + random suffix?

2019-06-11 17:09 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        labelSelector: { 'tekton.dev/pipeline': pipelineRun.spec.pipelineRef.name },
I still don't see why you need to fetch the pipeline for this use case.

2019-06-11 18:07 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +                name: getLatestRun({ data: listres }, 'creationTimestamp').metadata.name,
Isn't it better to have a numbered list of PipelineRuns? Plus, although the probability is low, we can still have name conflicts using pseudo random name generation.

2019-06-11 18:16 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        labelSelector: { 'tekton.dev/pipeline': pipelineRun.spec.pipelineRef.name },
It's not fetching the Pipeline. 
Suppose, `Pipeline-A`, has 3 runs namely, `Pipline-Run-A-1`, `Pipline-Run-A-2`, `Pipline-Run-A-3` named with the numbering algorithm as per their execution order. At the List Row level, I don't have this information. We only have details of one particular *PipelineRun* say `Pipeline-Run-A` and not of the corresponding `Pipeline` or the other Runs. Now if I click on `Rerun` action against `Pipeline-Run-A-1` a new `PipelineRun` must be created and the name of the new `PipelineRun` needs to be computed using the latestRun details so that their is no name conflict.  
The following will happen, 
the k8sList(RunModel, labelSelector) will fetch the list of all PipelineRuns for `Pipeline-A` and fetch the name of the latestRun, `Pipeline-Run-A-3` and this will be used to create a new PipelineRun with name `Pipeline-Run-A-4`

2019-06-11 23:15 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +              latestRun.metadata.name.slice(0, -1),
So this only removes one number from the end and won't do what you expect if the number is multiple digits. It also doesn't account for the numbers being out of order.
So although random strings can clash, so will this.

2019-06-11 23:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +    rerunPipeline(pipeline, pipeline.latestRun, ''),
If redirect url can be null, no need to provide an empty string, omit the last param.

2019-06-11 23:15 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        labelSelector: { 'tekton.dev/pipeline': pipelineRun.spec.pipelineRef.name },
Seems overkill to fetch a list of resources just to attempt to create a unique Id and yet it's still very fragile.

2019-06-12 03:00 UTC, sbose78 commented
build and deploy

2019-06-12 03:00 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rgarg13.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-121-openshift-console.apps.rgarg13.devcluster.openshift.com

2019-06-12 07:52 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +  redirectURL: string,
done

2019-06-12 07:56 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +    basePath = '/dev/k8s';
fixed

2019-06-12 07:56 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineDetailsPage.tsx
> +    k8sGet(PipelineModel, this.props.name, this.props.namespace).then((res) => {
As discussed, will update in a separate PR

2019-06-12 07:58 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        redirectToResourceList(redirectURL);
updated

2019-06-12 07:58 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +        labelSelector: { 'tekton.dev/pipeline': pipelineRun.spec.pipelineRef.name },
changed to suffix with random string

2019-06-12 07:59 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-actions.tsx
> +              latestRun.metadata.name.slice(0, -1),
changed to use random string suffix

2019-06-12 07:59 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/PipelineRow.tsx
> +    rerunPipeline(pipeline, pipeline.latestRun, ''),
done

2019-06-12 08:02 UTC, abhinandan13jan commented
build and deploy

2019-06-12 11:46 UTC, merged