add Perspective title to Navigation
talamer/console pull request #123
Opened 2019-06-04 10:51 UTC by sahil143

Story: https://jira.coreos.com/browse/ODC-823

![Screenshot from 2019-06-04 16-20-57](https://user-images.githubusercontent.com/9278015/58873837-ce1a3400-86e4-11e9-8427-13e3629275b7.png)
![Screenshot from 2019-06-04 16-21-08](https://user-images.githubusercontent.com/9278015/58873838-ce1a3400-86e4-11e9-9c6e-2a95be865e35.png)

2019-06-04 11:50 UTC, divyanshiGupta requested changes

2019-06-04 11:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +class SideBarHeader extends React.PureComponent<SideBarHeaderProps> {
This can also be a Function Component as it does not have a state and we are not using any life-cycle hooks as well, also it is a very small component so we don't need to make it a class.
```
const SideBarHeader: React.FC<SideBarHeaderProps> = (props: SideBarHeaderProps) => {}
```

2019-06-04 11:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +import { connect } from 'react-redux';
Put absolute imports first then relative and then scss imports.

2019-06-04 11:50 UTC, divyanshiGupta commented on frontend/public/ui/ui-selectors.js
> +export const getActiveNamespace = state => state.UI.get('activeNamespace');
We have a `getActiveNamespace` selector in `ui-actions.js` so to avoid any confusions you can give this selector a different name or you can directly select `activeNamespace` from state in your component itself.

2019-06-04 12:31 UTC, christianvogt commented on frontend/public/components/service-account.jsx
> +export const clusterName = url.host.replace(/\./g, '-');
This should be moved to a common utility. Did you confirm with Sam or anyone from the console team if this is the correct way?

2019-06-04 13:04 UTC, serenamarie125 requested changes
Perspective name should be 16px and #FFFFFF 
Cluster name should be 14px and #D1D1D1

2019-06-04 13:04 UTC, serenamarie125 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Dev Console';
this should be "Developer"

2019-06-04 13:04 UTC, serenamarie125 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Admin Console';
this should be "Administrator"

2019-06-04 13:04 UTC, serenamarie125 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Dev Console';
please include the fa-code icon before the label

2019-06-04 13:04 UTC, serenamarie125 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Admin Console';
please include the fa-cogs icon before the label

2019-06-04 13:40 UTC, serenamarie125 commented
FYI @beanh66

2019-06-04 15:28 UTC, sahil143 commented on frontend/public/components/service-account.jsx
> +export const clusterName = url.host.replace(/\./g, '-');
No, I haven't confirmed this yet. I will confirm it and update it accordingly.

2019-06-04 15:32 UTC, sahil143 commented
>Perspective name should be 16px and #FFFFFF
Cluster name should be 14px and #D1D1D1

@serenamarie125 Can I get the Patternfly color and size variable for these?

2019-06-04 17:08 UTC, christianvogt commented
@sahil143 look in the patternfly repo and find the matching styles.
Keep in mind that our repo is a bit behind in versions so the names don't always match exactly.

2019-06-04 17:10 UTC, serenamarie125 commented
pf-black-300 #d1d1d1

2019-06-04 17:20 UTC, serenamarie125 commented
i think #ffffff is pf-global--Color--light-100 but you will have to verify :)

2019-06-05 07:01 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Admin Console';
@serenamarie125 But the mega menu uses the `fa-cog` icon not `fa-cogs`.
![Screenshot from 2019-06-05 12-30-41](https://user-images.githubusercontent.com/9278015/58936615-c793c700-878d-11e9-841d-48e9754672cc.png)

2019-06-05 07:41 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +class SideBarHeader extends React.PureComponent<SideBarHeaderProps> {
@divyanshiGupta yes, this can be a functional component. But the prop `activePerspective` will only change when the perspective is changed. If we use a functional component here it will continue to rerender whenever the parent component is rendered. That's why I used the PureComponent, to prevent unnecessary renders.

2019-06-05 07:42 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +import { connect } from 'react-redux';
fixed in https://github.com/talamer/console/pull/123/commits/fd9fdd9c546f5394f442a2698da163b9a42c65f7

2019-06-05 07:42 UTC, sahil143 commented on frontend/public/ui/ui-selectors.js
> +export const getActiveNamespace = state => state.UI.get('activeNamespace');
fixed in https://github.com/talamer/console/pull/123/commits/fd9fdd9c546f5394f442a2698da163b9a42c65f7

2019-06-05 07:43 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Dev Console';
fixed in https://github.com/talamer/console/pull/123/commits/fd9fdd9c546f5394f442a2698da163b9a42c65f7

2019-06-05 07:43 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Admin Console';
I used fa-cogs as you suggested. https://github.com/talamer/console/pull/123/commits/fd9fdd9c546f5394f442a2698da163b9a42c65f7

2019-06-05 07:48 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +class SideBarHeader extends React.PureComponent<SideBarHeaderProps> {
Yes, but this is a very small component and it will not affect the performance even if it get rendered every time the perspective changes. Anyways this is also fine.

2019-06-05 09:42 UTC, divyanshiGupta commented
@sahil the following tests failiing
```
 public/extend/devconsole/components/__tests__/DevConsoleNav.spec.tsx
  ● Test suite failed to run

    TypeError: Invalid URL
      
      at new URLImpl (node_modules/whatwg-url/lib/URL-impl.js:19:13)
      at Object.setup (node_modules/whatwg-url/lib/URL.js:187:17)
      at new URL (node_modules/whatwg-url/lib/URL.js:25:18)
      at Object.<anonymous> (public/components/service-account.jsx:44:11)
      at Object.<anonymous> (public/extend/devconsole/shared/components/SideBarHeader.tsx:19:25)

 public/extend/devconsole/components/topology/__tests__/topology-utils.spec.ts
  ● TopologyUtils  › should match the previous snapshot

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
```
For the second test to pass you need to update the stored snapshot.

Also there is this ` 'SideBarHeaderProps' is assigned a value but never used`  lint error in `SideBarHeader.tsx`. Please fix that.

2019-06-05 12:29 UTC, sbose78 commented
build and deploy

2019-06-05 12:29 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit31.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-123-openshift-console.apps.rohit31.devcluster.openshift.com

2019-06-05 16:14 UTC, serenamarie125 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +        return 'Admin Console';
it should be fa-cogs ( plural )

2019-06-05 16:29 UTC, christianvogt reviewed
Can please update the icon in the mega-menu as well to `<CogsIcon />`

2019-06-05 16:29 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.scss
> +  border-bottom: 1px solid #030303;
I know that the admin console customized their colors and it looks like they us `$color-pf-black`
https://github.com/openshift/console/blob/e87c22b23267b08ab0831944d588c82ce41e0de5/frontend/public/style/_overrides.scss#L432

2019-06-05 16:29 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +            <CogsIcon /> Administrator Console
Remove the word `Console`

2019-06-05 16:29 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +            <CodeIcon /> Developer Console
Remove the word `Console`

2019-06-05 16:29 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +      case 'admin':
This should be the default case

2019-06-05 16:29 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +  getNameBasedOnActivePerspective = (activePerspective: string): React.ReactNode => {
Move outside of the component. No need for this to be within the closure of the component class.

2019-06-05 16:29 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +class SideBarHeader extends React.PureComponent<SideBarHeaderProps> {
Use `React.FC` instead.

2019-06-05 16:29 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +export default connect(mapStateToProps)(SideBarHeader);
Can make use of https://github.com/reduxjs/react-redux/blob/master/docs/api/connect.md#pure-boolean

2019-06-05 21:31 UTC, christianvogt commented
@sahil143 please update your image in the description

2019-06-06 07:19 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +export default connect(mapStateToProps)(SideBarHeader);
fixed in https://github.com/talamer/console/pull/123/commits/8dde52a3809e4574f6337757ab4eba61f1865e2f

2019-06-06 07:19 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +class SideBarHeader extends React.PureComponent<SideBarHeaderProps> {
fixed in https://github.com/talamer/console/pull/123/commits/8dde52a3809e4574f6337757ab4eba61f1865e2f

2019-06-06 07:19 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +  getNameBasedOnActivePerspective = (activePerspective: string): React.ReactNode => {
fixed in https://github.com/talamer/console/pull/123/commits/8dde52a3809e4574f6337757ab4eba61f1865e2f

2019-06-06 07:19 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +      case 'admin':
fixed in https://github.com/talamer/console/pull/123/commits/8dde52a3809e4574f6337757ab4eba61f1865e2f

2019-06-06 07:19 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +            <CodeIcon /> Developer Console
fixed in https://github.com/talamer/console/pull/123/commits/8dde52a3809e4574f6337757ab4eba61f1865e2f

2019-06-06 07:20 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +            <CogsIcon /> Administrator Console
fixed in https://github.com/talamer/console/pull/123/commits/8dde52a3809e4574f6337757ab4eba61f1865e2f

2019-06-06 08:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +class SideBarHeader extends React.PureComponent<SideBarHeaderProps> {
@sahil143 There is a benefit of using function components instead of class components since React 16. And you can always use `React.memo` to do the shallow props comparison which avoids unnecessary re-renders. Ref: https://twitter.com/dan_abramov/status/1135431444711563264

2019-06-06 08:14 UTC, divyanshiGupta commented on frontend/public/components/service-account.jsx
> +export const clusterName = url.host.replace(/\./g, '-');
Is this confirmed now?

2019-06-06 11:16 UTC, sahil143 commented on frontend/public/extend/devconsole/shared/components/SideBarHeader.tsx
> +class SideBarHeader extends React.PureComponent<SideBarHeaderProps> {
@rohitkrai03 I changed this to a functional component in the latest commit.

2019-06-06 11:16 UTC, sahil143 commented on frontend/public/components/service-account.jsx
> +export const clusterName = url.host.replace(/\./g, '-');
@divyanshiGupta not yet. Waiting on the reply from sam.

2019-06-06 12:52 UTC, christianvogt commented on frontend/public/components/service-account.jsx
> +export const clusterName = url.host.replace(/\./g, '-');
Regardless we should not be reusing such utilities from other components. They need to be moved to a common utility.
For now I'm ok with copying these lines to avoid the dependency. As changing console code affects our ability to merge right now.

2019-06-06 12:53 UTC, christianvogt commented
Please rebase / squash your commits so that the changes to console code are separate from the changes to dev console.

2019-06-07 12:46 UTC, serenamarie125 commented
@christianvogt @sahil143 
Perspective name should be 16px and #FFFFFF
Cluster name should be 14px and #D1D1D1

2019-06-07 12:55 UTC, serenamarie125 commented
Just used the web inspector - looks like nav items are 14 ... 
Please change perspective name to 14px
and try cluster name at 12px @sahil143 could you add a screenshot with this ( including most of the nav bar ) ?

2019-06-07 14:12 UTC, serenamarie125 commented
@sahil143 can you verify that perspective font size is 16 and the cluster font size is 14 ?  if so 🎉

2019-06-08 09:22 UTC, sahil143 commented
> @sahil143 can you verify that perspective font size is 16 and the cluster font size is 14? 

@serenamarie125 yes, font size is already 16px and 14 px.

2019-06-10 09:58 UTC, rohitkrai03 approved these changes
LGTM

2019-06-10 10:21 UTC, divyanshiGupta commented on frontend/public/components/service-account.jsx
> +export const clusterName = url.host.replace(/\./g, '-');
Probably you shouldn't make any changes to this file since you have created a separate util now for getting cluster-name.

2019-06-10 10:40 UTC, sahil143 commented
@cvogt @serenamarie125 All of the requested changes has been addressed. Please review again.

@divyanshiGupta failed unit tests are fixed in latest changes.

2019-06-10 10:43 UTC, divyanshiGupta approved these changes

2019-06-10 16:23 UTC, merged