add deployment config option component
talamer/console pull request #124
Opened 2019-06-05 12:52 UTC by vikram-raj

Story: - https://jira.coreos.com/browse/ODC-820

This change adds build configuration pure component.

```Typescript
<DeploymentConfig
            onNewImageAvailableChange={this.onConfigureWebhookChange}
            onDeploymentConfigChange={this.onLaunchFirstBuildChange}
            onEnviromentVariableChange={this.onEnviromentVariableChange}
            newImageAvailableChecked={this.state.configureWebhookChecked}
            deploymentConfigChecked={this.state.automaticallyBuildChecked}
            namespace={this.state.namespace}
          />
```

2019-06-05 16:47 UTC, rohitkrai03 requested changes

2019-06-05 16:47 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +const DeploymentConfig: React.FC<BuildConfigProps> = ({onNewImageAvailableChange,
Run prettier on the file.

2019-06-05 16:47 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +  const buildConfigObj = {
I think this should be `deploymentConfigObj`

2019-06-05 16:55 UTC, christianvogt commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +  onEnviromentVariableChange: (obj: NameValueType | NameValueFormType) => void;
The callback contains an array of pairs.
```suggestion
  onEnviromentVariableChange: (envPairs: (NameValueType | NameValueFormType)[]) => void;
```

2019-06-05 16:55 UTC, christianvogt commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +import { EnvironmentPage } from './../../../../../public/components/environment';
Import paths went back one dir too many. Do not need to include `public` dir.

2019-06-05 17:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +interface BuildConfigProps {
Where's the prop for supplying the env vars?
Probably not needed right now but future plans was to attempt to reuse the same form for an edit scenario in which case we will want to prefill the form.

2019-06-06 08:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +            readOnly={false}
Is this always going to be false?

2019-06-06 17:31 UTC, christianvogt commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +    configMapKeyRef: {
In your other pr you have this:
```
interface NameValueFormType {
  name: string;
  valueForm: configMapKeyType | secretKeyRefType;
}
```

Shouldn't they be the same?

2019-06-07 15:48 UTC, divyanshiGupta requested changes

2019-06-07 15:48 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +import { Checkbox } from './../../../../../public/components/checkbox';
I think if you are using pf3  `CheckBox` for `build-config` then you should use that here as well.

2019-06-07 16:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +import { Checkbox } from './../../../../../public/components/checkbox';
Does anyone know why this checkbox exists in console today over PF3...

2019-06-07 16:19 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +import { Checkbox } from './../../../../../public/components/checkbox';
Not sure, it just wraps the checkbox and its label together. They are using this in two places `attach-storage.tsx` and `create-pvc.tsx`. Though they are also using the pf3 checkbox in some places and default html input checkbox in some :P

2019-06-07 16:22 UTC, christianvogt commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +import { Checkbox } from './../../../../../public/components/checkbox';
Evolution is a b....
Should talk to sam and create a tech debt issue in their jira with the findings.

2019-06-09 20:48 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +interface BuildConfigProps {
added a prop which takes deploymentConfig. https://github.com/talamer/console/pull/124/commits/10ab1d93ef0e21fcba3c67d773350e51518435a7

2019-06-09 20:49 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +    configMapKeyRef: {
Updated. Yes, it should be same.

2019-06-09 20:50 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/deployment-config/DeploymentConfig.tsx
> +import { Checkbox } from './../../../../../public/components/checkbox';
Done. imported the ```Checkbox``` component from pf3.

2019-06-09 20:50 UTC, vikram-raj commented
Updated the PR. Please review it again @rohitkrai03 @christianvogt @divyanshiGupta

2019-06-10 06:16 UTC, divyanshiGupta approved these changes

2019-06-10 06:19 UTC, invincibleJai approved these changes

2019-06-10 09:36 UTC, rohitkrai03 approved these changes
LGTM

2019-06-10 09:39 UTC, merged