add AddLabel option component
talamer/console pull request #125
Opened 2019-06-05 14:41 UTC by vikram-raj

Story - https://jira.coreos.com/browse/ODC-996

This change adds ```AddLabel``` pure component.

```Typescript
<AddLabel
  onLabelAdd={this.onLabelAdd} />
```

2019-06-05 16:49 UTC, rohitkrai03 requested changes

2019-06-05 16:49 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +interface DeploymentConfigProps {
```suggestion
interface AddLabelProps {
```

2019-06-05 17:01 UTC, christianvogt commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <EnvironmentPage
I'm confused. Why are you using the environments component for labels and not the `name-value-editor` ?

2019-06-05 17:01 UTC, christianvogt commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +import { EnvironmentPage } from './../../../../../public/components/environment';
Went up one dir too many. Do not include the `public` dir.

2019-06-05 17:01 UTC, christianvogt commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +interface DeploymentConfigProps {
I see no props for supplying the values back to the form component.
Or a way to notify removal of labels.

2019-06-06 01:58 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <EnvironmentPage
```EnviromentPage``` component is the wrapper of ```name-value-editor```. There is a ```addConfigMapSecret``` prop in this component for showing the add key-value pair the from the resource which I hide. So, that I can use it for key-value pair for adding the label, which needs only name and value.

2019-06-06 02:01 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +interface DeploymentConfigProps {
I will add this props.

2019-06-06 17:06 UTC, christianvogt commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <EnvironmentPage
It's odd because you're using a component dedicated to env vars and turned off all the visuals that make it no longer related to env.
IF there are changes to the env component that make sense for all env vars, we will inherit those here and break the UI. It makes the most sense to use the base component directly in this case.

2019-06-09 19:48 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +interface DeploymentConfigProps {
Added a prop to pass back the value to the component. https://github.com/talamer/console/pull/125/commits/256899cf74bdcbf233c237fc96db2ee02c288564

2019-06-09 19:49 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <EnvironmentPage
Done. https://github.com/talamer/console/pull/125/commits/256899cf74bdcbf233c237fc96db2ee02c288564 
Used ```name-value-editor``` component for add labels.

2019-06-09 19:50 UTC, vikram-raj commented
I make the changes. Please review it again. @christianvogt @rohitkrai03

2019-06-10 06:22 UTC, debsmita1 requested changes
Shouldn't this file be under shared/components ?

2019-06-10 06:49 UTC, debsmita1 submitted a review, later dismissed

2019-06-10 06:49 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <div>Each label is applied to each created resource.</div>
You can add `className="co-section-heading-tertiary"`

2019-06-10 08:16 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <div>Each label is applied to each created resource.</div>
It is not a header.

2019-06-10 08:19 UTC, vikram-raj commented
> Shouldn't this file be under shared/components ?

@debsmita1 yes, I will move it to shared components folder.

2019-06-10 09:32 UTC, rohitkrai03 approved these changes
LGTM

2019-06-10 09:48 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <div>Each label is applied to each created resource.</div>
@vikram-raj  I found this in Sunil's VD, the text is in bold.

![Labels](https://user-images.githubusercontent.com/22490998/59187277-bcc4a200-8b92-11e9-9e12-e4b3ccfece4c.png)

https://redhat.invisionapp.com/share/T9S7XCM64R7#/screens/365559441

2019-06-10 09:55 UTC, merged

2019-06-10 10:02 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/add-label/AddLabel.tsx
> +      <div>Each label is applied to each created resource.</div>
@debsmita1 This component will go inside `FormSection` component from my PR. It has a component for section heading `FormSectionHeading` that will handle it automatically.