Refactor Git Import to remove usage of CRD and introduce Formik based form framework
talamer/console pull request #128
Opened 2019-06-07 21:30 UTC by rohitkrai03

Related Stories - https://jira.coreos.com/browse/ODC-852 and https://jira.coreos.com/browse/ODC-670

This PR -
- Introduces `Formik` as a framework for building complex forms.
- Updates `React` to latest version to make use of hooks and latest version of `Formik`.
- Adds custom form field components like `InputField`, `DropdownField`, `NSDropdownField` which wraps `Formik` contexts. 
- Updates custom components like `BuilderImageSelector`, `BuilderImageTagSelector`, `ApplicationSelector` to work with `Formik` context using hooks.
- Adds form sections to divide the form into multiple sections.
- Adds `validation-utils` for validating each form fields separately.
- Adds `submit-utils` which adds functions to create resources. These functions are used to create all the resources when user submits the form.
- Removes old `GitImportForm` files.
- Renames and moves dropdown components. Old components are still there because some older forms use `AppNameSelector`.

Things left to do - 

- [ ] Add tests for all the utility functions.
- [ ] Iron out a few bugs in validation.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/formik/CustomFormikFields.tsx
> +export const InputField: React.FC<InputFieldProps> = ({ label, helpText, ...props }) => {
Make each of these separate component files.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/formik/CustomFormikFields.tsx
> +  dropDownClassName?: string;
Looks like this is only needed to make the dropdown full width using class `dropdown--full-width`.
Instead add the prop `fullWidth?: boolean` and remove the class prop

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/formik/CustomFormikFields.tsx
> +export interface InputFieldProps {
Common field types could go into a separate type file.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/GitImport.tsx
> +  const validate = (values: GitImportFormData) => {
No reason for static pure functions to be inside the component render closure. Move outside of component.
There are other functions like this. Do a sweep.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/GitImportForm.tsx
> +    <Form onReset={handleReset} onSubmit={handleSubmit} className="co-m-pane__body-group">
Remove `co-m-pane__body-group`
The form itself should not force padding around it. That should be left to the parent to control the layout of it's children.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/GitImportForm.tsx
> +import { GitImportFormProps } from './import-types';
Why is this an import and not co-located in this component? Who else will use this?

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/GitImport.tsx
> +    return _.pickBy(errors);
Is this necessary for formik?

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/SectionDivider.tsx
> +export const SectionDivider: React.FC = () => (
Nothing we can reuse already from console or PF?

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/app/AppSection.tsx
> +      <SectionHeading text="App" style={{ fontWeight: '500' }} />
having to set the `fontWeight` for each usage seems wrong. Create a `FormSectionHeading`.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/app/AppSection.tsx
> +        dropDownClassName="dropdown--full-width"
Change to `fullWidth`

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/app/AppSection.tsx
> +  project: ProjectData;
Why is this not just a single string value? Why an object?

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/app/ApplicationSelector.tsx
> +          menuClassName="dropdown-menu--text-wrap"
Why do you need `dropdown-menu--text-wrap` here? Should this not go to `ApplicationDropdown`?

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/app/ApplicationSelector.tsx
> +      <FormGroup controlId="app-selector-field" className={cx({ 'has-error': touched && error })}>
use prop `validationStatus` instead of applying `className` directly. See pf3 docs.
Do a sweep.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageSelector.scss
> +    font-size: 15px;
Should use PF variable.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageSelector.scss
> +    margin-left: 5px;
Should also probably be a patternfly variable for spacing.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageSelector.tsx
> +        <div id={"builder-image-selector-field"} className="odc-builder-image-selector">
```suggestion
        <div id="builder-image-selector-field" className="odc-builder-image-selector">
```

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageSelector.tsx
> +              key={`${image.name}-key`}
Not sure `-key` adds any value here as names should be unique no?
```suggestion
              key={image.name}
```

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageTagSelector.tsx
> +        <FormGroup className="co-m-pane__form">
Why are you using `co-m-pane__form` ? Shouldn't the parent form already take care of this?

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/builder/BuilderSection.tsx
> +        data-test-id="builder-image-selector"
This isn't being used. Remove.

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/GitImport.tsx
> +import { GitImportProps, GitImportFormData } from './import-types';
Why do you import `GitImportProps` and not co-locate in this file?

2019-06-07 22:27 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-validation-utils.ts
> +  const errors = {} as GitData;
```suggestion
  const errors: GitData = {};
```

2019-06-09 14:24 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/GitImport.tsx
> +    return _.pickBy(errors);
Yes, formik needs the `errors` object to contain only those keys which has an error. If a key has a empty value like `'', {}, null` it treats the form as dirty and disables submit.

2019-06-09 14:24 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/SectionDivider.tsx
> +export const SectionDivider: React.FC = () => (
I couldn't find anything like this in console.

2019-06-09 14:47 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/app/AppSection.tsx
> +  project: ProjectData;
Because later we would need to have create project form here and we'll be adding more properties to it like `displayName` and `description`.

2019-06-10 07:15 UTC, vikram-raj commented
build and deploy

2019-06-10 07:15 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit34.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-128-openshift-console.apps.rohit34.devcluster.openshift.com

2019-06-10 09:07 UTC, divyanshiGupta requested changes

2019-06-10 09:07 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/dropdown/ApplicationDropdown.tsx
> +const AppDropdown: React.FC<ApplicationDropdownProps> = (props) => {
I think this should also be `ApplicationDropdown` for consistency.

2019-06-10 09:07 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/formik-fields/field-types.ts
> +  selectedKey: string;
This should also be optional

2019-06-10 09:07 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/formik-fields/field-types.ts
> +  label: string;
Both name and label should be optional if all the other props are optional

2019-06-10 10:07 UTC, vikram-raj reviewed
32 tests are failing on this PR.

2019-06-10 10:07 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageSelector.tsx
> +
Organize imports absolute first, followed by relative, followed by scss.

2019-06-10 10:07 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageTagSelector.tsx
> +
Organize imports absolute first, followed by relative.

2019-06-10 10:07 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/import/git/GitSection.tsx
> +
Organize imports absolute first, followed by relative.

2019-06-10 10:07 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/import/section/FormSectionHeading.tsx
> +  <SectionHeading text={title} style={{ fontWeight: '500' }} />
Can we use patternfly variable here ```--pf-global--FontWeight--semi-bold```?

2019-06-10 10:07 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/formik-fields/field-utils.ts
> +  return state || null
semicolon missing. Run prettier on the PR.

2019-06-10 10:18 UTC, rohitkrai03 commented
@vikram-raj Tests are failing on `master-next` branch as well. Not sure why though.

2019-06-10 10:22 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/formik-fields/field-types.ts
> +  selectedKey: string;
Actually, no there should always be selectedKey prop. Without that the dropdown will not be controlled input.

2019-06-10 10:23 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/formik-fields/field-types.ts
> +  label: string;
Both `name` and `label` are required to build the input component. Without `name` the component would not be able to connect to the correct key in formik state.

2019-06-10 10:24 UTC, divyanshiGupta commented
@rohitkrai03 none of the test failed for me on lastest master-next.

2019-06-10 11:54 UTC, rohitkrai03 commented
@vikram-raj @divyanshiGupta Updated enzyme version which was causing the tests to fail.

2019-06-10 18:11 UTC, christianvogt commented on frontend/public/extend/devconsole/components/formik-fields/DropdownField.tsx
> +export const DropdownField: React.FC<DropdownFieldProps> = ({ label, helpText, ...props }) => {
We should have a single default export per component file.

2019-06-10 18:11 UTC, christianvogt commented on frontend/public/extend/devconsole/components/formik-fields/field-utils.ts
> +  return cx({
interesting use of classnames

2019-06-10 18:11 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageSelector.tsx
> +              key={`${image.name}`}
Did you mean to leave this as a template string? Or should it just be `key={image.name}` ?

2019-06-10 18:26 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/formik-fields/DropdownField.tsx
> +export const DropdownField: React.FC<DropdownFieldProps> = ({ label, helpText, ...props }) => {
Having named export here helps with having an index.ts file from where its easy to import any custom formik field.

2019-06-10 18:26 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/builder/BuilderImageSelector.tsx
> +              key={`${image.name}`}
Yes, i actually missed it. it should indeed be `key={image.name}`

2019-06-10 18:29 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/formik-fields/field-utils.ts
> +  return cx({
Yeah, this seemed like a good fit here. :)

2019-06-11 04:10 UTC, christianvogt approved these changes
Just a few comments and some imports to organize.

2019-06-11 04:10 UTC, christianvogt commented on frontend/public/extend/devconsole/components/formik-fields/InputField.tsx
> +      <ControlLabel className={cx({ 'co-required': props.required })}>{label}</ControlLabel>
Can we simplify this by creating a new `ControlLabel` that supports a required prop and applies this class?

2019-06-11 04:10 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/GitImportForm.tsx
> +      className="co-source-to-image-form__button-bar"
Magic classname?
Any alternative?
Why is this needed?

2019-06-11 04:10 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/GitImport.tsx
> +  activeNamespace: string;
no need to call this `activeNamespace`. Just `namespace` will do.

2019-06-11 07:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/GitImportForm.tsx
> +      className="co-source-to-image-form__button-bar"
It just adds some margin on top and bottom of the button bar.

2019-06-11 07:39 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/formik-fields/InputField.tsx
> +      <ControlLabel className={cx({ 'co-required': props.required })}>{label}</ControlLabel>
I think it doesn't make any significant difference in this case.

2019-06-11 07:39 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/GitImportForm.tsx
> +      className="co-source-to-image-form__button-bar"
Removed.

2019-06-11 07:39 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/GitImport.tsx
> +  activeNamespace: string;
Agreed. Done.

2019-06-11 09:46 UTC, divyanshiGupta approved these changes

2019-06-11 10:03 UTC, merged