feat(advanced-options): create pure component for resource limits
talamer/console pull request #129
Opened 2019-06-09 09:46 UTC by debsmita1

This PR includes:
- A pure component for Advanced Options: Resource Limits
- The Number Spinners displays an error when negative values are entered
- The Number Spinners displays an error when value of `Request` is greater than `Limit`

Refer Story: https://jira.coreos.com/browse/ODC-822

![2019-06-09-14_43_55 639960](https://user-images.githubusercontent.com/22490998/59157429-dc42c880-8ac7-11e9-86ca-bde90561d63d.gif)

2019-06-10 05:25 UTC, vikram-raj commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.scss
> +}
This custom CSS not required. You can use Patternfly grid or flex layout.

Grid - https://pf4.patternfly.org/layouts/Grid/examples/
Flex - https://www.patternfly.org/v4/documentation/core/layouts/flex

2019-06-10 06:31 UTC, invincibleJai commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +              // className="odc-resource-limits-dropdown"
can we remove comment

2019-06-10 06:31 UTC, invincibleJai commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const firstLabel = 'MiB';
not sure if name `firstLabel` makes sense or if we can have some meaningful name

2019-06-10 06:31 UTC, invincibleJai commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +    //millicores
comments may be removed

2019-06-10 06:31 UTC, invincibleJai commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +export const convertValueToBase = (value, unitLabel) => {
good to have type predefined for arguments

2019-06-10 08:50 UTC, divyanshiGupta requested changes

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +export const validateLimit = (min, max, unitOfMin, unitOfMax) => {
add types for arguments

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  if (isPositive(max) !== '') {
You can simply do this : `if (isPositive(max))  {return isPositive(max)}` .

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeCpuRequestData: React.ReactEventHandler<HTMLInputElement> = (event) => {
Add event type.

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeCpuLimitData: React.ReactEventHandler<HTMLInputElement> = (event) => {
Add event type.

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeMemoryRequestData: React.ReactEventHandler<HTMLInputElement> = (event) => {
Add event type.

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeMemoryLimitData: React.ReactEventHandler<HTMLInputElement> = (event) => {
Add event type.

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeCpuRequest = (operation) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onCpuRequestUnitChange = (val) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeCpuLimit = (operation) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onCpuLimitUnitChange = (val) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeMemoryRequest = (operation) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onMemoryRequestUnitChange = (val) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeMemoryLimit = (operation) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onMemoryLimitUnitChange = (val) => {
Add type

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +      <FormGroup controlId="cpu-request" className={cpuRequestError ? 'has-error' : ''}>
Do this `cpuRequestError && 'has-error'`

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +              // className="odc-resource-limits-dropdown"
remove this commented out code if not required anymore.

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +      <FormGroup controlId="cpu-limit" className={cpuLimitError ? 'has-error' : ''}>
`cpuLimitError && 'has-error'`

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +              // className="odc-resource-limits-dropdown"
remove this commented out code if not required anymore.

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +      <FormGroup controlId="memory-request" className={memoryRequestError ? 'has-error' : ''}>
memoryRequestError && 'has-error'

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +      <FormGroup controlId="memory-limit" className={memoryLimitError ? 'has-error' : ''}>
`memoryLimitError && 'has-error'`

2019-06-10 08:50 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +              // className="odc-resource-limits-dropdown"
remove this commented out code if not required anymore.

2019-06-10 10:03 UTC, rohitkrai03 commented
@debsmita1 Do we have a visual design document for this one? Because the designs look very different from 3.11 designs.

2019-06-10 10:08 UTC, debsmita1 commented
> @debsmita1 Do we have a visual design document for this one? Because the designs look very different from 3.11 designs.

Yes, Here it is : https://marvelapp.com/1fj5ej2g/screen/57669532

2019-06-10 11:40 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +              // className="odc-resource-limits-dropdown"
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:40 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +      <FormGroup controlId="memory-limit" className={memoryLimitError ? 'has-error' : ''}>
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:40 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +      <FormGroup controlId="memory-request" className={memoryRequestError ? 'has-error' : ''}>
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:41 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +              // className="odc-resource-limits-dropdown"
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:41 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +      <FormGroup controlId="cpu-limit" className={cpuLimitError ? 'has-error' : ''}>
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:41 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const onChangeMemoryRequestData: React.ReactEventHandler<HTMLInputElement> = (event) => {
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:41 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +              // className="odc-resource-limits-dropdown"
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:41 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  const firstLabel = 'MiB';
Changed it to `binaryUnitLabel` https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:42 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +export const convertValueToBase = (value, unitLabel) => {
Done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 11:42 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  if (isPositive(max) !== '') {
done https://github.com/talamer/console/commit/87e1b0b1a7200d6a3a9af5a9b922b02668b67249

2019-06-10 12:15 UTC, divyanshiGupta commented
> > @debsmita1 Do we have a visual design document for this one? Because the designs look very different from 3.11 designs.
> 
> Yes, Here it is : https://marvelapp.com/1fj5ej2g/screen/57669532

But in this design as well there is only one field and that is for memory, there are no fields for cpu. Why is that?

2019-06-10 12:19 UTC, debsmita1 commented
> > > @debsmita1 Do we have a visual design document for this one? Because the designs look very different from 3.11 designs.
> > 
> > 
> > Yes, Here it is : https://marvelapp.com/1fj5ej2g/screen/57669532
> 
> @debsmita1 But in this design as well there is only one field and that is for memory, there are no fields for cpu. Why is that?

@divyanshiGupta  It's because, UX has referred the starter cluster. I was asked to follow what is in 3.11 and this is how it is in 3.11
![3 11 ResourceLimits](https://user-images.githubusercontent.com/22490998/59194798-ca385700-8ba7-11e9-9a22-fdf30f9b6a67.png)
Just that I have replaced the input fields with `Number Spinner`s like how it is shown in the Visual Design

2019-06-10 12:25 UTC, divyanshiGupta commented
Its fine if you have confirmed this with UX.

2019-06-10 13:33 UTC, rohitkrai03 approved these changes
LGTM

2019-06-10 15:35 UTC, divyanshiGupta approved these changes

2019-06-10 15:39 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.scss
> +}
@vikram-raj Done. I found a common class `co-m-table-grid__body row` so used that https://github.com/talamer/console/commit/006e66f7b5371e6eae2d1a11a1c8312c3aa92b91

2019-06-11 06:37 UTC, invincibleJai approved these changes

2019-06-11 08:21 UTC, vikram-raj commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  return value >= 0 ? '' : 'Can\'t be negative.';
This ```isPositive``` function should return a boolean value. So that we can show the error message based on the field. 
eg. -  Request can't be negative or Limit can't cant be negative.

2019-06-11 08:29 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +  return value >= 0 ? '' : 'Can\'t be negative.';
@vikram-raj  In 3.11, when negative value is entered it just shows `Can't be negative`

2019-06-11 08:43 UTC, vikram-raj commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{memoryRequestError}</HelpBlock>
```suggestion
        {memoryRequestError && <HelpBlock>{memoryRequestError}</HelpBlock>}
```

2019-06-11 08:44 UTC, vikram-raj commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{memoryLimitError}</HelpBlock>
```suggestion
        {memoryLimitError && <HelpBlock>{memoryLimitError}</HelpBlock>}
```

2019-06-11 08:44 UTC, vikram-raj commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{cpuLimitError}</HelpBlock>
```suggestion
        {cpuLimitError && <HelpBlock>{cpuLimitError}</HelpBlock>}
```

2019-06-11 08:45 UTC, vikram-raj commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{cpuRequestError}</HelpBlock>
```suggestion
        {cpuRequestError && <HelpBlock>{cpuRequestError}</HelpBlock>}
```

2019-06-11 10:02 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{memoryRequestError}</HelpBlock>
Done

2019-06-11 10:03 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{memoryLimitError}</HelpBlock>
Done

2019-06-11 10:03 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{cpuLimitError}</HelpBlock>
Done

2019-06-11 10:03 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/advanced-options/ResourceLimits.tsx
> +        <HelpBlock>{cpuRequestError}</HelpBlock>
Done

2019-06-11 10:20 UTC, merged