Dev console merge with console/master
talamer/console pull request #140
Opened 2019-06-13 21:26 UTC by christianvogt

2019-06-14 01:44 UTC, vikram-raj commented
@christianvogt  I am getting this when I run this PR locally.
```
template: index.html:8:10: executing "index.html" at <.CustomProductName>: can't evaluate field CustomProductName in type *server.jsGlobals
```

And in terminal this
```
2019/06/14 07:10:56 http: multiple response.WriteHeader calls
```

2019-06-14 02:47 UTC, christianvogt commented
@vikram-raj console has changed a lot including the server. Make sure you rebuild using `./build.sh`

2019-06-14 03:14 UTC, vikram-raj commented
Application dropdown is not opening it is throwing an error

2019-06-14 03:33 UTC, vikram-raj commented
Do we need ```Import YAML``` action in the secondary navbar of DevConsole as we already have ```Import YAML``` option on add page?

2019-06-14 03:38 UTC, christianvogt commented
@vikram-raj 
1. App drop down opens for me. But it is showing the same app in all namespaces and I cannot select it.... I'll have to look into this and compare to our current fork.
2. Loads ok for me. But i can see the blank page for a little bit.
3. This is a react-router warning. I'll check if this is something that is happening because of my work or not. I know that the warning is false because it does support an array prop. Console tries to suppress the error with a hack in `app.jsx`
4. Odd it's set to `readOnly={false}`

The Import YAML button is in admin console and that is a shared component. @serenamarie125 What do you want to do about this button?

2019-06-14 05:25 UTC, sbose78 commented
build and deploy

2019-06-14 05:26 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit37.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-140-openshift-console.apps.rohit37.devcluster.openshift.com

2019-06-14 06:21 UTC, sahil143 reviewed
Base Circle Svg is not showing up on any of the nodes and Decorator. DropShadow filter is not showing on hover.
![Screenshot from 2019-06-14 11-33-22](https://user-images.githubusercontent.com/9278015/59486970-c43cc180-8e98-11e9-8c15-081da2b44945.png)
![Screenshot from 2019-06-14 11-33-06](https://user-images.githubusercontent.com/9278015/59486863-6f994680-8e98-11e9-91dd-df6095b5ee98.png)

Tooltips and application name don't have black background.
![Screenshot from 2019-06-14 11-22-54](https://user-images.githubusercontent.com/9278015/59487082-331a1a80-8e99-11e9-8451-1bb01508ed96.png)

By default, Topology is not selected on side bar.
![Screenshot from 2019-06-14 11-23-11](https://user-images.githubusercontent.com/9278015/59487217-91df9400-8e99-11e9-8300-30fa038238e6.png)

Selected Item doesn't have Blue Vertical line on the left side.
![Screenshot from 2019-06-14 11-23-36](https://user-images.githubusercontent.com/9278015/59487290-d79c5c80-8e99-11e9-8a51-f2ccd9f48d05.png)

2019-06-14 06:40 UTC, sahil143 commented
Clicking on Filter by Application Dropdown on Topology page throws an error
```
Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    in a (created by DropDownRow)
    in li (created by DropDownRow)
    in DropDownRow (created by Dropdown)
    in ul (created by Dropdown)
    in div (created by Dropdown)
    in div (created by Dropdown)
    in Dropdown (created by ResourceDropdown)
    in ResourceDropdown (created by ApplicationDropdown)
```
Also, I'm not getting the dropdown to select the `part-of` application while creating S2I app from Browse Catalog instead there is an input field to enter the labels.

2019-06-14 08:17 UTC, divyanshiGupta reviewed
![nav-bug](https://user-images.githubusercontent.com/20724543/59494049-f6a2ea80-8ea9-11e9-9c10-2056be17bfbb.gif)
So when I click on `projects` I can see the list of all projects then I click on `status` and I see the status page, but `projects` remains selected and on clicking outside `status` gets deselected but `projects` remain selected even though we are on the `status` page

Is this bug known or it is in this PR or something has changed in console?

Also, it used to show `overview` in the URL and not `projects` previously, and it is also getting redirected to `workloads`.

2019-06-14 08:26 UTC, rohitkrai03 requested changes

2019-06-14 08:26 UTC, rohitkrai03 commented on frontend/packages/dev-console/src/plugin.tsx
> +    type: 'NavItem/Href',
I think we don't need `Status` nav item anymore because console moved this page into projects details page as workloads section.

2019-06-14 09:53 UTC, rohitkrai03 commented
@christianvogt I found a fix for the environment fields being readonly. It was because `environment.jsx` implementation changed a bit. I'll raise a PR to your branch.

2019-06-14 10:46 UTC, rohitkrai03 commented
@christianvogt Raised a PR on your branch for some of the fixes - https://github.com/christianvogt/console/pull/1

2019-06-14 14:51 UTC, debsmita1 commented
> @christianvogt I am getting this when I run this PR locally.
> 
> ```
> template: index.html:8:10: executing "index.html" at <.CustomProductName>: can't evaluate field CustomProductName in type *server.jsGlobals
> ```
> 
> And in terminal this
> 
> ```
> 2019/06/14 07:10:56 http: multiple response.WriteHeader calls
> ```

@christianvogt I am getting this error. Tried to follow what you suggested to Vikram, but in vain

2019-06-14 18:13 UTC, christianvogt commented on frontend/packages/dev-console/src/plugin.tsx
> +    type: 'NavItem/Href',
Removed

2019-06-15 12:54 UTC, karthikjeeyar commented on frontend/packages/dev-console/yamls/pipelines/pipeline.yaml
> +      name: openshift-cli-deploy-mapit
```suggestion
      name: openshift-cli
```

2020-08-20 16:31 UTC, closed without merging