integrate routing advanced option in git import flow
talamer/console pull request #141
Opened 2019-06-14 19:08 UTC by divyanshiGupta

Story: https://jira.coreos.com/browse/ODC-1020

![routes](https://user-images.githubusercontent.com/20724543/59532281-e1f44000-8f05-11e9-86d9-ba44b4c16eab.gif)

2019-06-14 19:11 UTC, divyanshiGupta commented
@christianvogt I know you asked us not to raise any PRs, but I just got finished with the work and thought that it will be a good idea to get the PR reviewed. I will raise a new PR on openshift console repo once we are merged.

2019-06-14 19:46 UTC, rohitkrai03 requested changes

2019-06-14 19:46 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/formik-fields/field-types.ts
> +  emptyStateMsg?: string;
Why do we need this?

2019-06-14 19:46 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/__tests__/import-validation-utils.spec.ts
> +      const mockData = cloneDeep(mockFormData);
Thanks for doing this. I was meaning to do it but missed it in the last PR.

2019-06-14 19:46 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/GitImportForm.tsx
> +        <RouteSection create={values.route.create} />
Better to send `route` as prop here. Create doesn't give full context.

2019-06-14 19:46 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/route/CreateRouteForm.tsx
> +/* eslint-disable no-unused-vars, no-undef */
Maybe just rename it to `CreateRoute.tsx`

2019-06-14 19:46 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/route/CreateRouteForm.tsx
> +          selectedKey=""
```suggestion
          selectedKey={targetPort}
```

2019-06-14 19:47 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/formik-fields/field-types.ts
> +  emptyStateMsg?: string;
Forgot to remove this. :P

2019-06-14 19:48 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/__tests__/import-validation-utils.spec.ts
> +      const mockData = cloneDeep(mockFormData);
You are welcome :)

2019-06-14 19:49 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/route/CreateRouteForm.tsx
> +          selectedKey=""
Missed it. Thanks

2019-06-14 20:02 UTC, rohitkrai03 commented
@divyanshiGupta Can you also add `validateForm(newValues)` to `GitSection.handleGitUrlBlur()` and `BuilderImageSelecter.handleImageChange()`? I see some flickers of validation error messages sometimes. After downgrading to rc-1 i thought we won't need that part but we need it after all.

2019-06-14 20:04 UTC, divyanshiGupta commented
> @divyanshiGupta Can you also add `validateForm(newValues)` to `GitSection.handleGitUrlBlur()` and `BuilderImageSelecter.handleImageChange()`? I see some flickers of validation error messages sometimes. After downgrading to rc-1 i thought we won't need that part but we need it after all.

Done @rohitkrai03

2019-06-14 20:07 UTC, rohitkrai03 approved these changes
LGTM

2019-06-15 04:30 UTC, sbose78 commented
build and deploy

2019-06-15 04:30 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.rohit37.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-141-openshift-console.apps.rohit37.devcluster.openshift.com

2019-06-17 16:45 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/route/CreateRoute.tsx
> +    <React.Fragment>
Remove `React.Fragment`

2019-06-17 16:45 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/route/SecureRoute.tsx
> +        <div className="co-create-route__security">
Why is this here? What styles does it add as I cannot find any reference.
If not needed, please remove.

2019-06-17 16:45 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-validation-utils.ts
> +      .max(253, 'Can\'t be longer than 253 characters.'),
For consistency with required message.
```suggestion
      .max(253, 'Cannot be longer than 253 characters.'),
```

2019-06-17 16:45 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-validation-utils.ts
> +      .matches(pathRegex, { message: 'Path must start with /', excludeEmptyString: true }),
Could you make every message consistent and add a period to the end.

2019-06-17 21:04 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/route/SecureRoute.tsx
> +        <div className="co-create-route__security">
This was being used in console `create-route` but we don't need it anymore. Forgot to remove this.

2019-06-17 21:07 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/import-validation-utils.ts
> +      .matches(pathRegex, { message: 'Path must start with /', excludeEmptyString: true }),
Done

2019-06-17 21:08 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/import-validation-utils.ts
> +      .max(253, 'Can\'t be longer than 253 characters.'),
Done

2019-06-17 21:08 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/route/CreateRoute.tsx
> +    <React.Fragment>
Done

2019-06-21 20:05 UTC, closed without merging