Add context for active perspective in the redux store and launch into last viewed perspective
talamer/console pull request #20
Opened 2019-03-26 09:24 UTC by rohitkrai03

Related to https://jira.coreos.com/browse/ODC-149.

This PR -
- Adds a context variable `activePerspective` in the redux store under `UI` state.
- If the path has a segment in it which is legal perspective name, the state gets updated when location changes.
- When a user uses perspective switcher to switch from on perspective to another, the state changes as well as last viewed perspective gets saved into local storage.
- When the user comes back to the application at root path `/`, the app redirects to last viewed perspective.
- Also, updated `PerspectiveSwitcher` and `Nav` to use `activePerspective` instead of location to determine the perspective.
- Updated routes and names according to change to Dev Console.

2019-03-28 19:41 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +  onChangePerspective: (string) => void;
`onChangePerspective` => `onPerspectiveChange`
`onPerspectiveChange(string): void`;

2019-03-28 19:41 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +            isActive={() => props.activePerspective === 'admin'}
Why is this a function? Shouldn't this be `props.activePerspective === 'admin'`?

2019-03-28 19:41 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +              alt="Admin Console"
I'm not sure an alt attribute here adds much value. IMO either make alt value equal `""` or have it equal to `Administrator`.

2019-03-28 19:41 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +              alt="Dev Console"
I'm not sure an alt attribute here adds much value. IMO either make alt value equal `""` or have it equal to `Developer`.

2019-03-29 04:33 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +            isActive={() => props.activePerspective === 'admin'}
Actually no. The prop type for this is defined as a function.

`isActive?<P>(match: match<P>, location: H.Location): boolean;`

2019-04-01 20:45 UTC, christianvogt requested changes

2019-04-01 20:45 UTC, christianvogt commented on frontend/public/components/masthead.jsx
> +export const Masthead = ({ activePerspective, onNavToggle }) => {
Instead of passing in the `activePerspective`, pass in the an `href`. That way the masthead doesn't need to have knowledge of what are perspectives.
Don't forget to update the `propTypes`.

2019-04-01 20:45 UTC, christianvogt commented on frontend/public/components/app.jsx
> +  const lastViewedPerspective = localStorage.getItem(LAST_PERSPECTIVE_LOCAL_STORAGE_KEY);
Can't you get the value from the redux store? Isn't this the `activePerspective`?

2019-04-01 20:45 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +    activePerspective: state.UI.get('activePerspective'),
Typically you should use a selector function to retrieve values from state so that the state value location is hidden from the consumer.

2019-04-01 20:45 UTC, christianvogt commented on frontend/public/ui/ui-actions.js
> +export const getActivePerspective = () => store.getState().UI.get('activePerspective');
As we already discussed, the usage of store as a static entity is bad.
You should create a proper selector for usage in the rest of the code and use `connect` to pull the value from the state. This will be one less thing to refactor when we fix their misuse of the store.

2019-04-01 20:45 UTC, christianvogt commented on frontend/public/ui/ui-actions.js
> +    if (perspective !== getActivePerspective()) {
You don't really need to perform this check. So what if we set the same value in localStorage.
If you fix the `getActivePerspective` to be a proper selector, you won't be able to perform this check without it being a thunk.

2019-04-01 20:45 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +        onChangePerspective={() => {}}
`onChangePerspective` => `onPerspectiveChange`

2019-04-01 20:45 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/PerspectiveSwitcher.spec.tsx
> +        onChangePerspective={() => {}}
`onChangePerspective` => `onPerspectiveChange`

2019-04-02 21:30 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +  const lastViewedPerspective = localStorage.getItem(LAST_PERSPECTIVE_LOCAL_STORAGE_KEY);
No, this is actually for the redirect to last viewed perspective when user hit `/`. So, it takes value from local storage.

2019-04-03 20:56 UTC, christianvogt approved these changes

2019-04-03 20:57 UTC, merged