[WIP]Created mega-menu nav comp and added it in persepective switcher comp
talamer/console pull request #22
Opened 2019-04-01 13:54 UTC by divyanshiGupta

Tasks implemented : 

- https://jira.coreos.com/browse/ODC-221
- https://jira.coreos.com/browse/ODC-224

![mega-menu](https://user-images.githubusercontent.com/20724543/55332571-49782300-54b3-11e9-94df-f4061cd5f1b6.gif)

To Do -
- [ ] Use React Icons in MegaMenu
- [ ] Change the page layout
- [ ] Make MegaMenu Responsive

2019-04-02 12:14 UTC, divyanshiGupta commented
@christianvogt @rohitkrai03 can you guys review and merge this PR so that @debsmita1 and @karthikjeeyar can add there changes on top of my changes as they both need to add code in Perspective Switcher. I am working on new Page component and I can raise a separate PR for that and if anything else needs to be changed I can add it in the Page component PR.

2019-04-02 18:50 UTC, christianvogt requested changes
Please run the linter and fix all errors.
Can we not do the Page changes here now?
We should be referencing patternfly variables for sizing and colors.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.tsx
> +  className?: string,
This prop isn't used and we should not accept `className` in as a prop.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.tsx
> +import './MegaMenu.scss';
Separate scss per component. Should be `MegaMenuItem.scss`.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.tsx
> +  onClick?: (MouseEvent) => void,
Remove this? All links are routes. Either internal or external.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuNav.tsx
> +      aria-label="Mega Menu Nav"
Need a better name for this. Contact Serena. For example google's nav is called 'Google apps'.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.tsx
> +import './MegaMenu.scss';
`MegaMenuSection.scss`

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.tsx
> +  children: any
`any` => `ReactNode`

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +import MegaMenu from '../../shared/components/MegaMenu/MegaMenu';
Bad path.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.tsx
> +        {props.externalLink ? <i className="fa fa-external-link odc-mega-menu__external-link"></i> : ""}
We talked about using a flex layout for this.
Or if not, this should be the second element inside `NavLink` (before the text) so that it's float position takes precedence over the text and therefore the external link icon will not wrap.
Also, you should use patternfly react-icons.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.tsx
> +          className="odc-mega-menu__item-icon"/>
`odc-mega-menu-item__icon`

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.tsx
> +    <NavItem className="odc-mega-menu__item">
`odc-mega-menu-item`

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.tsx
> +      className={props.isNavOpen ? "odc-mega-menu__expanded" : "odc-mega-menu__collapsed"}>
The current positioning is just temporary until the new layout is complete?
`odc-mega-menu` and `.is-open`
Then you create a css rule for `odc-mega-menu.is-open`.
No collapsed state as that's the default state.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.tsx
> +      className="odc-mega-menu__group-separator">
`odc-mega-menu-section`

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +        <MegaMenuSection title="Example">
Remove this `title`.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +          <MegaMenuItem to="/k8s/cluster/projects" title="Admin Console" icon={openshiftIconImg}/>
Title should be `Administrator`.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +          <MegaMenuItem to="/devops" title="Dev Console" icon={openshiftIconImg}/>
Title should be `Developer`.
Move to end of list.

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +  &__group-separator {
Is this still required now that we updated patternfly?

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +    transition: left 500ms linear;
Two different transition times?

2019-04-02 18:50 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +  &__expanded {
Set a bunch of default values on the `odc-mega-menu` class itself and then override those in the `is-open` state.

2019-04-03 11:55 UTC, divyanshiGupta commented
@christianvogt I have added the new page-layout. Few css changes and using react icons are left I am working on that.

2019-04-04 11:50 UTC, rohitkrai03 requested changes

2019-04-04 11:50 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/ConsolePage.tsx
> +              {props.megaMenu}
Extra space here. Run prettier.

2019-04-04 11:50 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +    transition: left 500ms linear;
Use 300ms with ease-in-out

2019-04-04 11:50 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.scss
> +    margin-left: 125px;
`margin-left: auto` to push it to the right automatically.

2019-04-04 11:50 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/ConsolePage.tsx
> +  megaMenu: React.ReactNode,
Maybe make the `megaMenu` props optional?

2019-04-04 11:50 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.scss
> +  position: absolute;
Spacing issue.

2019-04-04 12:02 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +  &__group-separator {
Yes because patternfly has a separator only for links and not for groups. Better to use our own

2019-04-04 12:04 UTC, rohitkrai03 approved these changes
LGTM

2019-04-04 17:07 UTC, christianvogt requested changes
Install prettier in your IDE and use it for formatting.
Run the linter and fix any errors.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/ConsolePage.scss
> +.console-page{
Rename class to `odc-console-page`
We might want to move it directly into the console itself but for now this is ok.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +  width: 25%;
Replace `width: 25%` with:

```
width: 290px;
max-width: 80%;
```

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +  left: -100%;
Transition on `transform` instead of `left` it is light weight in comparison.
```
left: 0;
transform: translateX(-100%);
transition: transform .3s ease-in-out;
```
Then change the transform on open:
```
  &.is-open {
    transform: translateX(0);
  }
```

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/ConsolePage.scss
> +}
Missing new line.  Does the linter not do error on this?

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.tsx
> +    {props.isNavOpen ? <div className="odc-ps__backdrop" /> : ''}
Use PF4 `Backdrop`:
`{props.isNavOpen && <Backdrop style={{ position: 'absolute' }} />}`

`Backdrop` should be the first element in the fragment.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.scss
> +}
Missing new line.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.scss
> +}
Missing new line.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.scss
> +    border-bottom-color: lightgrey;
This should be a PF4 color: `var(--pf-global--BorderColor--light)`

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.scss
> +    padding-bottom: 10px;
This should be a patternfly spacing variable.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.scss
>  }
Missing new line.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.scss
> +.odc-ps{
For future reference use the full name. eg. `odc-perspective-switcher`
Yes it's long, but consistent with the name of the component it styles.

You do not need this `scss` file if you use the PF4 `Backdrop` component.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.tsx
> +      {props.externalLink ? <i className="fa fa-external-link odc-mega-menu-item__external-link"></i> : ''}
Use patternfly react icon instead if there is an equivalent icon.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
>  import * as React from 'react';
Organize your imports with absolute imports first, followed by relative imports, followed by `scss` imports.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuNav.tsx
> +  onToggle?: () => void;
We aren't using `onToggle` at all. You can remove this.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuNav.tsx
> +    aria-label="Mega Menu Nav"
Need to have a different label here that makes sense to a user. Call it `Applications`; got an OK from UX.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuNav.tsx
> +interface MegaMenuNavProps {
`export` the component props.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuItem.tsx
> +interface MegaMenuItemProps {
`export` the component props.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.tsx
> +interface MegaMenuProps {
`export` the component props.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/ConsolePage.tsx
> +interface ConsolePageProps {
`export` the component props.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/components/app.jsx
> +import ConsolePage from '../extend/devconsole/shared/components/ConsolePage';
Move above the `scss` imports.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +.odc-mega-menu {
This needs to have `overflow-y: auto`.

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +  z-index: 200;
Align with PF4 `Backdrop`: `z-index: var(--pf-global--ZIndex--2xl);`

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +  background: white;
Use PF4 colors: `background-color: var(--pf-global--BackgroundColor--light-100)`

2019-04-04 17:07 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.tsx
> +    className="odc-mega-menu-section__separator">
I thought you get separators with the updated PF4 version?

2019-04-04 17:18 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/ConsolePage.scss
> +.console-page{
> Rename class to `odc-console-page`

I think it should be `openshift-console-page` and not `odc-console-page` because the page layout is being used for both the consoles. 

> We might want to move it directly into the console itself but for now this is ok.

I was not sure where to put this in console itself.

2019-04-04 17:20 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/ConsolePage.scss
> +}
I ran the linter and fixed errors but I dont know how this slipped away.

2019-04-04 17:22 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.tsx
> +    className="odc-mega-menu-section__separator">
Patternfly has a separator only for links and not for groups. Better to use our own.

2019-04-04 18:12 UTC, divyanshiGupta commented
> Install prettier in your IDE and use it for formatting.
> Run the linter and fix any errors.

Done.

2019-04-04 19:19 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/ConsolePage.scss
> +.console-page{
Anything in our folder we will use `odc` just for consistency and simplicity right now. If we move the file later, we can update the prefix accordingly.

2019-04-04 19:46 UTC, christianvogt requested changes
And... unit tests... :)

2019-04-04 19:46 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +.backdrop {
This is too generic of a name and doesn't follow the naming rules. You know there's nothing wrong with applying styles directly to an element :)
That way you also don't need to use `!important` either.

2019-04-04 19:46 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/ConsolePage.tsx
> +    <div className="pf-c-page">
I feel like we should be using `@patternfly/react-styles` for all css if we want to do things correctly. But that requires an extra built step. And since this works, take this only as an FYI. I'll have to ping the PF team about it.

2019-04-05 08:12 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +.backdrop {
I know we can use styles directly, but sometime back I was told not to use styles directly, everything should be a css class. I will change it.

2019-04-05 13:48 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenu.scss
> +.backdrop {
A reason why you don't want to use inline styles is when you are working on a library or component wherein overriding styles from the parent is expected. In our case we are not creating a component for re-use. Nor do we expect a parent to override the style. Therefore an inline style is perfectly acceptable.

2019-04-05 21:53 UTC, christianvogt commented on frontend/public/components/app.jsx
>            sidebar={this._sidebarNav()}
Found a bug in the layout when visiting the developer catalog.
Try this instead:
```
<div style={{ display: 'flex' }}>{props.sidebar}</div>
```

2019-04-05 22:19 UTC, christianvogt commented
@divyanshiGupta can you fix this error that appears in the console:
```
Warning: Failed prop type: The prop `title` is marked as required in `NavGroup`, but its value is `undefined`.
    in NavGroup (created by MegaMenuSection)
    in MegaMenuSection (created by PerspectiveSwitcher)
```

2019-04-06 12:26 UTC, divyanshiGupta commented
> @divyanshiGupta can you fix this error that appears in the console:
> 
> ```
> Warning: Failed prop type: The prop `title` is marked as required in `NavGroup`, but its value is `undefined`.
>     in NavGroup (created by MegaMenuSection)
>     in MegaMenuSection (created by PerspectiveSwitcher)
> ```

Fixed

2019-04-06 12:27 UTC, divyanshiGupta commented
@christianvogt I have added the unit tests.

2019-04-06 15:05 UTC, christianvogt reviewed
Great job. Only minor comments.

2019-04-06 15:05 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/MegaMenu/MegaMenuSection.tsx
> +  <NavGroup title={props.title ? props.title : ''} className="odc-mega-menu-section__separator">
Can simplify to `props.title || ''`

2019-04-06 15:05 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +export interface StateProps {
The state and dispatch props are considered an internal implementation to the component and don't need to be exported. We only should export the props of the main component that is exported.

2019-04-06 15:05 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/MegaMenu.spec.tsx
> +  let menuWrapper: ShallowWrapper<any> = null;
Move as a const in each test function. That way you also do not need to supply the type as it will be inferred.

Check all test files.

2019-04-06 15:05 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/MegaMenu.spec.tsx
> +import { Backdrop } from '@patternfly/react-core';
Organize absolute imports before relative.

This will be easier once we get proper limiting in hopefully next sprint.

Check all test files.

2019-04-07 16:09 UTC, christianvogt approved these changes

2019-04-07 19:37 UTC, divyanshiGupta commented
@debsmita1 @christianvogt I am getting this error while running the latest code from this PR - 
```
ERROR in /home/divgupta/go/src/github.com/openshift/console/frontend/public/extend/devconsole/shared/components/__tests__/MegaMenu.spec.tsx(58,21):
TS2304: Cannot find name 'jest'.

```

2019-04-07 20:05 UTC, christianvogt commented
@divyanshiGupta include the `tsconfig` and `package.json` fixes for the jest error.

2019-04-07 20:56 UTC, christianvogt commented on frontend/package.json
> +    "@types/jest": "^24.0.11",
`@types/jest` version should match the version of `jest`

2019-04-07 20:56 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/MegaMenu.spec.tsx
> +    map['click']({ target: ReactDOM.findDOMNode(menuWrapper.find('.test-class').instance()) });
We can remove the use of `findDOMNode`.

2019-04-07 20:56 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/__tests__/MegaMenu.spec.tsx
> +    map['click']({ target: ReactDOM.findDOMNode(menuWrapper.find('.odc-mega-menu').instance()) });
We can remove the use of `findDOMNode`.

2019-04-07 21:04 UTC, divyanshiGupta commented
@debsmita there were a lot of lint errors in your PR please run `yarn lint` everytime you push code.

2019-04-08 07:01 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/__tests__/MegaMenu.spec.tsx
> +    map['click']({ target: ReactDOM.findDOMNode(menuWrapper.find('.odc-mega-menu').instance()) });
Done https://github.com/divyanshiGupta/console/pull/2

2019-04-08 07:02 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/__tests__/MegaMenu.spec.tsx
> +    map['click']({ target: ReactDOM.findDOMNode(menuWrapper.find('.test-class').instance()) });
Done https://github.com/divyanshiGupta/console/pull/2

2019-04-08 07:44 UTC, merged