Import flow
talamer/console pull request #25
Opened 2019-04-02 05:53 UTC by vikram-raj

2019-04-07 04:36 UTC, christianvogt requested changes
Run prettier on all your files in the `devconsole` folder.
Run the linter.
Follow file naming conventions in `devconsole` folder when naming component classes. Uppercase first letter and camel casing to match the name of the component default export.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Import.tsx
> +    </Firehose>
You should have another component that encapsulates this `Firehose` and `ImportFlow` together.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/components/namespace.jsx
> +    this.setState({isOpen: !isOpen});
When setting the state based on the existing state value, always use the function parameter form of the `setState` function:
```
this.setState(({isOpen}) => ({isOpen: !isOpen}));
```

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/components/namespace.jsx
> +      isOpen: false,
`isOpen` is too generic. What is open? Make it more specific.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/components/namespace.jsx
> +        isOpen={this.state.isOpen} closeModal={this.importOverlay} />
I'm really not sure if this is the best approach to showing the modal. But I know that the new designs are moving away from this dropdown so I'm not too concerned at this time.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/import.scss
> +}
Follow css naming conventions. Use prefix `odc-`. Name the rule to match the component name. Any element inside the component should use the notation `__element-name`.

Also use patternfly variables for sizing. IIRC patternfly does spacing in increments of `8px`.
Probably do not need the margin if you're using `PageSection` from patternfly.

Why are you constraining the width to `700px`?

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/preview-import/preview-import.scss
> +}
Follow css naming conventions. Use prefix odc-. Name the rule to match the component name. Any element inside the component should use the notation __element-name.

Also use patternfly variables for sizing. IIRC patternfly does spacing in increments of 8px.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +}
Missing `DispatchProps` for correct typing.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +class ImportFlow extends React.Component<any, any> {
Do not use `any` type. Use proper typings.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +import { connect } from 'react-redux';
Organize imports absolute first, followed by relative, followed by scss.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow-catalog.tsx
> +export const ImportFlowCatalog: React.SFC<any> = props => {
Do not use `any` typing. Use proper types.
We prefer default exports for react component files to ensure we stick to a single exported component per file.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow-catalog.tsx
> +      <div className="import__filter">
Where are these classes defined?

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +    return (
Deconstruct upfront all props and state that will be used in the render function.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +        </div>
Remove the wrapping `<div>`

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/preview-import/preview-import.tsx
> +import { NamespaceModel } from './../../../../../public/models';
Organize imports absolute first, followed by relative, followed by scss.
Also fix your relative paths to the shortest possible path.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/preview-import/preview-import.tsx
> +  }
This should be a `FunctionalComponent` since there's no state. Also missing typings. Do not use `any`.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/preview-import/preview-import.tsx
> +      </ModelessOverlay>
As much as I dislike their approach right now, OpenShift console has a way of doing modals using `createModalLauncher` from `factory/modal`.
Have a look.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/preview-import/preview-import.tsx
> +            </Firehose>
You should have another component that encapsulates this `Firehose` and `ImportFlow` together. Or just put the `Firehose` in the `ImportFlow`.

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +  }
If you separated out this component into two, one for managing state and another for rendering, you'll have an easier time testing the two components. It would also align better with the redux approach and would later allow you to more easily switch state management from local state to redux or something else.
`ImportFlow` and `ImportForm`

2019-04-07 04:36 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +} from '@patternfly/react-core';
I think for consistency we need to stick to the PF3 react components. Those would align with the mock ups creates by UX.

2019-04-08 11:21 UTC, vikram-raj commented on frontend/public/extend/devconsole/pages/import.scss
> +}
I tried ```PageSection``` from Patternfly but it doesn't add any space from the top.

I fix max-width to 700px so, that I can align the form to the center of the page. I will change it once we have the final UX design.

2019-04-08 11:27 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/preview-import/preview-import.tsx
> +            </Firehose>
I separated the import-flow component into two. And put the ```Firehose``` at one place in ```importFlow``` component.

2019-04-08 11:32 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +} from '@patternfly/react-core';
```FormSelect```, ```FormSelectOption```, ```FormAction```, ```TextInput``` these component are not present in PF3 react component.

2019-04-08 14:40 UTC, sahil143 commented on frontend/public/components/namespace.jsx
> +  importOverlay() {
shouldn't `property intializer syntax` also used here ? `importOverlay = () => { }`

2019-04-08 15:00 UTC, sahil143 commented on frontend/public/extend/devconsole/pages/Import.tsx
>  const ImportPage: React.SFC = () => (
Please change the type `SFC` to `FunctionComponent`?

2019-04-08 15:00 UTC, sahil143 commented on frontend/public/extend/devconsole/pages/Home.tsx
>  const HomePage: React.SFC = () => {
Please change the type SFC to FunctionComponent? Because SFC is deprecated.

2019-04-08 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +} from '@patternfly/react-core';
[PF3 vertical form example](http://patternfly-react.surge.sh/patternfly-3/index.html?knob-Title=Kebab%20title&knob-Show%20Modal=true&knob-Close%20Popover=true&knob-Show%20Help=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Leeway=2&knob-Max%20Shown=5&selectedKind=patternfly-react%2FForms%20and%20Controls%2FForms%2FForm%20Examples&selectedStory=Vertical%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

For the select, you can use `components/utils/dropdown` from console, or PF3 typeahead select, or PF3 Dropdown. Probably the console dropdown is your best choice to align with the rest of the console.

2019-04-09 03:23 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +} from '@patternfly/react-core';
I replace the form with PF3 for. and Also added typeahead dropdown to application name dropdown.

2019-04-11 01:34 UTC, christianvogt commented
@vikram-raj the `+ Add` menu is going away entirely. It'll be replaced with the `+ Add` main nav item and a landing page. So please remove your changes to the project bar.

2019-04-11 02:35 UTC, vikram-raj commented
@christianvogt ```+ Add``` option from main nav will open the entire page. If we remove the ```+ add``` from the project bar then from where import flow slider will open.

2019-04-11 02:39 UTC, christianvogt commented
`+ Add` will open a landing page with all the same options as those that appear in the dropdown menu today but will be a tile selector.

2019-04-11 02:58 UTC, vikram-raj commented
So, when we need the import flow that will slide in from the left?

2019-04-11 03:18 UTC, christianvogt commented
Right now the only import flow that is has discussed is via the topology empty state and from the `+ Add` main navigation item. Both result in the same landing page content and both open import flow in main content area.

There may be future flows in a panel. But the drop-down menu that you've modified is going away.

2019-04-11 03:36 UTC, vikram-raj commented
Got it. Thanks

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +  return state;
Never pass in the entire state otherwise your component re-renders on every state change that may not even be relevant to your component.

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +      <div className="odc-import-flow-form">
The form itself shouldn't assign padding. Let the parent who consumes the form own the padding.

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +        </p>
Same comment about the info text. It probably shouldn't be in the form itself. Try to make components that are very focused and reusable.

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +      gitTypeField = null;
This else is unnecessary.

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Import.tsx
> +  </div>
Update this page to follow the standard page layouts. See other `*-page.tsx` files.

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Home.tsx
>  };
Home page is now gone. 
Add a new route for your import flow.

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/components/overlay-import-flow/OverlayImportFlow.tsx
> +
You won't need this modal anymore with the full page view.

2019-04-11 16:03 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +}
Can we get a better description of the prop types instead of using `any`

2019-04-12 17:12 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +              onBlur={this.validateGitRepo}
Validate the git url against the regex `onChange`.
Validation via the CR will happen on blur.

2019-04-12 17:12 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/import-flow.tsx
> +      </p>
I think that should be part of the page consuming the flow.
There shouldn't be any padding around this component. Leave that to the parent.

2019-04-12 17:12 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +      </div>
No need for this outter `div`.

2019-04-12 17:12 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    }
Since `setState` is async. It's best to only have a single call to `setState` to ensure it's clear that no part of the flow is consuming state and expecting a new state value.
Cleaner to assign two variables `gitType` and `gitTypeDetected`. And then call `setState` once.
Or better yet, have the `detectGitType` as a static function that simply returns the git type detected, then set the state with this value in `validateGitRepo`.

2019-04-15 19:56 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    history.back();
import `history` from `frontend/public/components/utils/router.ts`
Then use `history.goBack()`

2019-04-15 19:56 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/import.scss
> +}
Damn console overrides the patternfly styles :(

2019-04-21 03:42 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +            data-test-id="import-application-name" />
Can you use `NsDropdown` from `utils`?
Also the label isn't `Application Name`. It should be `Namespace`.

2019-04-22 06:54 UTC, vikram-raj commented
@christianvogt I added @debsmita1 changes to this PR as well. Please have a look.

2019-04-22 13:38 UTC, divyanshiGupta requested changes

2019-04-22 13:38 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/k8s/ns/:ns/add',
Shouldnt we create a separate nav-item for import and a separate route? Add is supposed to show only the empty state at all times with the `+add` actions.

2019-04-23 05:06 UTC, vikram-raj commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/k8s/ns/:ns/add',
Yes, I will add a separate route for import.

2019-04-23 20:52 UTC, sbose78 commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    '': 'Please choose builder image',
Ideally you should be fetching this list from the equivalent of `oc get imagestreams -n openshift`

2019-04-24 14:15 UTC, christianvogt submitted a review, later dismissed
Also, update your file names for components to use PascalCase.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/models/index.ts
> +
We should probably put these models in our folder for now.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Import.tsx
> +      </p>
Remove any temp text for now so when we merge we don't have this in any demos.

Console uses the `PageHeading` component. Follow what the rest of the pages do.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/__tests__/ImportFlowForm.spec.tsx
> +    importFlowForm.find('input[data-test-id="import-name"]').simulate('change', {
You should only need the test id as part of your query. No need for the tag to also be in the selector.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +          this.setState({ gitType: '' });
Call `setState` only once.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    timeOut = setTimeout(() => {
Timeout must be saved as an instance variable. It should also be cleared on `componentWillUnmount`
Is this even necessary? It's just doing regex comparison we can do `onChange` fast enough.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    this.randomString = this._generateRandomString();
Move random string initialization to the declaration itself.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    const activeNamespace = getActiveNamespace();
We should get the active namespace from redux connect and not from some global function.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +  componentCreated: boolean,
A lot of types here could be marked optional such as the errors so you can not use `null` as a value instead of empty string.

2019-04-24 14:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +  private _onBrowserClose = event => {
we don't need to prefix private functions with underscore in typescript.

2019-04-24 16:14 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/k8s/ns/:ns/git-import',
@vikram-raj can you change the path to `/dev/git-import/ns/:ns` . Refer this comment https://github.com/talamer/console/pull/38#discussion_r277704208 by @christianvogt .

2019-04-24 16:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/k8s/ns/:ns/git-import',
Also, you will have to redirect `/dev/git-import` to `/dev/git-import/ns/:ns` or `/dev/git-import/all-namespaces`. Refer latest routes.tsx.

2019-04-24 16:57 UTC, debsmita1 commented on frontend/public/extend/devconsole/pages/Import.tsx
> +      </p>
Should we remove the helper texts, below the input fields, as well ?

2019-04-24 20:00 UTC, debsmita1 commented on frontend/public/models/index.ts
> +
Done https://github.com/vikram-raj/console/pull/3

2019-04-24 20:00 UTC, debsmita1 commented on frontend/public/extend/devconsole/pages/Import.tsx
> +      </p>
https://github.com/vikram-raj/console/pull/3

2019-04-24 20:00 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +          this.setState({ gitType: '' });
Done https://github.com/vikram-raj/console/pull/3

2019-04-24 20:00 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    this.randomString = this._generateRandomString();
Done https://github.com/vikram-raj/console/pull/3

2019-04-24 20:00 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    const activeNamespace = getActiveNamespace();
Done https://github.com/vikram-raj/console/pull/3

2019-04-24 20:01 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +  private _onBrowserClose = event => {
Done https://github.com/vikram-raj/console/pull/3

2019-04-24 20:12 UTC, sbose78 commented
@vikram-raj , could we show the namespace context in the Import page?

2019-04-25 01:53 UTC, vikram-raj commented
@sbose78 Yes, we show the namespace context.

2019-04-25 01:58 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/import-flow-form/ImportFlowForm.tsx
> +    timeOut = setTimeout(() => {
Yes, it is not actually necessary. Because we are not making any API call here to validate the URL, just checking with regex.

2019-04-25 22:04 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Import.scss
> +}
Remove this and use `co-m-pane__body` instead.

2019-04-25 22:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    '': 'please choose Git type',
`please` -> `Please`
Also `Git` case doesn't match `git` used elsewhere.

2019-04-25 22:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          {showGitValidationStatus}
This doesn't show up well on mobile with the padding changes suggested:
![image](https://user-images.githubusercontent.com/14068621/56770094-1ad32c80-6781-11e9-8ef8-23f27626dc1e.png)
Should we not have the loader and validation beside the label?

2019-04-25 22:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/ImportFlow.tsx
> +import './ImportFlow.scss';
Doesn't look like you need `ImportFlow.scss`.

2019-04-25 22:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    return '';
This is weirdly done as the caller of `detectGitType` sets state and here we also set state. Choose one location to set the state.

2019-04-25 22:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  checkUrlValidationStatus() {
Change to `checkUrlValidationStatus: () => {` so you can avoid using `.bind`

2019-04-25 22:04 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
Why is this an interval and not a timeout?
Why not watch with a web socket? Why poll?

2019-04-26 06:10 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
> Why is this an interval and not a timeout?
Because we have to keep checking the GitSource until we got the status of the GitSource.

>Why not watch with a web socket? Why poll?
We tried to use existing ```watchK8sObject``` but we are facing some issue with it.

2019-04-26 07:12 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          {showGitValidationStatus}
Moved it to beside the label.

2019-04-26 07:14 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    return '';
Fix this. Remove the ```setState``` from ```detectGitType``` function.

2019-04-26 07:15 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  checkUrlValidationStatus() {
I missed this.

2019-04-26 11:21 UTC, divyanshiGupta submitted a review, later dismissed

2019-04-26 11:21 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.scss
> +    color: #1e4f18;
Use pf variables for colors

2019-04-26 13:44 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
Looks like on the first first interval callback to `checkUrlValidationStatus` and the very first result returned by `k8sGet` the interval is cancelled. So it doesn't look like you're actually polling anything. Unless maybe `k8sGet` returns an error in which case it continues to poll? Is that it?

2019-04-26 14:09 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
We cancel the interval when we get the status of the GitSource. we continue polling until we get the status of the GitSource.

2019-04-26 16:06 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
`validateGitRepo` creates the git source resource. It then starts an interval. After 3 seconds a call to `checkUrlValidationStatus` is made which immediately calls `k8sGet`. Since the resource was created 3 seconds ago, this will return successfully and then the poller interval is canceled. In the event of an error, then the interval makes sense. Are you encountering errors trying to retrieve the git source after the call to create the git source successfully returned? What kind of errors are you getting if that's the case?

2019-04-26 17:31 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
@christianvogt  We arent encountering any errors after the create git source call. 
For your pervious comment, we stop polling the moment we get a validation status, be it reachable or unreachable. The polling starts again when the user modifies the url. I thought we cannot do this with the `watchk8sObject` service, so went ahead with polling.

2019-04-26 17:54 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
I get the reason for why you need to do something along these lines. I just don't see how why the use of `setInterval` over `setTimeout`. I don't see where _interval_ polling is being used. Looks like it's a single delayed call to request the status and it's done only once per url update at which point the interval is restarted.

2019-04-26 18:07 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
After creating Gitsource cr we are able to fetch the status in a single get request. But I figured out that on creating gitsourceanalysis, it takes more than a single get request to fetch the build type name. So considering this I thought its safe to keep polling at intervals till we get the validation status for a git url.

2019-04-26 18:30 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
You just said `We arent encountering any errors after the create git source call.`
So what happens when you make the first GET request? Looks to me like it will go into the `then` callback and clear the interval. Or does it simply not execute the callback and there are no errors report....?
(this is about url validation and not build type)

2019-04-26 18:43 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          this.poller=setInterval(this.checkUrlValidationStatus.bind(this), 3000);
Now, whenever we make the first GET req, we are able to fetch the status and we clear the interval

2019-04-26 19:41 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.scss
> +    color: #1e4f18;
Done : https://github.com/vikram-raj/console/pull/6

2019-04-27 09:42 UTC, rohitkrai03 approved these changes

2019-04-27 09:44 UTC, merged