add feature flag to perspective switcher
talamer/console pull request #26
Opened 2019-04-02 10:53 UTC by karthikjeeyar

The perspective switcher will be enabled only if the dev console operator is installed.

2019-04-02 16:03 UTC, christianvogt commented
Since the entire perspective switcher and mega menu are being worked on. I'm ok without tests for this change as the current perspective switcher is a temporary implementation.

2019-04-02 16:37 UTC, christianvogt approved these changes

2019-04-03 13:52 UTC, karthikjeeyar commented
@christianvogt  @divyanshiGupta I have retained the existing functionality (collapse/expand of sidebar) when dev console is disabled.

2019-04-04 07:00 UTC, karthikjeeyar commented
@rohitkrai03  I resolved the conflicts and rebased the PR. Please review the changes

2019-04-04 07:19 UTC, rohitkrai03 requested changes

2019-04-04 07:19 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +        {devconsoleItem(props)}
You are sending props as a parameter to `devConsoleItem()` but the function doesn't accept any parameters. Its using props from its parent scope.

2019-04-04 07:50 UTC, rohitkrai03 approved these changes
LGTM

2019-04-04 07:50 UTC, merged