Add shared routes, nav items and views to dev console
talamer/console pull request #29
Opened 2019-04-04 20:34 UTC by rohitkrai03

Related Jira story https://jira.coreos.com/browse/ODC-128

- Adds shared routes based on the active perspective.
- Updates the utility function to generate Resource links.
- Updates all the other links on any shared view pages using a utility function which prepends given path with active perspective.
- Updates the namespace dropdown bar to work with other perspectives and dispatch correct actions when changing a namespace.
- Add menu items for shared views in dev console navigation based on latest updates from UX team.

<img width="200" alt="Screenshot 2019-04-05 at 2 04 13 AM" src="https://user-images.githubusercontent.com/6041994/55586662-2796ce80-5747-11e9-924f-045e6de11e83.png">

2019-04-05 23:38 UTC, christianvogt requested changes

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/components/nav.jsx
> +    return pathWithPerspective(formatNamespacedRouteForResource(resource, activeNamespace));
Why don't you use `PerspectiveLink in `NavLink#render`?

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/components/nav.jsx
> +    return pathWithPerspective(`/k8s/cluster/${this.props.resource}`);
Why don't you use `PerspectiveLink in `NavLink#render`?

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/components/utils/link.jsx
> +}, []);
Does this affect `ui-actions#formatNamespaceRoute`. Looks like it might as that code splits on `/` and references '[0]`.

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/components/utils/perspective.tsx
> +};
Please add a `FIXME` comment related to using global store.

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveLink.tsx
> +type PerspectiveLinkProps = StateProps & LinkProps;
`export` this type

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveLink.tsx
> +  };
This should be a static function and not in the render function. Or just move the logic inline of the return value.

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +          <HrefLink href="/dev/pipelines/run" name="Pipline Runs" activePath="/dev/pipelines/run" />
Remove this entry.

Only `Pipelines` should be present and it should not be within a section. It should be at the top level.

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +          <ResourceNSLink resource="buildconfigs" name={BuildConfigModel.labelPlural} />
Name this `Builds`. Ya it's weird. I last heard, build config was what we need to show. Maybe we should confirm with Serena.

It should also be a top level item and not within a section now that there's only one.

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +          <ResourceNSLink resource="imagestreams" name={ImageStreamModel.labelPlural} startsWith={['imagestreams', 'imagestreamtags']} />
Remove `builds` and `imagestreams`

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +        <DevNavSection title="Catalog">
Remove the entire `Catalog` section.

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/components/utils/resource-link.jsx
> +  return pathWithPerspective(url);
Please add a `FIXME` comment related to using global store.

2019-04-05 23:38 UTC, christianvogt commented on frontend/public/components/nav.jsx
> +    return resourcePath === props.resource || _.startsWith(resourcePath, `${props.resource}/`) || matchesModel(resourcePath, props.model) || resourcePath.includes(props.resource);
Isn't this risky? shouldn't we strip the legal perspectives and do the comparisons against the path without the perspective segment?

2019-04-07 13:02 UTC, rohitkrai03 commented on frontend/public/components/utils/link.jsx
> +}, []);
No it doesn't affect `ui-actions#formatNamespaceRoute`,  if we don't have Namespace Prefixes with perspectives then the formatting doesn't work since it doesn't recognises the prefix. 
So, the logic of `ui-actions#formatNamespaceRoute` first filters all `links#namespacedPrefixes` to get the current locations prefix. Then it gets `activeNamespace` and checks if previous namespace are not same and then generates the final route for namespace. So, having all the namespace prefixes with perspective enables us to be in the same perspective even when changing namespace.

2019-04-07 15:09 UTC, christianvogt commented on frontend/public/components/nav.jsx
> +  return href.replace(/^admin|dev\//, '');
Isn't there a list of perspectives you can make use of for this purpose? Furthermore admin isn't a valid perspective segment.

2019-04-08 11:37 UTC, rohitkrai03 commented
@christianvogt 
- I renamed `pathWithPerspective` -> `pathWithPerspectiveFromStore`.
- Created a new function `pathWithPerspective` which takes `activePerspective` and `path` encapsulating the logic of default perspective. Using it everywhere so that it would be easier to change the logic later.
- Fixed a bug in `MegaMenuItem` after the rebase.
- Also, added logic to generate links in `Add` action dropdown on the top. So, now any action stays in the same perspective. 

The PR is ready for review again.

2019-04-08 19:28 UTC, christianvogt approved these changes

2019-04-08 19:29 UTC, merged