feat(perspective-switcher): add switcher menu with navigational links
talamer/console pull request #3
Opened 2019-02-18 09:58 UTC by divyanshiGupta

Tasks implemented in PR : 

- https://jira.coreos.com/browse/ODC-36
- https://jira.coreos.com/browse/ODC-60

![switcher](https://user-images.githubusercontent.com/20724543/52942765-a26f7a00-3391-11e9-8bac-0d3ddc6ef425.gif)

Note : 
Merge this PR after https://github.com/talamer/console/pull/2

2019-02-18 09:59 UTC, divyanshiGupta commented
@joshuawilson I cannot add reviewers

2019-02-20 04:41 UTC, christianvogt requested changes

2019-02-20 04:41 UTC, christianvogt commented on frontend/public/components/app.jsx
> +        <Modal
This should be within the `extends/devconsole/shared` dir as a temp solution as we want to minimize the amount of changes outside our own directory.

2019-02-20 04:41 UTC, christianvogt commented on frontend/public/components/app.jsx
> +              <Link
Use `<NavLink>` with the prop `activeClassName` along with `isActive`. See https://reacttraining.com/react-router/web/api/NavLink

2019-02-20 04:41 UTC, christianvogt commented on frontend/public/style/_overrides.scss
> +.perspective-switcher {
Move these styles to a separate file to be imported by the new component to address the comment about moving the `Modal` to a separate component.

Pre-fix all of our styles with `devops-`

2019-02-25 02:30 UTC, christianvogt requested changes

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +          isActive={(match, { pathname }):boolean => !pathname.includes('/devconsole')}
Use `#startsWith` instead of `#includes`.

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +          isActive={(match, { pathname }):boolean => pathname.includes('/devconsole')}
This line is unnecessary because the default behavior uses the `to` property as the pathname to match. It also matches by default non-exact paths. ie it matches `/devconsole/*`

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +          activeClassName='devops-ps-active-link'
Follow BEM notation. Use `devops-perspective-switcher__active-link`.
Also use double quotes for JSX attributes.

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +          activeClassName='devops-ps-active-link'
Follow BEM notation. Use `devops-perspective-switcher__active-link`.
Also use double quotes for JSX attributes.

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +  currentPath: string
This prop is never used. Remove it.

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/components/app.jsx
> +          path={this.currentPath}
This is not a valid prop to `PerspectiveSwitcher`.

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/components/app.jsx
> +  get currentPath() {
This is no longer required.

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/style/_overrides.scss
> +
Undo changes to this file to leave it untouched.

2019-02-25 02:30 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.scss
> +.devops-perspective-switcher {
Update the css to make the overlay look like it covers the existing navigation. Also update the `active-link` to follow BEM and benefit from scss parent selector:

```
.devops-perspective-switcher {
  &.pf-c-modal-box {
    position: fixed;
    left: 0;
    top: 76px;
    height: calc(100vh - 76px);
    width: 290px;
  }

  &__active-link {
    color: black;
  }
}
```

2019-02-25 13:22 UTC, rohitkrai03 approved these changes
LGTM

2019-02-25 15:42 UTC, christianvogt approved these changes

2019-02-25 15:46 UTC, merged