Set topology view as landing page of dev-console
talamer/console pull request #33
Opened 2019-04-10 10:07 UTC by divyanshiGupta

Task : https://jira.coreos.com/browse/ODC-494

![devconsole-landing-page](https://user-images.githubusercontent.com/20724543/55870538-6d6bf080-5ba6-11e9-9cfa-8788ae81682f.gif)

2019-04-10 16:06 UTC, christianvogt requested changes

2019-04-10 16:06 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/PerspectiveSwitcher.tsx
> +        to="/"
This should still point to `/dev`. If the user right clicks and chooses to open in a new tab we'd end up opening up the admin perspective.

2019-04-10 16:06 UTC, christianvogt commented on frontend/public/components/app.jsx
> +        <Redirect to={`/${lastViewedPerspective}/topology`} />
You need to add a new route for `/dev` that redirects to the default page. You can use react-router's `Redirect` component.
Keep this as is.

2019-04-11 07:50 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +        <Redirect to={`/${lastViewedPerspective}/topology`} />
Yes, changes to this `Redirect` will affect other perspectives as well. Right now its generic enough for all perspective.

2019-04-11 08:03 UTC, rohitkrai03 approved these changes
LGTM

2019-04-11 13:44 UTC, christianvogt approved these changes

2019-04-11 13:45 UTC, merged