[WIP]feat(pipelines): Add Pipeline section to Dev Console
talamer/console pull request #37
Opened 2019-04-17 06:05 UTC by abhinandan13jan

2019-04-21 03:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/Pipelines/PipelineFilterReducer.tsx
> +export default DevpipelineFilterReducer;
This isn't a component. It shouldn't be in the components dir. And it shouldn't be a `.tsx` file but instead a `.ts` file.

2019-04-21 03:49 UTC, serenamarie125 requested changes
The Pipelines navigation item should be selected when pipelines or the details of a pipeline are being viewed

2019-04-21 07:46 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineFilterReducer.tsx
> +export default DevpipelineFilterReducer;
@christianvogt  I've moved the FilterReducer to devconsole/utils section as a ts file.

2019-04-21 07:48 UTC, abhinandan13jan commented
@serenamarie125  Added activation logic to the Pipeline navigation item
![Screenshot from 2019-04-21 13-16-50](https://user-images.githubusercontent.com/24852534/56467094-e20d1d80-6437-11e9-8377-ea837fab1803.png)
![Screenshot from 2019-04-21 13-16-54](https://user-images.githubusercontent.com/24852534/56467097-eb968580-6437-11e9-97f6-e201807f024c.png)

2019-04-21 18:14 UTC, rohitkrai03 requested changes

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    if( path == '/pipelines')
Why are you changing the logic for `isActive` specifically for `pipelines`? This should always be generic enough to handle all use cases. It shouldn't be working based on a bunch of `if-else` statements.

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +        <HrefLink href="/k8s/pipelines" name="Pipelines" activePath="/k8s/pipelines" isActive={isActive('/pipelines')} />
Any specific reason for adding `k8s` as prefix? Does this use namespaces in the URL?

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +    <ResourceSummary resource={pipeline}>
If there are no children you don't need a separate end tag. 
```suggestion
    <ResourceSummary resource={pipeline} />
```

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +  <div className="col-sm-6">
Can you use Patternfly4 react grids instead of Patternfly 3 since we are going to move to Patternfly 4 anyways?

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +<div className="row">
Spacing issue. Run prettier on your code.

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +const DevPipelineDetails = ({obj:pipeline}) => <div className="co-m-pane__body">
Use `(` for multi-line JSX. 
```suggestion
const DevPipelineDetails = ({obj:pipeline}) => (
  <div className="co-m-pane__body">
```

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +          return <React.Fragment key={task.name}><dt >Name: {task.name}</dt><dd>Ref: {task.taskRef.name}</dd></React.Fragment>
Run prettier. Spacing is all over the place in this file.

2019-04-21 18:14 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +  </div>
Run `yarn lint` and fix linting errors. Currently there are 115 lint errors in your code.

2019-04-21 18:17 UTC, rohitkrai03 commented
@abhinandan13jan Please run prettier on all your code. Also, run `yarn lint` and fix all the linting errors. I started reviewing your code but all I see right now is wrong formatting and linting errors. I can't focus on the code logic because of that.

2019-04-21 19:04 UTC, rohitkrai03 requested changes

2019-04-21 19:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetailsPage.tsx
> +  breadcrumbsFor={obj => breadcrumbsForOwnerRefs(obj).concat({
Not sure we need breadcrumbs. When asked about this in F2F presentation i got the answer that its just for visual representation of where we are and will not be part of final designs. But i see it in the [invision](https://redhat.invisionapp.com/share/BTRK9B9HRNJ#/358337971_DevOps_Console_-_CI-CD_Pipeline_01) link as well. I added a comment there as well. Maybe @serenamarie125 can have an answer for us.

2019-04-21 19:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineRow.tsx
> +const DevPipelineRow = ({obj: pipeline}) => {
Remove `Dev` prefix from all the components. It should just be `PipelineRow` as the filename suggests.

2019-04-21 19:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineRuns.tsx
> +  'pipeline' :'pipeline-a'
Why is this selector hard coding pipeline name?

2019-04-21 19:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/routes.tsx
> +const getRedirection = (basePath) => {
If you change your path to `/dev/k8s/ns/:ns/pipelines` then you don't need any redirection logic. It comes free with the admin console namespaced routes logic.

2019-04-21 19:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/routes.tsx
> +const getRedirection = (basePath) => {
Also, you get namespace bar on top without adding any extra prefix to `link.tsx`

2019-04-21 19:04 UTC, rohitkrai03 commented on frontend/public/models/index.ts
> +export const PipelineModel: K8sKind = {
Better to add these models in devconsole directory and reference them in resource-pages.tsx

2019-04-22 05:48 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineRuns.tsx
> +  'pipeline' :'pipeline-a'
@rohitkrai03 PipelineRuns are not included in this PR. This is only for visual representation.

2019-04-23 14:41 UTC, christianvogt requested changes
Run prettier and lint your code.

2019-04-23 14:41 UTC, christianvogt commented on frontend/public/components/utils/link.jsx
> +  '/dev/k8s/pipelines'
I don't believe this is necessary as the `/k8s` path above should capture this route.

2019-04-23 14:41 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    if( path == '/pipelines')
Let's address active routes as a bug. This is an issue that affects many routes and I don't want to get hung up on this here.

2019-04-23 14:41 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +        <HrefLink href="/k8s/pipelines" name="Pipelines" activePath="/k8s/pipelines" isActive={isActive('/pipelines')} />
Pipelines should be a `ResourceNSLink`.

2019-04-23 14:41 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/Pipelines/PipelineFilterReducer.ts
> +export default DevpipelineFilterReducer;
`DevPipelineStatus` and `DevpipelineFilterReducer` are exactly the same thing. Remove one.
Only classes should start with a capital letter.
Rename the file to `pipeline-filter-reducer.ts` to align with naming conventions.
Also do not name the parent folder `Pipelines`. Use `pipelines`. Not sure if a parent folder is even necessary though.
Remove default export and use name exports for utility files.

2019-04-23 18:03 UTC, abhinandan13jan commented on frontend/public/models/index.ts
> +export const PipelineModel: K8sKind = {
@rohitkrai03 Yes, these will be fetched from Devconsole. As these models are not final yet(pipelines not merged), going for the simplest implementation for summit and will update accordingly when models are finalized.

2019-04-23 18:06 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    if( path == '/pipelines')
@rohitkrai03 @christianvogt I've implemented new login for isActive which will take care of all cases

2019-04-23 18:13 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +        <HrefLink href="/k8s/pipelines" name="Pipelines" activePath="/k8s/pipelines" isActive={isActive('/pipelines')} />
@rohitkrai03 @christianvogt Added Pipeline as a resource

2019-04-23 18:14 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +  <div className="col-sm-6">
@rohitkrai03 Will take care of the interface related details after UX is final.

2019-04-23 18:15 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +<div className="row">
@rohitkrai03 Used prettier and linter

2019-04-23 18:15 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +          return <React.Fragment key={task.name}><dt >Name: {task.name}</dt><dd>Ref: {task.taskRef.name}</dd></React.Fragment>
@rohitkrai03 Ran Lint and Prettier

2019-04-23 18:16 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetails.tsx
> +  </div>
@rohitkrai03 Thanks for pointing it out. :) Fixed.

2019-04-23 18:16 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineDetailsPage.tsx
> +  breadcrumbsFor={obj => breadcrumbsForOwnerRefs(obj).concat({
@rohitkrai03 Removed breadcrumbs

2019-04-23 18:17 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineRow.tsx
> +const DevPipelineRow = ({obj: pipeline}) => {
@rohitkrai03 Removed Dev prefix from all class/function names

2019-04-23 18:18 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/Pipelines/PipelineRuns.tsx
> +  'pipeline' :'pipeline-a'
@rohitkrai03 it was hardcoded as pipelineruns were still under development. Right now it uses this.props.obj.metadata.name instead

2019-04-23 18:18 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/routes.tsx
> +const getRedirection = (basePath) => {
@rohitkrai03 removed

2019-04-23 18:20 UTC, abhinandan13jan commented on frontend/public/models/index.ts
> +export const PipelineModel: K8sKind = {
@rohitkrai03 yes, indeed. They will be fetched from Devconsole. Right now as the models are not final(tekton pipelines/CLI not merged) going for the simplest implementation. Will fetch them from Devconsole once the finalised pipelines are in place.

2019-04-23 18:21 UTC, abhinandan13jan commented on frontend/public/components/utils/link.jsx
> +  '/dev/k8s/pipelines'
@christianvogt removed

2019-04-23 18:21 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/Pipelines/PipelineFilterReducer.ts
> +export default DevpipelineFilterReducer;
@christianvogt Merged into one

2019-04-23 19:02 UTC, sbose78 commented
Just so that I could confirm that this is going to come in a later PR:

1. If I navigate to http://localhost:9000/dev/k8s/ns/devns/pipelines/tekton-pipeline-structure/Runs
2. and click on a pipelineRun, I get a 404.

2019-04-23 19:38 UTC, abhinandan13jan commented
@sbose78 Yes, Details for PipelineRun will be covered in a separate story and PR. PipelineRun has not yet been configured/finalized as a resource till now, so the resource details view throws a 404.

2019-04-23 19:44 UTC, sbose78 commented
Ah that's because you don't have `PipelineRuns/PipelineRunDetails.tsx` yet 👍

2019-04-23 19:44 UTC, sbose78 commented on frontend/public/extend/devconsole/components/PipelineRuns/PipelineRunRow.tsx
> +    return 'Complete';
Why are we doing this instead of keeping it as is. In the same context, why are we not doing 
```
items: [
    { id: 'Succeeded', title: 'Succeeded' },
    { id: 'Failed', title: 'Failed' },
    { id: 'Running', title: 'Running' },
  ],
```

in Pipelines/PipelineRuns.tsx

2019-04-23 19:44 UTC, sbose78 commented on frontend/public/extend/devconsole/components/Pipelines/PipelineRuns.tsx
> +    { id: 'Succeeded', title: 'Complete' },
Are we doing this to adhere to the screens provider ?

2019-04-23 19:44 UTC, sbose78 commented on frontend/public/models/index.ts
> +export const PipelineModel: K8sKind = {
.. or since there could be other extensions which might want to possibly re-use the extended `models`, you could consider keeping them under `extend/models/`

2019-04-23 20:23 UTC, abhinandan13jan commented
@sbose78 I've not yet added the resource kind for 'pipelinerun' in the current list which is displaying the runs, will dig into that during the next story and PR. Once that is in place the 'pipelinerun' details will be visible. For most 'filter' and 'status' nomenclature, it is done to mostly bridge the difference between the server response and the interface as per UX.

2019-04-23 20:24 UTC, abhinandan13jan commented
@sbose78 Yes, moving the models to a common location seems like a good idea. Thanks.

2019-04-24 08:57 UTC, abhinandan13jan commented
This PR is now outdated and prone to merge conflicts. Closing this and raising new PR https://github.com/talamer/console/pull/42

2019-04-24 08:57 UTC, closed without merging