Create empty state component and add in topology view
talamer/console pull request #38
Opened 2019-04-17 09:22 UTC by divyanshiGupta

Story: https://jira.coreos.com/browse/ODC-421

In this PR I have implemented:
- `EmptyState` component
- Added checks for deciding when to display `EmptyState` 
- Added test cases for `TopologyPage` and `EmptyState`

Note
I will add a gif once my minishift starts working

2019-04-17 14:09 UTC, divyanshiGupta commented
Closed the PR by mistake

2019-04-18 15:53 UTC, christianvogt requested changes

2019-04-18 15:53 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Topology.tsx
> +  const namespace = _.get(props.match, 'param-ns');
This should be: `params.ns`

2019-04-18 15:53 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Topology.tsx
> +    >
I cannot get your empty state to load at all. Not like is shown in your gif.

2019-04-18 15:53 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.scss
> +}
We shouldn't need this.
Do we need to update patternfly to get the proper functionality to center the empty state?
What does console do today to center their empty state?

2019-04-18 15:53 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +      }}
Replace with `EmptyStateSecondaryActions`

2019-04-18 15:53 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +  <EmptyState className="odc-empty-state">
Looks like we need to update patternfly to get the `full` variant.

2019-04-18 15:53 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Topology.tsx
> +  match: any;
Can we type this from `react-router` ?

2019-04-19 06:57 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/pages/Topology.tsx
> +    >
So you had no `deploymentConfigs` in your `activeNamespace` and even then you cannot see the empty state? I am looking into it, but it works for me. I will ask someone else to try it out as well.

2019-04-19 07:16 UTC, rohitkrai03 requested changes

2019-04-19 07:16 UTC, rohitkrai03 commented on frontend/public/ui/ui-selectors.js
> +export const getActiveNamespace = (state) => state.UI.get('activeNamespace');
Don't add this selector for now. Because there is already a function in `ui-actions.js` called `getActiveNamespace` and this may lead to name collisions. Later on we need to fix this by removing `getActiveNamespace` which uses global redux store directly.

2019-04-19 07:16 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +        activePerspective={props.activePerspective}
You don't need to pass `activePerspective` as a prop to `PerspectiveLink`. Its already a connected component.

2019-04-19 07:16 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +        activePerspective={props.activePerspective}
Same here

2019-04-19 07:16 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +        activePerspective={props.activePerspective}
Same here

2019-04-19 07:16 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +    activePerspective: getActivePerspective(state),
You don't need to map `activePerspective` here.

2019-04-19 07:16 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/pages/Topology.tsx
> +    >
Weird. I just tried it and it works for me.

2019-04-19 07:18 UTC, rohitkrai03 requested changes

2019-04-19 07:18 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +import { PerspectiveLink } from '../PerspectiveLink';
This should be default import `import PerspectiveLink from '../PerspectiveLink';`

2019-04-19 07:20 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +  <EmptyState className="odc-empty-state">
Yes, we need to update @patternfly/react-core to use `EmptyStateVariant.full`

2019-04-19 07:20 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +import { PerspectiveLink } from '../PerspectiveLink';
Yes, missed it :P

2019-04-19 07:23 UTC, divyanshiGupta commented on frontend/public/ui/ui-selectors.js
> +export const getActiveNamespace = (state) => state.UI.get('activeNamespace');
Or I can change the name of the selector to something else like `getActiveNamespaceFromUI`

2019-04-22 09:04 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.scss
> +}
They are using patternfly3 empty state in which by default the content is placed in the center and the empty state occupies the full page similar to what you can do using `EmptyStateVariant.full` in pf4 empty state. In the latest version they have added modifiers for changing the width of the empty-state keeping the full one as default. We need to update pf4, until then we can keep this as is and also I will add a comment saying "remove this once pf4 is updated". We are anyways going to change the UI for empty state.

2019-04-23 00:38 UTC, serenamarie125 requested changes
If this is a short term fix until we convert to PF4, let's be sure to add 2 additional items for the Summit milestone
1. "Import from git" which is the new _Import from git_ flow
1. "Add database" which is a filtered version of the developer catalog (filtered by DATABASE)

2019-04-23 07:58 UTC, divyanshiGupta commented
> If this is a short term fix until we convert to PF4, let's be sure to add 2 additional items for the Summit milestone
> 
> 1. "Import from git" which is the new _Import from git_ flow
> 2. "Add database" which is a filtered version of the developer catalog (filtered by DATABASE)

@serenamarie125 we are already using PF4 empty state. We decided to go forward with the current pattern since the corresponding UX story is still WIP, we will have to create another story for implementing new UX design when the empty state UX story gets completed. Yes I have added `Add Database` but didnt update the gif, I will do that now. I will add `Import from git` since now we have created a separate route for the same.

2019-04-23 14:23 UTC, christianvogt requested changes

2019-04-23 14:23 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.scss
> +}
To center something use margin left / right with a value of `auto`.

2019-04-23 14:23 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +export default connect<StateProps, {}, {}>(mapStateToProps, () => ({}))(ODCEmptyState);
Simplify to:
`export default connect<StateProps>(mapStateToProps)(ODCEmptyState);`

2019-04-23 14:23 UTC, christianvogt commented on frontend/public/ui/ui-selectors.js
> +export const getActivePerspective = state => state.UI.get('activePerspective');
I don't see you making use of this change.

2019-04-23 14:23 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +        to={formatNamespacedRouteForResource('git-import', props.activeNamespace)}
This creates a url like: `/dev/k8s/ns/empty-project/git-import`
git-import is not a k8s resource and should follow the same url scheme as other non-resources pages:
`/dev/git-import/ns/<namespace>`. Look at the catalog link for example.
Console isn't perfectly consistent in this area. eg. the `/import` page

2019-04-23 14:25 UTC, divyanshiGupta commented on frontend/public/ui/ui-selectors.js
> +export const getActivePerspective = state => state.UI.get('activePerspective');
I haven't added this :)

2019-04-23 14:29 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +        to={formatNamespacedRouteForResource('git-import', props.activeNamespace)}
So @vikram-raj added this route in his PR as I asked him not to use the route for `dev/add` for `git-import` and create a separate one (https://github.com/talamer/console/pull/25#discussion_r277292408). I will change the path here to what you suggested and will ask @vikram-raj to change the route.

2019-04-23 14:30 UTC, divyanshiGupta commented on frontend/public/ui/ui-selectors.js
> +export const getActivePerspective = state => state.UI.get('activePerspective');
Juts ran prettier over it and it removed the parentheses around state :P

2019-04-23 14:42 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +        to={formatNamespacedRouteForResource('git-import', props.activeNamespace)}
Ok that's fine. We can always adjust routes later. Figured since there's other changes, may as well do this now too. Vikram's PR is still a WIP and can adapt.

2019-04-23 14:49 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/EmptyState/EmptyState.tsx
> +        to={formatNamespacedRouteForResource('git-import', props.activeNamespace)}
Yes, I have changed it and asked @vikram-raj to change the route.

2019-04-23 14:57 UTC, rohitkrai03 requested changes

2019-04-23 14:57 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/routes.tsx
> +const RedirectToNamespace: React.FunctionComponent<RedirectToNamespaceProps> = (
Reuse the `NamespaceRedirect` component from `app.jsx` instead of just `appendActiveNamespace `

2019-04-23 14:57 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/routes.tsx
> +    render: (props) => <RedirectToNamespace location={props.location} />,
After importing `NamespaceRedirect` 
```suggestion
    render: (props) => <NamespaceRedirect {...props} />,
```

2019-04-23 16:13 UTC, christianvogt approved these changes

2019-04-23 16:14 UTC, christianvogt commented
@divyanshiGupta I will merge this PR. Create a new PR one to align the UI with the latest UX.

2019-04-23 16:21 UTC, divyanshiGupta commented
@christianvogt shouldn't we create a story to track that? Anyways the related UX story is still in progress. So should I start working on it when the UX story is done or we want to start implementing the new UI and iterate over it?

2019-04-23 16:36 UTC, rohitkrai03 commented
@christianvogt @divyanshiGupta Right now the code is getting namespace from URL and passing that to `Firehose` for getting deployment configs. Since we don't have topology URL with namespace right now it doesn't work on Openshift 4. It worked on Openshift 3 because maybe by default openshift 3 doesn't send any resource if namespace not specified and openshift 4 sends all resources if not specified. This is not an issue right now because we will always have topology URL with namespace, so it would work fine.

2019-04-23 16:38 UTC, rohitkrai03 approved these changes
LGTM

2019-04-23 16:40 UTC, divyanshiGupta commented
> @christianvogt @divyanshiGupta Right now the code is getting namespace from URL and passing that to `Firehose` for getting deployment configs. Since we don't have topology URL with namespace right now it doesn't work on Openshift 4. It worked on Openshift 3 because maybe by default openshift 3 doesn't send any resource if namespace not specified and openshift 4 sends all resources if not specified. This is not an issue right now because we will always have topology URL with namespace, so it would work fine.

@rohitkrai03 yes, you are right. Once we have the Topology URL with namespace it will work since I am extracting the namespace from the URL. I was adding the route for topology with namespace but then I saw other two PRs doing the same thing so I avoided adding it since it eventually will get added. I can add that in this PR if needed.

2019-04-23 17:44 UTC, merged