[WIP] feat(topology): integrate topology layout
talamer/console pull request #39
Opened 2019-04-19 02:17 UTC by christianvogt

* Sets up the topology page to hold the graph
* Renders react components as graph nodes
* Overlays a toolbar for the graph controls
* Uses a simple D3 layout for nodes as a simple POC of separating out the layout component from the rest of the graph
* Handles browser / container resizing
* Supports pan / zoom

![image](https://user-images.githubusercontent.com/14068621/56401538-52912000-6227-11e9-8acf-d4f69d272e6b.png)

2019-04-21 03:52 UTC, serenamarie125 requested changes

2019-04-21 03:52 UTC, serenamarie125 commented on frontend/public/extend/devconsole/pages/Topology.tsx
> +  const title = namespace ? `Topology of ${namespace}` : 'Topology';
@christianvogt the page title should just be "Topology"

2019-04-23 13:58 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/topology/ns/:ns',
Why do we need to add this twice?

2019-04-23 14:45 UTC, christianvogt commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/topology/ns/:ns',
We don't :) Just left over code.

2019-04-23 14:45 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Topology.tsx
> +  const title = namespace ? `Topology of ${namespace}` : 'Topology';
ok

2019-04-25 18:13 UTC, christianvogt commented
@karthikjeeyar in order to integrate better with the empty state, I refactored the `TopologyDataController` to include the firehose as we needed the result of the transformation in order to decide when to show the empty state.

@sahil143 I have integrated the workload node with the topology and made some small changes in order to pull the correct data from the model. I'd like to do some refactoring to support a default node and a workload node. As before your change I had a default node available but it's slightly different than the workload node. I'd like to combine the two and allow the `BaseNode` to be used as the default node. I wanted to do minimal changes here to get the workload node functional in the layout so any further changes I'll want to address in a separate PR.

2019-04-26 07:52 UTC, karthikjeeyar reviewed
@christianvogt, when the graph gets updated with the new data the drag, and drop feature fails to work. Probably by diffing the old state and new state of the graph data and add/remove node accordingly should fix this issue and also improves the performance as well.

2019-04-26 07:52 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +        data={data.data.donutStatus.pods}
data.data.donutStatus.pods is not explicit about what the data is,  specify an alias to the props `data: node`.

2019-04-26 07:52 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +  data,
add an alias to the data prop

2019-04-26 11:43 UTC, christianvogt commented
@karthikjeeyar in order to do a data diff we need a consistent Id generated for nodes. This is something I was going to address in another pr. There is also a Todo in graph about blind casting the graph data which is causing node positions to be lost on update. So there are still outstanding problems with updating the graph with new data.

I'll look at why DND fails after update.

2019-04-26 15:10 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +  data,
changed to `data: workload`

2019-04-26 15:11 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +        data={data.data.donutStatus.pods}
changed to `data: workload`

2019-04-26 15:12 UTC, christianvogt commented
I fixed the DND issue which was due to not updating the data in the dom node for d3 to function.

2019-04-26 15:43 UTC, karthikjeeyar commented
LGTM

2019-04-26 15:44 UTC, karthikjeeyar approved these changes

2019-04-26 15:56 UTC, merged