fix embedded dev console routes
talamer/console pull request #4
Opened 2019-02-20 21:42 UTC by christianvogt

`react-router` does not allow nesting of `<Switch>` and therefore the fallback routes were not being hit in the OS console. I have refactored the dev console routes to be an array of route objects instead of a React component.

Now to embed the routes, we map over the routes in the OS console app.

Furthermore I use async loading and chunking of our routes.

2019-02-21 04:59 UTC, rohitkrai03 requested changes
I think we could refactor the routes to have even less information since all the routes are built using same AsyncComponent. Maybe have only path and component name in the routes array and move the render prop to .map call or a generic function.

2019-02-21 08:43 UTC, debsmita1 reviewed
May be we could define a LazyRoute component which uses the AsyncComponent, and then make use of this LazyRoute to define all the asynchronous routes in devconsole by simply sending the path and the loader as props

Below is the screenshot of the LazyRoute Component in the app.jsx file
![screenshot from 2019-02-21 14-10-34](https://user-images.githubusercontent.com/22490998/53155235-a5ad7480-35e2-11e9-8ef7-2f1983a23519.png)

2019-02-21 15:03 UTC, christianvogt commented
@rohitkrai03 I want the OS console `app.jsx` to make no assumptions on the routes. Therefore we should continue to control whether the route is lazy or not. Furthermore I want to make the least amount of changes to the OS console code as possible.

2019-02-22 03:55 UTC, rohitkrai03 approved these changes

2019-02-22 14:56 UTC, merged