[WIP]: Topology data model
talamer/console pull request #40
Opened 2019-04-19 21:30 UTC by karthikjeeyar

The data controller component receives the k8s object and transforms the data into the below format

```
{  
   "graphData":{  
      "nodes":[  
         {  
            "id":"d0e7c0de-5f6a-11e9-93ab-525400a53bdd",
            "name":"nodejs"
         },
         {  
            "id":"8c6ddae3-606c-11e9-b12c-525400a53bdd",
            "name":"nodejs1"
         },
         {  
            "id":"ed6a85f7-5f70-11e9-93ab-525400a53bdd",
            "name":"php"
         },
         {  
            "id":"76393f64-5f81-11e9-93ab-525400a53bdd",
            "name":"python"
         }
      ],
      "edges":[  
           {"source": "ed6a85f7-5f70-11e9-93ab-525400a53bdd",
            "target": "76393f64-5f81-11e9-93ab-525400a53bdd"}

      ],
      "groups":{  
            "id": '34393f64-5f81-11e9-93ab-525400a53bdd",
            "name": "application-1",
            "nodes": [ {...} , {...}]
      }
   },
   "topologyData":{  
      "d0e7c0de-5f6a-11e9-93ab-525400a53bdd":{  
         "id":"d0e7c0de-5f6a-11e9-93ab-525400a53bdd",
         "type":"workload",
         "resources":[  
            {  
               "metadata":{ ... },
               "status":{ ... },
               "name": "nodejs",
               "kind":"DeploymentConfig"
            },
            {  
               "metadata":{ ... },
               "status":{ ... },
               "name": "nodejs",
               "kind":"ReplicationController"
            },
            {  
               "metadata":{ ... },
               "status":{ ... },
               "name": "nodejs-service",
               "kind":"Service"
            },
            {  
               "metadata":{ ... },
               "status":{ ... },
               "name": "nodejs",
               "kind":"Route"
            }
         ],
         "data":{  
            "url":"dummy_url",
            "edit_url":"dummy_edit_url",
            "donut_status":{ ...// contains pods information }
         }
      }
}
}
```

2019-04-23 05:26 UTC, vikram-raj commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/topology/ns/:ns',
Isn't the route should be ```/dev/ns/:ns/topology```? Because we follow this pattern for the route in the console.

2019-04-23 06:05 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/routes.tsx
> +    path: '/dev/topology/ns/:ns',
Corret, topology routes should be namespaced, Routes and pages for topology has been already added by Christian in another PR. I have added these routes to test the data model, this changes are to be removed when we are integrating the data model with topology layout

2019-04-23 14:59 UTC, christianvogt requested changes

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +}
Interfaces should start with a capital letter.

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +}
Move re-usable types to `topology-types.ts`

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +}
Personal preference. But just, array types can also be `Node[]` vs `Array<Node>`
Also Object can be `{}` but I think in this case we want a proper type for `topolgyData`.
Rename `graphData` -> `graph` and `topologyData` to `topology`.

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +    return shouldUpdate && nextProps.loaded;
That's a lot of comparisons. Won't we always get here because one of these values has changed? Therefore the comparisons are extra work for no value?

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +  transformData(topologyGraphData, selectorsByService, resource) {
Move all data transformations to a utility class for separation and ease of testing.

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +      ];
Why bother omitting the spec? Does it matter? Since we already have the information, may as well keep the full resource.

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +  }
It would be good if we could create reproducible unique identifiers so that in the future maybe we can save state or graph data and have it link back up correctly.
Since we don't currently have a use case, I'm ok with this for now.

2019-04-23 14:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +      </React.Fragment>
No fragment necessary.

2019-04-23 22:47 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/pages/Topology.tsx
> -      <TopologyPageContent />
this needs to be moved to topologyLayout

2019-04-23 22:52 UTC, christianvogt requested changes

2019-04-23 22:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataController.tsx
> +  }
Remove constructor

2019-04-23 22:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataUtils.tsx
> +  getRoute(service: ResourceProps): ResourceProps {
Does this function and others like it need to be public?

2019-04-23 22:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/topology-types.ts
> +export interface TopologyDataProps {
Props should remain colocated in the file that defines the component that uses the props. Unless props will be reused across multiple components. I don't believe that's the case here.

2019-04-24 15:07 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyDataUtils.tsx
> +export class TransformTopologyData {
This is a utility file and therefore should end in `.ts` and not `.tsx`.
Rename to `topology-utils.ts` since it doesn't export a react component.

2019-04-24 15:07 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologyLayout.tsx
> +const TopologyLayout: React.SFC<any> = (props: any) => {
Missing use of props.

2019-04-24 15:07 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/topology-types.ts
> +}
Isn't this the same as `K8sResourceKind` that console defines?

2019-04-24 15:07 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/topology-types.ts
> +}
Again looks like the same as `PodModel`. Let's reuse types where we can.

2019-04-24 15:28 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/components/topology/topology-types.ts
> +}
No, it is not the same. It includes a few other properties like apiVersions and type which are mandatory fields. we are not getting those from the firehose resources object.

2019-04-24 15:32 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/components/topology/topology-types.ts
> +}
we are pulling out the information like the id, name, and type at the top level. so it is having its own definition

2019-04-24 19:00 UTC, christianvogt approved these changes

2019-04-24 19:07 UTC, merged