[WIP] Topology Node
talamer/console pull request #41
Opened 2019-04-24 05:07 UTC by sahil143

ODC Story: https://jira.coreos.com/browse/ODC-430

Done:
BaseNode
![Screenshot from 2019-04-24 10-22-00](https://user-images.githubusercontent.com/9278015/56633442-c5612780-667b-11e9-9361-2a42c51a9e04.png)
WorkloadNode
![Screenshot from 2019-04-24 10-21-37](https://user-images.githubusercontent.com/9278015/56633453-d4e07080-667b-11e9-86ca-3fe778f25d44.png)
Decorator
![Screenshot from 2019-04-24 10-21-05](https://user-images.githubusercontent.com/9278015/56633467-df026f00-667b-11e9-9234-fd89a673e592.png)
Wrapped in Node Wrapper(should look like this):
![Screenshot from 2019-04-24 10-22-31](https://user-images.githubusercontent.com/9278015/56633486-f3466c00-667b-11e9-903e-c70246722160.png)

##TODO

- [ ] Test with topology layout
- [ ] Display the label on node by going through this order 
```
app.kubernetes.io/instance
app.kubernetes.io/component
app.kubernetes.io/name
deployment config resource name
```
- [ ] Add edit icon on decorator
- [ ] covert NodeWrapper to Class Component

2019-04-24 15:41 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +          </g>
A child of a decorator should not have to specify a transform for positioning this should be handled by the decorator itself.

2019-04-24 15:41 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +    this.decoratorRadius = this.radius * 0.25;
Calculations based on props should always occur in the render function.

2019-04-24 15:41 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +type state = {
Types and interfaces should use PascalCase.

2019-04-24 15:41 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/WorkloadNode.tsx
> +      <g className="donut" transform={centerTransform}>
Why do we need this transform? The outer group should control the position of all children.

2019-04-24 15:58 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +          strokeWidth={baseOuterRadius * 0.06}
Colors should be pulled from patternfly using css.
The selected stroke should be a fixed size in case we do change node sizes. Want uniformity across nodes.

2019-04-24 15:58 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +  baseInnerRadius: number;
Can remove `base` from the prop name. 
Do we even need these or can we go with just radius.

2019-04-24 15:58 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +    <g transform={`translate(${x}, ${y})`}>
We don't need the transform location here as the parent node group should control the overall location of the node.

2019-04-24 15:58 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +        style={{ fontSize: baseOuterRadius * 0.25 }}
Font-size should be fixed.

2019-04-24 16:00 UTC, divyanshiGupta requested changes

2019-04-24 16:00 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +  return (
You don't need to return the component explicitly since everything is wrapped in a single element, you can remove the curly braces and return statement. Check other files too

Also, run prettier over your code

2019-04-24 16:00 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +}) => {
You dont need to list all the props here, you can do this `({x=0, y=0, ...props})`. Check other files too

2019-04-24 16:00 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +      <circle cx={0} cy={0} r={baseOuterRadius} fill="#fff" />
can you use patternfly variables for colors wherever possible?

2019-04-24 16:04 UTC, divyanshiGupta commented
@sahil143 there are 90 lint errors currently in this PR. Please run `yarn lint` and fix the errors. Also. run prettier over your code

2019-04-24 16:09 UTC, divyanshiGupta requested changes

2019-04-24 16:09 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +import { PenIcon } from '@patternfly/react-icons';
Absolute imports should come before relative ones

2019-04-24 16:27 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/WorkloadNode.tsx
> +      <g className="donut" transform={centerTransform}>
This transform property is not being used. Transformation is done on basis of NodeWrapper group. I just added this if we would need to use this as a standalone component. x,y are optional props

2019-04-24 16:31 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +          strokeWidth={baseOuterRadius * 0.06}
Shouldn't  `strokeWidth` change if the node size changes? if we have node with a radius of 300 then selected `strokeWidth` would be fixed and much thinner.

2019-04-24 16:35 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +  baseInnerRadius: number;
We can go with just radius but then we would have to do all calculation in BaseNode which I wanted to avoid and inner radius determine the radius of svg image.
I will remove the base from prop name

2019-04-24 16:36 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +    <g transform={`translate(${x}, ${y})`}>
Same as above. This transform is not being used. Only the parent transform is used.

2019-04-24 16:38 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +        style={{ fontSize: baseOuterRadius * 0.25 }}
If we increase the radius of node then the `text` font size would be smaller. Just wanted to make the font size relative to the node size so it doesn't look weird if we increase the node radius in code.

2019-04-24 16:43 UTC, sahil143 commented
@divyanshiGupta can you check again? I fixed lint error except this one `error  'pods' was used before it was defined ` Pods constant will be removed as this is dummy data. I ran prettier also.

2019-04-24 16:47 UTC, divyanshiGupta commented
@sahil143 checking

2019-04-24 16:48 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +          </g>
Yes, Agree. But when I tried to handle this with decorator itself. PenIcon was stuck on the edge of decorator circle that's why I used transform on child also

2019-04-24 16:51 UTC, divyanshiGupta commented
@sahil143 except for this `error 'pods' was used before it was defined ` there are no more errors :)

2019-04-24 18:31 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +    this.decoratorRadius = this.radius * 0.25;
fixed in https://github.com/talamer/console/pull/41/commits/c0433c296811f4e4ea64e9f2b5ee6d234a7cd11b

2019-04-24 18:31 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +type state = {
fixed

2019-04-24 18:31 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +  baseInnerRadius: number;
changed prop name in https://github.com/talamer/console/pull/41/commits/dda06a3efed96edf793958f3707418062c40c3a1

2019-04-24 18:32 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +  return (
Changed in https://github.com/talamer/console/pull/41/commits/c0433c296811f4e4ea64e9f2b5ee6d234a7cd11b

2019-04-24 18:34 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +}) => {
This is intentional. I wanted to grab specific props because some are optional. :)

2019-04-24 18:34 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Node/NodeWrapper.tsx
> +import { PenIcon } from '@patternfly/react-icons';
changed the order

2019-04-24 18:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/Node/BaseNode.tsx
> +          strokeWidth={baseOuterRadius * 0.06}
I think regardless of shape or size, the selection thickness should be consistent across nodes.

Not that we have different shapes yet anyways.

2019-04-25 03:12 UTC, christianvogt approved these changes
Approving and merging to move forward with integration task.

2019-04-25 03:13 UTC, merged