feat(pipeline): Add Pipeline to Devconsole
talamer/console pull request #42
Opened 2019-04-24 08:56 UTC by abhinandan13jan

@rohitkrai03 @christianvogt  Please review. Please follow the steps.
1. Extend your API
Go to /console/frontend/public/extend/devconsole/components/__mocks__/Pipelines/ then run the following file
chmod +x install_pipeline_mocks.sh
install_pipeline_mocks.sh

2. Visit URLhttp://localhost:9000/dev/k8s/ns/myproject/pipelines and select all the filters. You would get a view as follows:
![Screenshot from 2019-04-23 23-37-53](https://user-images.githubusercontent.com/24852534/56605222-3f17f780-6621-11e9-8b6a-78f0a00bdf59.png)

3. Click on Pipeline-a to see details
![Screenshot from 2019-04-23 23-37-59](https://user-images.githubusercontent.com/24852534/56605239-4939f600-6621-11e9-9464-a5ce004a0040.png)

4. Click on Runs to see the PipelineRuns for the specific Pipeline
![Screenshot from 2019-04-23 23-37-29](https://user-images.githubusercontent.com/24852534/56605271-6373d400-6621-11e9-8512-2f427839714f.png)

P.S: This covers ODC-434 and ODC-432, ODC-433. Test cases will be taken care of in a separate PR.

2019-04-24 09:16 UTC, abhinandan13jan commented
@rohitkrai03 @christianvogt  Please review. Will move the models to devconsole  when models are finalized(tekton pipelines are merged).

2019-04-24 11:46 UTC, sbose78 commented on frontend/public/extend/devconsole/components/pipelineruns/pipeline-run-row.tsx
> +    return 'Complete';
We might want to keep this consistent instead of this textual transformation.

2019-04-24 12:30 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelineruns/pipeline-run-row.tsx
> +    return 'Complete';
updated. Keeping it as-is

2019-04-24 12:46 UTC, serenamarie125 commented
This looks great, based on a review we had on 24-April, please make the following updates:

1. Change the "Pipeline Name" column to "Name" in the Pipeline List View
1. Change the "Runs" tab to "Pipeline Runs" in the Pipeline Detail View
1. In the Pipeline Detail View, the status should be "Successful" not "Complete"
1. In the Task Progress column of the Pipeline Detail View, change the content to be _5 of 7_ , representing # tasks completed of # total tasks

2019-04-24 12:46 UTC, serenamarie125 requested changes

2019-04-24 12:46 UTC, serenamarie125 commented on frontend/public/extend/devconsole/components/pipelines/pipeline-header.tsx
> +  <ColHead {...props} className="col-lg-3 col-md-3 col-sm-4 col-xs-6" sortField="metadata.name">Pipeline Name</ColHead>
Rename "Pipeline Name" to "Name"

2019-04-24 14:02 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelines/pipeline-header.tsx
> +  <ColHead {...props} className="col-lg-3 col-md-3 col-sm-4 col-xs-6" sortField="metadata.name">Pipeline Name</ColHead>
@serenamarie125 Updated 'Pipeline Name' to 'Name', 'Runs' to 'Pipeline Runs', status is shown as 'Succeeded' as returned from the server, content changed to 5 of 7 (Please note Task details not available with the call). Please check screenshots for the changes.

2019-04-24 14:50 UTC, christianvogt reviewed
Please run prettier on all your files in dev console.
Rename react component files to be PascalCase.
Missing a lot of typescript props and typings in your files. I know you copied the patterns of existing console code, but we need to improve on the use of typescript and not add to the debt.

2019-04-24 14:50 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    return includeFlag && !excludeFlag;
Although better than what we got we cannot simply do string matching. This should be using react-router match. I've said before we can handle this as a separate bug instead of trying to solve the problem here.

2019-04-24 14:58 UTC, serenamarie125 commented on frontend/public/extend/devconsole/components/pipelines/pipeline-header.tsx
> +  <ColHead {...props} className="col-lg-3 col-md-3 col-sm-4 col-xs-6" sortField="metadata.name">Pipeline Name</ColHead>
Excellent, thank you @abhinandan13jan for the quick work, this is awesome!

2019-04-24 14:58 UTC, serenamarie125 approved these changes
Great work!

2019-04-25 14:05 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    return includeFlag && !excludeFlag;
ok, will redo with react-router in a separate PR

2019-04-25 14:06 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    return includeFlag && !excludeFlag;
@christianvogt Applied lint, prettier and changed file names to PascalCase

2019-04-25 21:19 UTC, christianvogt commented
Did a run through and everything seems to be working. Good job @abhinandan13jan 
As you work on unit tests, look to improve the typings as well to ensure all react component props are typed and all function parameters and return values are also typed. When we improve our linting rules it'll be easier to catch what's missing.

2019-04-25 21:22 UTC, christianvogt approved these changes

2019-04-25 21:22 UTC, merged