Added Gorkem's labelling strategy to source-to-image flow along with refactoring
talamer/console pull request #45
Opened 2019-04-25 21:44 UTC by rohitkrai03

Related to https://jira.coreos.com/browse/ODC-431

This PR - 
- Adds a new component `AppDropdown` which gets all relevant resources in a namespace and aggregates `part-of` label for application name and populate the dropdown. 
- Adds a generic `LabelDropdown` component which can take a list of resources and `labelSelector` and aggregates all the unique labels and populates the dropdown list.
- Updates the generic `Dropdown` component to take a new prop `actionItem`. This prop defines a new row for any type of action. If the user clicks on the action row then the parent component gets the `actionKey` in `onChange` callback.
- Updates the source-to-image component form to add a new input field for `Application Name` based on the action from `AppDropdown` component. If the user clicks on `Create New Application` this new input field is shown.
- Copied `source-to-image.tsx` to `devconsole` directory and initial refactoring. 
- Changed the reference in the route for `/catalog/source-to-image`.

Things left to do - 
- Add tests for new component.
- Move creation of resources logic out so that it can be shared or swapped easily.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6041994/56770294-35cd8d00-67d1-11e9-86ee-662ae0b5c30e.gif)

2019-04-25 22:22 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +    },
I think we can use just the `Component` CRD for this check.

2019-04-26 11:17 UTC, divyanshiGupta requested changes

2019-04-26 11:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/source-to-image/ImageStreamInfo.tsx
> +  tag: any;
Can you add a type for this?

2019-04-26 11:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/source-to-image/SourceToImage.tsx
> +
Is this space intentional?

2019-04-26 11:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/source-to-image/SourceToImage.tsx
> +                .
remove the . ?

2019-04-26 11:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/source-to-image/SourceToImage.tsx
> +  error?: any;
can you add a type here?

2019-04-26 11:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +const portsFromSpec = (portSpec: any): ContainerPort[] => {
type?

2019-04-26 11:17 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +export const getPorts = (imageStreamImage: any): ContainerPort[] => {
type?

2019-04-29 14:53 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +    },
Using just `Component` CRD will work only for Git Import Flow for now since `Component` CR is only created through that flow. But right now we have to support both Source to Image and Git import flow.

2019-04-29 14:55 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/source-to-image/SourceToImage.tsx
> +                .
Thats a full stop for the line.

2019-04-29 15:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/source-to-image/SourceToImage.tsx
> +
Yes it is. I like to separate my absolute and relative imports.

2019-04-29 16:58 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/SourceToImage.tsx
> +          <BuildSource preselectedNamespace={preselectedNamespace} {...props} />
What is `props` ? Missing type.

2019-04-29 16:58 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +    },
Got it. But then do we really need to look at all the rest? Why not just `Deployment` and `DeploymentConfig`?

2019-04-29 16:58 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/AppNameSelector.tsx
> +  onChange?: (arg0: string, arg1: string) => void;
Better for names `arg0` and `arg1`.

2019-04-29 16:58 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/AppNameSelector.tsx
> +          <HelpBlock>Names the application</HelpBlock>
Missing period to be consistent with other help text.

2019-04-29 16:58 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/AppNameSelector.tsx
> +            id="app-name"
Why is this ID here?

2019-04-29 16:58 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  };
Shouldn't you be initializing your state in the same way you do for `componentWillReceiveProps` for the first render?

2019-04-29 17:03 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +    },
Yeah i was thinking of the same thing. Keeping just `DeploymentConfigs` will work fine as well and make it much faster. We can add `Component` to the list later on.

2019-04-29 18:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/pages/SourceToImage.tsx
> +          <BuildSource preselectedNamespace={preselectedNamespace} {...props} />
Fixed.

2019-04-29 18:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppNameSelector.tsx
> +  onChange?: (arg0: string, arg1: string) => void;
Done

2019-04-29 18:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppNameSelector.tsx
> +          <HelpBlock>Names the application</HelpBlock>
Done

2019-04-29 18:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppNameSelector.tsx
> +            id="app-name"
Removed. Just used patternfly 3 props.

2019-04-29 18:10 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  };
Its almost same except i am checking if the loaded property has changed from `false` -> `true`, then stop showing `<Loading />` and start showing the placeholder as title.

2019-04-29 18:11 UTC, rohitkrai03 commented
@christianvogt Updated PR based on review comments

2019-04-29 21:07 UTC, christianvogt commented
* Clicking the `Create New Application` drop down item shows the new input form field. Subsequently clicking on `Create New Application` causes the dropdown item to become blank.
* I already have deployments with a `part-of` label but the applications drop down is empty.

2019-04-29 21:09 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +  ];
Need to also include `Deployment`

2019-04-29 21:34 UTC, christianvogt approved these changes
@rohitkrai03 tested locally and it's functioning fine. Take a look at the last minor comments.

2019-04-30 08:18 UTC, vikram-raj approved these changes
LGTM

2019-04-30 09:24 UTC, divyanshiGupta approved these changes

2019-04-30 10:24 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +  ];
Added.

2019-04-30 10:26 UTC, rohitkrai03 commented
@christianvogt The thing with clicking on already selected item is a bug with `Dropdown` component from console that i am using. I can look at that in another PR.

2019-04-30 10:29 UTC, merged