Topology resource Detail page
talamer/console pull request #50
Opened 2019-04-29 07:37 UTC by sahil143

story: https://jira.coreos.com/browse/ODC-425

![Screenshot from 2019-04-29 13-05-54](https://user-images.githubusercontent.com/9278015/56881911-9124a700-6a7f-11e9-8047-34bfcfcc8dc1.png)

2019-04-29 08:33 UTC, vikram-raj commented on frontend/public/extend/devconsole/components/topology/Topology.tsx
> +      <>
What is this empty tag for?

2019-04-29 08:37 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Topology.tsx
> +      <>
`React.Fragment`

2019-04-29 08:47 UTC, divyanshiGupta submitted a review, later dismissed

2019-04-29 08:47 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/topology/__tests__/TopologySideBar.spec.tsx
> +  xit('clicking on close button should call the onClose callback function', () => {
why is this test disabled?

2019-04-29 09:04 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/__tests__/TopologySideBar.spec.tsx
> +  xit('clicking on close button should call the onClose callback function', () => {
fixed!!

2019-04-29 09:15 UTC, rohitkrai03 requested changes

2019-04-29 09:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/topology/Topology.tsx
> +      <>
It better and more verbose to just write `<React.Fragment>`. More readable code.

2019-04-29 09:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/topology/Topology.tsx
> +        {this.state.selected && (
Better use a ternary operator here like
```suggestion
        { this.state.selected ? <TopologySidebar /> : null }
```

2019-04-29 09:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.scss
> +.modal.odc-topology-sidebar__overlay {
You wouldn't need this override if sidebar was a child of Graph.

2019-04-29 09:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/topology/Topology.tsx
> +          {this.renderToolbar}
Why not add the `<TopologySidebar>` as children of `<Graph/>`. that way you wouldn't have to override position values for it.

2019-04-29 09:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.tsx
> +class TopologySideBar extends React.Component<TopologySideBarProps> {
You can make this a functional component since it doesn't need a state or lifecycle methods.

2019-04-29 10:15 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.scss
> +.modal.odc-topology-sidebar__overlay {
Yes, we would need this override because its overriding the height of the model in patternfly. It doesn't depend on the Graph component. TopologySideBar should not be part of the Graph component because we have reserved child of Graph for GraphApi's example zoomIn, ZoomOut etc.

2019-04-29 10:19 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Topology.tsx
> +      <>
fixed in https://github.com/talamer/console/pull/50/commits/0bfa567f5acfde6f42c51e2301f17f5358aa4f2b

2019-04-29 10:19 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/Topology.tsx
> +        {this.state.selected && (
fixed in https://github.com/talamer/console/pull/50/commits/0bfa567f5acfde6f42c51e2301f17f5358aa4f2b

2019-04-29 10:20 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.tsx
> +class TopologySideBar extends React.Component<TopologySideBarProps> {
fixed in 0bfa567

2019-04-29 14:29 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.tsx
> +  };
This should be generic so that when we display different nodes on the topology we don't have to add more logic here.
Why not just consume the resources from the data model didectly.?

2019-04-29 14:29 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.tsx
> +  );
You do not need a fragment here.

2019-04-29 14:29 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.scss
> +    }
Is there not an existing button style that we can use already? We shouldn't have to style our own primitive button.

2019-04-29 14:29 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.scss
> +.modal.odc-topology-sidebar__overlay {
Nothing wrong with being a child of the graph. But if it doesn't but is anything then made out.

We should find a solution that does not require calculating such a value though because the height changes with responsive layouts in which case the top value need to be adjusted.

2019-04-29 14:29 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/__tests__/TopologySideBar.spec.tsx
> +  let wrapper: ShallowWrapper<TopologySideBarProps>;
No need for this declaration to be here. Move it to a const inside the test function that uses it.

2019-04-29 14:41 UTC, christianvogt commented
The sidebar also doesn't push the content out which means it can cover up the selected node.

2019-04-29 14:47 UTC, christianvogt commented
The following warning is logged when switching to the resources tab:
```
Warning: Each child in an array or iterator should have a unique "key" prop.
```

2019-04-30 02:40 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.tsx
> +  };
We can't consume the data model directly because ResourceOverviewPage takes data in a specific format.

2019-04-30 02:51 UTC, sahil143 commented
> The sidebar also doesn't push the content out which means it can cover up the selected node.
![image](https://user-images.githubusercontent.com/9278015/56938646-c2a17f00-6b20-11e9-968d-91b30771ff12.png)
This design image shows that the node is overlapped by side panel. Do we want to push the content out?

2019-04-30 04:02 UTC, christianvogt commented
I'm ok for now with it not pushing. We can discuss with UX later.

2019-04-30 04:10 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.tsx
> +  };
I just looked at the overview page prop types. I see what you mean now. Thanks!

2019-04-30 06:59 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.scss
> +.modal.odc-topology-sidebar__overlay {
We can keep it anywhere but its position is absolute and patternfly sets the top 76px because the main header height is 76px. We wanted the side-bar to open below secondary toolbar that's why I added secondary toolbar height to top. For responsive layout, I'm using a media query to set the top. Any other suggestions?

2019-04-30 07:04 UTC, sahil143 commented
> Warning: Each child in an array or iterator should have a unique "key" prop.

@christianvogt I'm not getting this warning.

2019-04-30 07:08 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.tsx
> +  );
fixed in https://github.com/talamer/console/pull/50/commits/8fa24c45ab6d69d9faf587b987d621f31ed07b47

2019-04-30 07:09 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/__tests__/TopologySideBar.spec.tsx
> +  let wrapper: ShallowWrapper<TopologySideBarProps>;
fixed in 8fa24c4

2019-04-30 07:33 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/TopologySideBar.scss
> +    }
There are no existing styles on the Button that's why I added padding to close button.

2019-04-30 10:17 UTC, sahil143 commented
@christianvogt @vikram-raj I talked with @karthikjeeyar about why metadata object is coming empty in some cases and we decided to add a temporary check to avoid the warning https://github.com/talamer/console/pull/50/files#diff-921e3963928899d0782d0476d9ad3a15R43

2019-04-30 10:27 UTC, rohitkrai03 approved these changes
LGTM

2019-04-30 10:32 UTC, merged