feat(devconsole_fflag): add feature flag for dev console
talamer/console pull request #6
Opened 2019-02-21 15:37 UTC by karthikjeeyar

Added feature flag
Added the feature flag to dev-console homepage component

2019-02-22 18:22 UTC, christianvogt requested changes

2019-02-22 18:22 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Home.tsx
> +const HomePage = connectToFlags(FLAGS.SHOW_DEV_CONSOLE)(HomePage_);
Just `export default` this line and then you can have only a single component named `HomePage` by renaming `HomePage_`.

2019-02-22 18:22 UTC, christianvogt commented on frontend/public/features.ts
> +    if(process.env.NODE_ENV === 'development') {
We need a separate flag that can be set from our package scripts. Once we can contribute directly to OS console we need to keep dev console off for the OS console folks unless specifically wanting to run with dev console enabled (even in development mode).

2019-02-22 18:22 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Home.tsx
> +  if (!props.flags[FLAGS.SHOW_DEV_CONSOLE]) {
I don't think this is the right place to check if `SHOW_DEV_CONSOLE` is enabled. We should probably not even enable the routes or the perspective itself rather than having each individual part of the app check this.

We can do the individual checks when it comes to features based on CRDs.

2019-02-25 08:50 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/pages/Home.tsx
> +  if (!props.flags[FLAGS.SHOW_DEV_CONSOLE]) {
@christianvogt  Got it. I will remove these checks from here and add it in dev console routes.

2019-02-25 13:16 UTC, rohitkrai03 requested changes

2019-02-25 13:16 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/pages/Home.tsx
> +  return <div>
The outer `<div>` is redundant here. You can use parentheses to return multi line JSX markup like
```
return (
  <div>Something</div>
)
```

2019-02-26 17:16 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Home.tsx
> +  if (!props.flags[FLAGS.SHOW_DEV_CONSOLE]) {
Are you still making these changes?

2019-02-27 10:27 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/pages/Home.tsx
> +  if (!props.flags[FLAGS.SHOW_DEV_CONSOLE]) {
@christianvogt  removed the flag from component level

2019-02-27 10:30 UTC, karthikjeeyar commented on frontend/public/features.ts
> +    if(process.env.NODE_ENV === 'development') {
Added an additional webpack configuration to extend the base config, to enable/disable the dev console work.

2019-03-01 04:13 UTC, christianvogt requested changes
Looks good. Minor comments on formatting using prettier.

2019-03-01 04:13 UTC, christianvogt commented on frontend/webpack.devconsole.config.ts
> +import * as webpack from 'webpack';
Please format this file. If you use vscode and still have prettier installed, simply `cmd + p` `> format document`.

2019-03-01 04:13 UTC, christianvogt commented on frontend/public/features.ts
> +  const detectDevConsole = dispatch => {
You can simplify this to:
```
const detectDevConsole = dispatch => {
  const showDevConsole = process.env.DEVCONSOLE_ENABLED && process.env.NODE_ENV === 'development';
  setFlag(dispatch, FLAGS.SHOW_DEV_CONSOLE, showDevConsole);
}
```

2019-03-01 04:13 UTC, christianvogt commented on frontend/public/extend/devconsole/pages/Home.tsx
> +      DevOps console is an internal feature and enabled only in development.
Missing white space. Use prettier to format all of our new files.

2019-03-01 07:37 UTC, karthikjeeyar commented on frontend/public/extend/devconsole/pages/Home.tsx
> +      DevOps console is an internal feature and enabled only in development.
@christianvogt  Used prettier to format all new files

2019-03-01 16:46 UTC, christianvogt requested changes

2019-03-01 16:46 UTC, christianvogt commented on frontend/public/features.ts
> +    const devconsole_enabled = !!((process.env.DEVCONSOLE_ENABLED || false) && process.env.NODE_ENV === 'development');
`|| false` is not needed.

2019-03-01 16:46 UTC, christianvogt commented on frontend/webpack.devconsole.config.ts
> +};
I guess your default prettier setup conflicts with the eslint rules in the project.

Please fix all your eslint errors in this file and others that you've changed.

2019-03-01 16:48 UTC, christianvogt commented on frontend/webpack.devconsole.config.ts
> +};
Note that there are some `no-undef` errors related to typescript. The OS console team has suppressed these. We can do the same until we fix their linter.

2019-03-01 20:05 UTC, karthikjeeyar commented on frontend/public/features.ts
> +    const devconsole_enabled = !!((process.env.DEVCONSOLE_ENABLED || false) && process.env.NODE_ENV === 'development');
we will use other scripts like `yarn dev`, where devconsole_enabled flag will not be available from env.  I have added it to handle such a scenario

2019-03-01 20:24 UTC, christianvogt commented on frontend/public/features.ts
> +    const devconsole_enabled = !!((process.env.DEVCONSOLE_ENABLED || false) && process.env.NODE_ENV === 'development');
But the coercion with `!!` makes the `|| false` unnecessary is all I was getting at.
`!!(undefined || false) === false` just like `!!undefined === false`

2019-03-01 21:25 UTC, christianvogt approved these changes

2019-03-01 21:31 UTC, rohitkrai03 approved these changes
LGTM

2019-03-01 21:43 UTC, merged