fix(dev-routes): disable shared dev routes when devconsole is disabled
talamer/console pull request #63
Opened 2019-05-01 22:08 UTC by karthikjeeyar

Fixes:
https://jira.coreos.com/browse/ODC-546

1. Page content area should display 404 because dev console is not enabled.
2. Does not load the 404 content until both console and dev-console feature flags are resolved.

2019-05-02 03:36 UTC, christianvogt commented on frontend/public/components/app.jsx
> +    return <Redirect to='/404'/>;
We don't want to redirect and update the url to `/404`.

2019-05-02 03:37 UTC, christianvogt commented on frontend/public/components/app.jsx
> +  }
This causes a floating loading indicator to be displayed in the main content area all the while other content around it is loading.

2019-05-02 10:09 UTC, karthikjeeyar commented on frontend/public/components/app.jsx
> +    return <Redirect to='/404'/>;
I changed the logic to handle the page not found error.

2019-05-02 10:10 UTC, karthikjeeyar commented on frontend/public/components/app.jsx
> +  }
removed using this redirect component altogether.

2019-05-02 11:11 UTC, rohitkrai03 requested changes

2019-05-02 11:11 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +      return lastViewedPerspective && flags[FLAGS.SHOW_DEV_CONSOLE] && lastViewedPerspective !== 'admin' ? (
This logic was generic to handle any perspective that comes in future. Now it is specific to `dev` only. I would rather have a generic solution that works with any perspective.

2019-05-02 11:11 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +    if(flags && !flagPending(FLAGS.SHOW_DEV_CONSOLE) && flags.SHOW_DEV_CONSOLE && activePerspective === 'dev') {
Same as above. Now this logic won't work for any perspective except `dev`.

2019-05-02 11:11 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +    if(flags && !flagPending(FLAGS.SHOW_DEV_CONSOLE) && flags.SHOW_DEV_CONSOLE && activePerspective === 'dev') {
I think we can have a simple function that takes a perspective as a parameter and determines using the flags if that perspective is enabled or not. Based on that we can prepend or not prepend the URLs or the redirects above. We can use a `PerspectiveToFlagMap` which store the corresponding flag for all the perspectives.

2019-05-02 12:42 UTC, karthikjeeyar commented on frontend/public/components/app.jsx
> +    if(flags && !flagPending(FLAGS.SHOW_DEV_CONSOLE) && flags.SHOW_DEV_CONSOLE && activePerspective === 'dev') {
added a perspective map to support other perspectives in future.

2019-05-02 13:45 UTC, rohitkrai03 requested changes

2019-05-02 13:45 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +    if(activePerspective !== 'admin' && flags && !flagPending(activePerspectiveFlag) && activePerspectiveFlag) {
You don't need to add the logic of not adding prefix if perspective is `admin` because that is already there in `pathWithPerspective` implementation.

2019-05-02 13:45 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +    this.perspectiveMap = {
Name it `perspectiveFlagMap` to be more clear. This can actually be an enum instead of a state variable of the component.

2019-05-02 17:36 UTC, karthikjeeyar commented on frontend/public/components/app.jsx
> +    this.perspectiveMap = {
fixed it

2019-05-02 17:39 UTC, rohitkrai03 approved these changes
LGTM

2019-05-02 21:52 UTC, christianvogt reviewed
Please fix lint errors.
As I went through this PR I started to think we should could tackle routing in a different way. We should probably have our own page component that is rendered at the `/dev` route. Then this component owns our own `Switch` and handles waiting for flags and manages our routes. If all fails it renders the `ErrorPage404`

2019-05-02 21:52 UTC, christianvogt commented on frontend/public/components/app.jsx
> +   }
We shouldn't enter this if condition unless we are trying to reach the dev perspective.

2019-05-02 21:52 UTC, christianvogt commented on frontend/public/components/app.jsx
> +    if(flags && !flagPending(activePerspectiveFlag) && activePerspectiveFlag) {
These two checks are the same: `!flagPending(activePerspectiveFlag) && activePerspectiveFlag`. You only need to check `flagPending`

2019-05-02 21:52 UTC, christianvogt commented on frontend/public/components/app.jsx
> +    if (flagPending(openshiftFlag) && flagPending(flags[FLAGS.SHOW_DEV_CONSOLE])) {
We should only perform the `SHOW_DEV_CONSOLE` flag check if we're trying to reach the dev perspective. Otherwise we're holding the user up for no reason.

2019-05-03 03:11 UTC, sbose78 commented
test

2019-05-03 06:49 UTC, karthikjeeyar commented on frontend/public/components/app.jsx
> +   }
added perspective check

2019-05-03 06:54 UTC, karthikjeeyar commented on frontend/public/components/app.jsx
> +    if(flags && !flagPending(activePerspectiveFlag) && activePerspectiveFlag) {
These two checks are different. `flagPending` is returning if the value is other than undefined whereas `activePerspectiveFlag` checks for its value itself. I have renamed the `activePerspectiveFlag` to `activePerspectiveFlagEnabled` to be more clear

2019-05-03 14:11 UTC, christianvogt approved these changes

2019-05-03 14:11 UTC, merged