Fixes: App flickers admin perspective while devconsole check is pending[ODC - 467]
talamer/console pull request #71
Opened 2019-05-03 11:49 UTC by sahil143

Bug: https://jira.coreos.com/browse/ODC-467

2019-05-03 14:20 UTC, christianvogt commented
@sahil143 please rebase.

2019-05-03 14:33 UTC, christianvogt commented on frontend/public/components/app.jsx
> +                  { (devconsoleEnabled || this.props.activePerspective === 'dev') && devConsoleRoutes.map(r => <Route key={r.path} {...r} />)}
These routes can only be added if devconsole is enabled.
I think the original is correct.
Rebase on top of @karthikjeeyar's recent change and try again.

2019-05-06 09:54 UTC, divyanshiGupta commented on frontend/public/components/app.jsx
> +      return null;
@sahil143 the new behavior is to show the `DevConsoleNav` if the `activePerspective` is `dev` and flag is pending? Because currently we show the admin console nav.

2019-05-06 11:38 UTC, sahil143 commented on frontend/public/components/app.jsx
> +      return null;
I just added a check if the active perspective is dev then we show nothing on side panel until the devconsole flag is enabled.

2019-05-06 11:41 UTC, sahil143 commented on frontend/public/components/app.jsx
> +      return null;
can you provide the steps to reproduce this 404?

2019-05-06 12:00 UTC, divyanshiGupta commented on frontend/public/components/app.jsx
> +      return null;
it is showing 404 because I manually set the flag to false to test the behavior.

2019-05-06 12:01 UTC, divyanshiGupta commented on frontend/public/components/app.jsx
> +      return null;
> I just added a check if the active perspective is dev then we show nothing on side panel until the devconsole flag is enabled.

Yes, I think that makes more sense.

2019-05-06 12:20 UTC, sahil143 commented on frontend/public/components/app.jsx
> +      return null;
Fixed! This should be the correct behavior when the devconsole flag is not enabled
![Screenshot from 2019-05-06 17-48-41](https://user-images.githubusercontent.com/9278015/57224510-52669200-7027-11e9-847b-432143f8df80.png)

2019-05-06 12:21 UTC, divyanshiGupta commented on frontend/public/components/app.jsx
> +      return null;
Yes, that seems right. Thanks

2019-05-06 12:32 UTC, divyanshiGupta approved these changes

2019-05-06 16:02 UTC, christianvogt commented on frontend/public/components/app.jsx
> +      return null;
@sahil143 this doesn't look right to me. If dev console isn't enabled, we should have the `administrator` navigation showing on the left.

2019-05-06 16:11 UTC, sahil143 commented on frontend/public/components/app.jsx
> +      return null;
Why would we show admin nav on a `/dev` route?

2019-05-06 17:37 UTC, christianvogt commented on frontend/public/components/app.jsx
> +      return null;
Same reason we show admin console on a `/foobar` route. IMO `/dev` is only valid if the dev console is available. Otherwise everything we display is within the context of the admin perspective.

2019-05-06 18:25 UTC, sbose78 commented
build and deploy

2019-05-06 18:25 UTC, sbose78 commented
[ Bot ] Your build is progress : https://console-openshift-console.apps.rgarg11.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-71-openshift-console.apps.rgarg11.devcluster.openshift.com

2019-05-07 05:38 UTC, sahil143 commented on frontend/public/components/app.jsx
> +      return null;
okay, Then we show admin on `/dev` route but show the 404 as content?

2019-05-07 11:39 UTC, christianvogt commented on frontend/public/components/app.jsx
> +      return null;
Yes. The dev route should be treated just the same as any other unknown route.

2019-05-07 12:58 UTC, sahil143 commented on frontend/public/components/app.jsx
> +      return null;
@christianvogt Added a fix for this. This is a bit tricky because whenever we go to route `/dev` it sets the activePerspective to `dev` and most of our checks depend on activePerspective. Please review again. https://github.com/talamer/console/pull/71/commits/41eefdd81ee378ab71b6756dcddbf5460d450983

2019-05-07 13:06 UTC, rohitkrai03 requested changes

2019-05-07 13:06 UTC, rohitkrai03 commented on frontend/public/components/app.jsx
> +      (this.props.activePerspective === 'dev' &&
This seems too complicated and specific to dev perspective. It will get even worse if some other perspective comes into picture in future. We should look at a generic solution for this.

2019-05-07 13:50 UTC, christianvogt commented on frontend/public/components/app.jsx
> +        !flagPending(this.props.flags[FLAGS.OPENSHIFT]))
If perspective isn't `dev` then we don't need to check for `OPENSHIFT`. It is the default and should always be shown as the fallback.

2019-05-07 13:50 UTC, christianvogt commented on frontend/public/components/app.jsx
> +  connectToFlags(FLAGS.OPENSHIFT, FLAGS.SHOW_DEV_CONSOLE)(App)
We don't need to wait on the `OPENSHIFT` flag.

2019-05-07 13:50 UTC, christianvogt commented on frontend/public/components/app.jsx
> +      (this.props.activePerspective === 'dev' &&
It would be good to move the logic of which nav to show to a separate component.
`Navigation` delegates to `DevConsoleNav` and / or `ConsoleNav`.

2019-05-07 14:14 UTC, sahil143 commented on frontend/public/components/app.jsx
> +      (this.props.activePerspective === 'dev' &&
made the logic more generic to support all perspectives https://github.com/talamer/console/pull/71/commits/736acbaa43eb7df9d9c6654d56629b92265f04d4.
@christianvogt working on making a sperate component for Navigation

2019-05-07 19:14 UTC, christianvogt commented on frontend/public/components/app.jsx
> +      return null;
Maybe we can revisit this issues this causes in another PR.
cc @rohitkrai03 
Essentially the `activePerspective` should only contain a value which is valid. And validity depends on a feature flag async call. This could get complicated and will require some more thought.

2019-05-08 08:38 UTC, sahil143 commented on frontend/public/components/app.jsx
> +  connectToFlags(FLAGS.OPENSHIFT, FLAGS.SHOW_DEV_CONSOLE)(App)
Fixed in https://github.com/talamer/console/pull/71/commits/19fa596beefe4d5d674dd6026decdfb054891edd

2019-05-08 08:38 UTC, sahil143 commented on frontend/public/components/app.jsx
> +        !flagPending(this.props.flags[FLAGS.OPENSHIFT]))
Fixed! Made the logic more generic https://github.com/talamer/console/pull/71/commits/736acbaa43eb7df9d9c6654d56629b92265f04d4

2019-05-08 17:23 UTC, christianvogt commented on frontend/public/components/app.jsx
> +    this.showActivePerspectiveNav = this.showActivePerspectiveNav.bind(this);
This is unnecessary because you are not passing these functions by reference.

2019-05-08 17:23 UTC, christianvogt commented on frontend/public/components/app.jsx
> +    if (this.props.activePerspective === 'admin' || this.showAdminNav()) {
move `this.props.activePerspective === 'admin'` to your `showAdminNav` function.

2019-05-09 05:00 UTC, sahil143 commented on frontend/public/components/app.jsx
> +    this.showActivePerspectiveNav = this.showActivePerspectiveNav.bind(this);
fixed in https://github.com/talamer/console/pull/71/commits/24d3c2902e4dac457e8f1e928c9963f25d76d216

2019-05-09 05:00 UTC, sahil143 commented on frontend/public/components/app.jsx
> +    if (this.props.activePerspective === 'admin' || this.showAdminNav()) {
fixed in https://github.com/talamer/console/pull/71/commits/24d3c2902e4dac457e8f1e928c9963f25d76d216

2019-05-09 16:02 UTC, christianvogt approved these changes

2019-05-09 16:05 UTC, rohitkrai03 approved these changes
LGTM

2019-05-09 16:10 UTC, merged