[WIP]feat(codebases):Add codebases section to devOps console
talamer/console pull request #8
Opened 2019-02-22 11:49 UTC by abhinandan13jan

Adding Codebase section to Devops console

2019-02-22 21:01 UTC, christianvogt commented
Is this a work in progress or is it really ready for review?
There are some fundamental reactjs errors. Please setup a meeting with me to further discuss.

2019-02-25 10:15 UTC, rohitkrai03 requested changes

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/components/nav.jsx
> +          <HrefLink href="/devconsole/codebases" name="Codebases" activePath="/devconsole/codebases/" />
@abhinandan13jan You don't need to add this now since we already have routes setup for dev console.

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/components/utils/link.jsx
> +export const namespacedPrefixes = ['/search', '/status', '/k8s', '/overview', '/catalog', '/provisionedservices', '/operators', '/operatormanagement', '/devconsole/codebases'];
This is not needed as well.

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/DevConsoleRoutes.tsx
> +// Ensure a *const* function wrapper for each namespaced Component so that react router doesn't recreate them
Please rebase your PR with latest changes on master-next branch. And why do we need this memoization here?

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/_codebase.scss
> +.codeBaseContainer {
Class names should follow BEM naming conventions - https://css-tricks.com/bem-101/. You should also prefix classnames with `devops-`

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/_codebase.scss
> +.codeBaseContainer {
The filename should be same as component with just .scss extension. `Codebase.scss`

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.tsx
> +import * as React from 'react';
Filename should follow react component naming conventions. 
```suggestion
CodebaseList.tsx
```

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.tsx
> +export class CodeBaseList extends React.Component<codebaseListProps> {
This could be a Stateless Functional Component `React.SFC`.

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.tsx
> +  display:Object = <h3 className = 'noCodebasesFound'> No codebases found. </h3>;
Why is the type here `Object`?

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.tsx
> +  updateDisplay = () => {
Why is there a functional component inside a class based component?

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.tsx
> +            return (
Rather than creating your own list component like this you should be using already created components and patterns used in console.

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/codebases/codebaselist.tsx
> +      <React.Fragment>
Why are you using `<React.Fragment>` when there is only one element to render?

2019-02-25 10:15 UTC, rohitkrai03 commented on frontend/public/style.scss
> +@import "extend/devconsole/components/codebases/codebase";
Do not add component specific stylesheet in console code. Use direct imports inside component.

2019-02-25 20:01 UTC, christianvogt commented
This page should be built using the pattern for resource based list pages already established by OpenShift console. Please look at any of the existing pages and how they utilize the `ListPage` component.

2019-03-04 07:50 UTC, abhinandan13jan commented
created new PR
https://github.com/talamer/console/pull/11

2019-03-04 07:50 UTC, closed without merging