feat(pipelines): Feature flag pipelines and runs
talamer/console pull request #81
Opened 2019-05-07 10:35 UTC by abhinandan13jan

@rohitkrai03 @divyanshiGupta @karthikjeeyar This is for feature flagging pipelines. 
To test, please do the following.
1. Go to public/extend/devconsole/__mocks__/pipelines on terminal
2. Run command oc delete -f base.yaml
3. Check devconsolenav will be missing the 'Pipelines' nav item.
![Screenshot from 2019-05-07 15-46-13](https://user-images.githubusercontent.com/24852534/57292956-e6e0fb00-70e0-11e9-9e89-8f6c7b5ad236.png)
4. Run script
 chmod +x install_pipeline_mocks.sh
./install_pipeline_mocks.sh
5. Check that the 'Pipeline' nav item is visible.
![Screenshot from 2019-05-07 15-46-39](https://user-images.githubusercontent.com/24852534/57292941-ddf02980-70e0-11e9-868d-93a53a18fe9e.png)

2019-05-07 12:37 UTC, rohitkrai03 requested changes

2019-05-07 12:37 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ConditionalResourceLinks.tsx
> +export const ConditionalResourceNSLink = ({
This is not an `HOC` as discussed. This is just a wrapper component that wraps `ResourceNSLink`. What if i want to flag a nave item that is using `HrefLink`? I'll have to create one more component like this which defeats the whole purpose of creating an HOC that is reusable.

2019-05-07 12:43 UTC, divyanshiGupta requested changes

2019-05-07 12:43 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/ConditionalResourceLinks.tsx
> +export const ConditionalResourceNSLink = ({
@abhinandan13jan I agree with @rohitkrai03. This component should be implemented in a way that you just need to send array of the flags you need to check for and the component should do that for you, it should be connected to the store to access the flags and if the desired flags are true should return the link item. In that way it can be used anywhere.

2019-05-07 14:23 UTC, abhinandan13jan commented
@rohitkrai03 @divyanshiGupta I agree that having one single component to render both ResourceLinks & HRefLinks seems better, I will look for that.
@divyanshiGupta However connecting to the store per node in the NavList seems redundant while the parent component is already connected to the store and can simply pass on a prop to the child. In any case, react will handle the re-render with minimal possible changes.

2019-05-07 16:03 UTC, sbose78 commented
build and deploy

2019-05-07 16:03 UTC, sbose78 commented
[ Bot ] Your build is progress : https://console-openshift-console.apps.rgarg11.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-81-openshift-console.apps.rgarg11.devcluster.openshift.com

2019-05-07 16:13 UTC, sbose78 commented
build and deploy

2019-05-07 16:13 UTC, sbose78 commented
[ Bot ] Your build is progress : https://console-openshift-console.apps.rgarg11.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-81-openshift-console.apps.rgarg11.devcluster.openshift.com

2019-05-08 05:46 UTC, sbose78 commented
build and deploy

2019-05-08 05:46 UTC, sbose78 commented
[ Bot ] Your build is progress : https://console-openshift-console.apps.rgarg11.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-81-openshift-console.apps.rgarg11.devcluster.openshift.com

2019-05-08 05:53 UTC, sbose78 commented
build and deploy

2019-05-08 05:53 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.tina1.devcluster.openshift.com//k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-81-openshift-console.apps.tina1.devcluster.openshift.com/

2019-05-08 08:30 UTC, abhinandan13jan commented
@rohitkrai03 @divyanshiGupta  Updated. Please review.

2019-05-08 08:44 UTC, divyanshiGupta requested changes

2019-05-08 08:44 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/ConditionalResourceLinks.tsx
> +export const ConditionalResource = ({
@abhinandan13jan this doesn't make sense to me. First of all its not an HOC and secondly if you dont want to create an HOC, instead of writing so much code just add this 
`{'<flags you want to check for>' && <ResourceLink />}` , if the desired flags are true your link will be shown.

2019-05-08 08:45 UTC, rohitkrai03 requested changes

2019-05-08 08:45 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ConditionalResourceLinks.tsx
> +export const ConditionalResource = ({
@abhinandan13jan This is again not an `HOC`. It's similar to `NavSection` that console already has implemented just instead of checking all the children components separately for their own flags you are checking for just one flag for one child component. Please take a look at - https://reactjs.org/docs/higher-order-components.html

2019-05-08 08:45 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +        <ConditionalResource
For every nav item we will have to now wrap it up in a wrapper called `ConditionalResource` which is unnecessary.

2019-05-08 08:46 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ConditionalResourceLinks.tsx
> +export const ConditionalResource = ({
Yes, for now i am okay with just having a function right there in this component which takes a required flag and return true or false which then is used to render a nav item. Even a simple conditional render is fine for now. We can take a look at improving the `DevConsoleNav` component to handle all the flagging if `HOC` implementation is complicating things now.

2019-05-08 09:01 UTC, rohitkrai03 commented
@abhinandan13jan 

> @divyanshiGupta However connecting to the store per node in the NavList seems redundant while the parent component is already connected to the store and can simply pass on a prop to the child. In any case, react will handle the re-render with minimal possible changes.

React doesn't handle all the re-render with minimal possible changes automatically. Take a look at this - https://thoughtbot.com/blog/react-rendering-misconception. If any of the props or state changes for a component all the child components are re-rendered unless you've implemented `componentShouldUpdate` properly. So, when the parent component is connected to store and is passing a value to some of its children, any change in the store value re-renders all of its children which is not needed. Sometimes its better to make that component smart and handle the connection to store to avoid such re-renders. And it turns out connected component that use `connect` from redux have a `shouldComponentUpdate` implemented which makes them better to use at leaf nodes.

Also, if we want to use this same `HOC` outside of dev console nav component we would need to connect it to the store again. 

This is a very good discussion thread of when to connect your components and when to let parent handle that for child component - https://github.com/elastic/kibana/issues/14547

2019-05-08 12:27 UTC, abhinandan13jan commented
@divyanshiGupta @rohitkrai03 Please check now :)

2019-05-08 13:35 UTC, abhinandan13jan commented
> @abhinandan13jan
> 
> > @divyanshiGupta However connecting to the store per node in the NavList seems redundant while the parent component is already connected to the store and can simply pass on a prop to the child. In any case, react will handle the re-render with minimal possible changes.
> 
> React doesn't handle all the re-render with minimal possible changes automatically. Take a look at this - https://thoughtbot.com/blog/react-rendering-misconception. If any of the props or state changes for a component all the child components are re-rendered unless you've implemented `componentShouldUpdate` properly. So, when the parent component is connected to store and is passing a value to some of its children, any change in the store value re-renders all of its children which is not needed. Sometimes its better to make that component smart and handle the connection to store to avoid such re-renders. And it turns out connected component that use `connect` from redux have a `shouldComponentUpdate` implemented which makes them better to use at leaf nodes.
> 
> Also, if we want to use this same `HOC` outside of dev console nav component we would need to connect it to the store again.
> 
> This is a very good discussion thread of when to connect your components and when to let parent handle that for child component - [elastic/kibana#14547](https://github.com/elastic/kibana/issues/14547)

I do not see that as a disadvantage, the component need not connect to the store itself even when used outside DevconsoleNav, it just needs to somehow avail the flag property which resides in the store and can be passed on by the parent. Are you really suggesting reconnecting to the store when the immediate container is already connected? 
In both cases, there will be equal number of re-renders if we subscribe to the entire store.flags and not an individual store.flag[""] which is not possible with a HOC for all navlinks.
In that case, should we not redo implementation for other children components like ResourceNSLinks to reconnect to the store instead of borrowing props from parents?
Anyway, I have implemented the conditional render using if-else, please review

2019-05-08 17:45 UTC, divyanshiGupta requested changes

2019-05-08 17:45 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +  flags: any;
Please add type here.

2019-05-08 17:45 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/__tests__/DevConsoleNav.spec.tsx
> +    flags:{},
add space between `:` and `{}`

2019-05-08 17:45 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +        {flags.get(FLAGS.SHOW_PIPELINE) ? (
You dont need to return `null` you can simply do this `flags.get(FLAGS.SHOW_PIPELINE) && <ResourceLink />`.

2019-05-09 07:49 UTC, abhinandan13jan commented
@divyanshiGupta Please check, I changed in those places :)

2019-05-09 09:54 UTC, rohitkrai03 commented
build and deploy

2019-05-09 11:41 UTC, divyanshiGupta approved these changes

2019-05-09 12:02 UTC, rohitkrai03 approved these changes
LGTM

2019-05-09 16:09 UTC, christianvogt commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    flags: state.FLAGS,
Use the `connectToFlags` for consistency with the rest of the code. Even though it isn't doing anything especially different and is just as inefficient in causing re-renders even though we're only interested in our own specific flag.

2019-05-10 07:56 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/DevConsoleNav.tsx
> +    flags: state.FLAGS,
@christianvogt Now using connectToFlag('SHOW_PIPELINE'). please approve

2019-05-10 15:51 UTC, christianvogt commented
@abhinandan13jan if you look at `features.ts` there is `const CRDs`. Shouldn't you be adding pipeline feature flags here as this is the list of CRD based features flags?

2019-05-11 08:35 UTC, abhinandan13jan commented
@christianvogt Added to const CRD and to feature unit test

2019-05-13 00:47 UTC, christianvogt commented
@abhinandan13jan do you still need `detectPipeline` if you are using the CRD feature flags?

2019-05-13 13:34 UTC, abhinandan13jan commented
> @abhinandan13jan do you still need `detectPipeline` if you are using the CRD feature flags?

@christianvogt No, wouldn't need it. updated.

2019-05-13 15:17 UTC, christianvogt approved these changes

2019-05-13 15:18 UTC, merged