Application switcher
talamer/console pull request #87
Opened 2019-05-12 20:41 UTC by divyanshiGupta

Story: https://jira.coreos.com/browse/ODC-435

This PR adds `ApplicationSwitcher` in the context bar

Also this PR fixes a bug in `dropdown.tsx`. So when an `item` is bookmarked it gets stored in the local storage in the array of bookmarked items and `dropdown.tsx` gets the array of bookmarks from local storage and appends these bookmarks to the list of `items` sent by parent to show the bookmarked `items` in the dropdown, but it introduces a bug wherein even if an `item` was bookmarked but is no more available in the list of `items` sent by parent it still shows in the dropdown list because of the above logic. Fixed this by checking if the respective `item` is available in `items` sent by parent.

![appswitcher](https://user-images.githubusercontent.com/20724543/57587547-29149d00-7524-11e9-80fe-c52a9ddb9e2b.gif)

2019-05-13 16:01 UTC, christianvogt reviewed
I'm getting errors trying to test this out.
I'll finish the review when I can properly run the changes.

```
Uncaught TypeError: _ui_ui_actions__WEBPACK_IMPORTED_MODULE_7__.UIActions.setActiveApplication is not a function
    at Object.onApplicationChange [as onChange] (namespace.jsx:290)
    at Object.onApplicationChange [as onChange] (ApplicationSwitcher.tsx:18)
    at LabelDropdown._this.onChange (LabelDropdown.tsx:121)
    at Dropdown.push../public/components/utils/dropdown.jsx.DropdownMixin.onClick_ (dropdown.jsx:52)
    at Dropdown._this.onClick (dropdown.jsx:128)
    at onClick (dropdown.jsx:115)
    at HTMLUnknownElement.callCallback (react-dom.development.js:104)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:142)
    at Object.invokeGuardedCallback (react-dom.development.js:191)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:205)
onApplicationChange @ namespace.jsx:290
onApplicationChange @ ApplicationSwitcher.tsx:18
LabelDropdown._this.onChange @ LabelDropdown.tsx:121
push../public/components/utils/dropdown.jsx.DropdownMixin.onClick_ @ dropdown.jsx:52
Dropdown._this.onClick @ dropdown.jsx:128
onClick @ dropdown.jsx:115
callCallback @ react-dom.development.js:104
```
 When selecting `all namespaces` the application switcher is stuck loading:
![image](https://user-images.githubusercontent.com/14068621/57636383-06f83a80-7577-11e9-996e-5b4e28985666.png)

2019-05-13 16:01 UTC, christianvogt commented on frontend/public/components/utils/dropdown.jsx
> +        <button aria-haspopup="true" onClick={this.toggle} onKeyDown={this.onKeyDown} type="button" className={classNames('btn', 'btn-dropdown', 'dropdown-toggle', buttonClassName ? buttonClassName :
Deconstruct `disabled` from `props` at the top of the `render` function.

2019-05-13 16:01 UTC, christianvogt commented on frontend/public/components/utils/dropdown.jsx
> +      if (!this.props.items[key]) {
Deconstruct `items` from `props` at the top of the `render` function.

2019-05-13 16:01 UTC, christianvogt commented on frontend/public/extend/devconsole/components/application-switcher/ApplicationSwitcher.tsx
> +  activeApplication: string;
Change `activeNamespace` and `activeApplication` to simply `namespace` and `application`.

2019-05-13 16:29 UTC, divyanshiGupta commented
> When selecting `all namespaces` the application switcher is stuck loading:
> ![image](https://user-images.githubusercontent.com/14068621/57636383-06f83a80-7577-11e9-996e-5b4e28985666.png)

Yes, because in `LabelDropdown` if resources are not loaded or not present `<LoadingInline />` is shown and hence when `all projects` is selected when there is no `lastViewed` application loading is shown because there are no resources.  I will change this to showing nothing when `all projetcs` is selected.

2019-05-13 16:32 UTC, divyanshiGupta commented
> I'm getting errors trying to test this out.
> I'll finish the review when I can properly run the changes.
> 
> ```
> Uncaught TypeError: _ui_ui_actions__WEBPACK_IMPORTED_MODULE_7__.UIActions.setActiveApplication is not a function
>     at Object.onApplicationChange [as onChange] (namespace.jsx:290)
>     at Object.onApplicationChange [as onChange] (ApplicationSwitcher.tsx:18)
>     at LabelDropdown._this.onChange (LabelDropdown.tsx:121)
>     at Dropdown.push../public/components/utils/dropdown.jsx.DropdownMixin.onClick_ (dropdown.jsx:52)
>     at Dropdown._this.onClick (dropdown.jsx:128)
>     at onClick (dropdown.jsx:115)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:104)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:142)
>     at Object.invokeGuardedCallback (react-dom.development.js:191)
>     at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:205)
> onApplicationChange @ namespace.jsx:290
> onApplicationChange @ ApplicationSwitcher.tsx:18
> LabelDropdown._this.onChange @ LabelDropdown.tsx:121
> push../public/components/utils/dropdown.jsx.DropdownMixin.onClick_ @ dropdown.jsx:52
> Dropdown._this.onClick @ dropdown.jsx:128
> onClick @ dropdown.jsx:115
> callCallback @ react-dom.development.js:104
> ```

Strange. I am not getting this error. Trying to figure out why this happened

2019-05-13 16:44 UTC, divyanshiGupta commented on frontend/public/components/utils/dropdown.jsx
> +      if (!this.props.items[key]) {
There is `items` in state as well so it is not possible to deconstruct `items` from props

2019-05-13 17:47 UTC, rohitkrai03 requested changes

2019-05-13 17:47 UTC, rohitkrai03 commented on frontend/public/components/namespace.jsx
> +    activeApplication: state.UI.get('activeApplication'),
You can create a selector in `ui-selectors.ts` file for this and use it.

2019-05-13 17:47 UTC, rohitkrai03 commented on frontend/public/ui/ui-actions.js
> +    if (application !== getActiveApplication()) {
Why do we need to check this here? It's okay to just override the value in localStorage. That way you don't need to have `getActiveApplication` which uses the global store.

2019-05-13 17:48 UTC, rohitkrai03 commented
@divyanshiGupta This is how application dropdown looks in git import form.
<img width="701" alt="Screenshot 2019-05-13 at 11 08 23 PM" src="https://user-images.githubusercontent.com/6041994/57642596-55d4bd00-75d5-11e9-998d-20e9517a6893.png">

I think you need to set `dropdownClassName="dropdown--full-width"`.

2019-05-13 17:52 UTC, rohitkrai03 requested changes

2019-05-13 17:52 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +    const allApplications = { name: 'all applications' };
Having this logic here makes this component specific to application label. This is more of generic component that can be used to aggregate any type of label from a list of resource. Maybe pass a prop from parent which sets the first item in the list as `All Application` or `All ${Whatever Label}`.

2019-05-13 18:25 UTC, divyanshiGupta commented
> @divyanshiGupta This is how application dropdown looks in git import form.
> 
> <img alt="Screenshot 2019-05-13 at 11 08 23 PM" width="701" src="https://user-images.githubusercontent.com/6041994/57642596-55d4bd00-75d5-11e9-998d-20e9517a6893.png">
> 
> I think you need to set `dropdownClassName="dropdown--full-width"`.

Fixed

2019-05-13 18:26 UTC, rohitkrai03 commented
> I'm getting errors trying to test this out.
> I'll finish the review when I can properly run the changes.
> 
> ```
> Uncaught TypeError: _ui_ui_actions__WEBPACK_IMPORTED_MODULE_7__.UIActions.setActiveApplication is not a function
>     at Object.onApplicationChange [as onChange] (namespace.jsx:290)
>     at Object.onApplicationChange [as onChange] (ApplicationSwitcher.tsx:18)
>     at LabelDropdown._this.onChange (LabelDropdown.tsx:121)
>     at Dropdown.push../public/components/utils/dropdown.jsx.DropdownMixin.onClick_ (dropdown.jsx:52)
>     at Dropdown._this.onClick (dropdown.jsx:128)
>     at onClick (dropdown.jsx:115)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:104)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:142)
>     at Object.invokeGuardedCallback (react-dom.development.js:191)
>     at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:205)
> onApplicationChange @ namespace.jsx:290
> onApplicationChange @ ApplicationSwitcher.tsx:18
> LabelDropdown._this.onChange @ LabelDropdown.tsx:121
> push../public/components/utils/dropdown.jsx.DropdownMixin.onClick_ @ dropdown.jsx:52
> Dropdown._this.onClick @ dropdown.jsx:128
> onClick @ dropdown.jsx:115
> callCallback @ react-dom.development.js:104
> ```
> 
I am not getting these errors. It runs fine for me.

2019-05-13 21:31 UTC, christianvogt commented
Another error when trying to use the type filter in the application drop down:
```
react-dom.development.js:244 Uncaught TypeError: Cannot read property 'name' of undefined
    at push../public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx.LabelDropdown.autocompleteFilter (LabelDropdown.tsx:58)
    at dropdown.jsx:219
    at pickBy.js:33
    at basePickBy (_basePickBy.js:23)
    at Module.pickBy (pickBy.js:32)
    at Dropdown.push../public/components/utils/dropdown.jsx.Dropdown.applyTextFilter_ (dropdown.jsx:219)
    at Dropdown._this.changeTextFilter (dropdown.jsx:157)
```

2019-05-13 21:38 UTC, christianvogt commented
The applications `favorite` doesn't do anything. Can we disable the feature?

2019-05-13 21:48 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +      title = <span className="btn-dropdown__item--placeholder">{actionItem.actionTitle}</span>;
Something going on here when I refresh the page when an application is selected, the italic name flashes.
![italic_flash](https://user-images.githubusercontent.com/14068621/57656697-28711a80-75a7-11e9-9b2c-c98273e7bd5d.gif)

2019-05-14 11:24 UTC, divyanshiGupta commented
> Another error when trying to use the type filter in the application drop down:
> 
> ```
> react-dom.development.js:244 Uncaught TypeError: Cannot read property 'name' of undefined
>     at push../public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx.LabelDropdown.autocompleteFilter (LabelDropdown.tsx:58)
>     at dropdown.jsx:219
>     at pickBy.js:33
>     at basePickBy (_basePickBy.js:23)
>     at Module.pickBy (pickBy.js:32)
>     at Dropdown.push../public/components/utils/dropdown.jsx.Dropdown.applyTextFilter_ (dropdown.jsx:219)
>     at Dropdown._this.changeTextFilter (dropdown.jsx:157)
> ```

Yes, it was a bug in `LabelDropdown.tsx`. The search is not working in import-from-git and source-to-image app-dropdowns as well in the master-next console. Fixed it now.

2019-05-14 11:26 UTC, divyanshiGupta commented
> The applications `favorite` doesn't do anything. Can we disable the feature?

Disabled. But I have kept the bookmarks feature, because it helps to show the applications on top of the list you want to view often.

2019-05-14 11:27 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +      title = <span className="btn-dropdown__item--placeholder">{actionItem.actionTitle}</span>;
Another bug in `dropdown.tsx`. They were adding placeholder class on all the titles. Fixed it.

2019-05-14 17:53 UTC, rohitkrai03 requested changes

2019-05-14 17:53 UTC, rohitkrai03 commented on frontend/public/components/namespace.jsx
> +          allApplicationsKey={ALL_APPLICATIONS_KEY}
I don't think you need to send these keys from here. `ApplicationSwitcher` can directly import it and use it as they are constants. That way you have less props going into `ApplicationSwitcher`

2019-05-14 17:53 UTC, rohitkrai03 commented on frontend/public/const.js
> +// Use a key for the "all" namespaces option that would be an invalid namespace name to avoid a potential clash
```suggestion
// Use a key for the "all" applications option that would be an invalid application name to avoid a potential clash
```

2019-05-14 17:53 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/application-switcher/ApplicationSwitcher.tsx
> +    key === props.allApplicationsKey ? props.onChange(key) : props.onChange(newApplication);
Its better to deconstruct your props at the top. Or better add it to function parameters.

2019-05-14 17:53 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +    if (this.props.allSelectorItem && !_.isEmpty(unsortedList)) {
Better to have this after you get `sortedList` because you would want `all application` showing at top of the list. Right now this could get changed after sorting.

2019-05-14 18:00 UTC, rohitkrai03 commented
build and deploy

2019-05-14 18:00 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.tkurian4.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-87-openshift-console.apps.tkurian4.devcluster.openshift.com

2019-05-14 18:08 UTC, christianvogt commented on frontend/public/ui/ui-actions.js
> +  LAST_APPLICATION_NAME_LOCAL_STORAGE_KEY,
This is no longer used.

2019-05-14 18:08 UTC, christianvogt commented on frontend/public/components/utils/dropdown.jsx
> +    const defaultTitle = React.isValidElement(props.title) ? props.title : <span className="btn-dropdown__item--placeholder">{props.title}</span>;
This was to fix the flash of the italic title right?
It's odd that this is the only place in the whole file that uses the `<span className="btn-dropdown__item--placeholder">`. Not even if `prop.title` changes in `componentWillReceiveProps`. I wonder if we could just remove this part.

2019-05-14 18:08 UTC, christianvogt commented on frontend/public/extend/devconsole/components/application-switcher/ApplicationSwitcher.tsx
> +      title={title && <span className="btn-link__title">{title}</span>}
Is this intended to be `&&`: `title={title && <span className="btn-link__title">{title}</span>}`

2019-05-14 18:12 UTC, divyanshiGupta commented on frontend/public/components/utils/dropdown.jsx
> +    const defaultTitle = React.isValidElement(props.title) ? props.title : <span className="btn-dropdown__item--placeholder">{props.title}</span>;
Maybe we can. But I am not aware of all the edge cases of as to why it was placed here in the first place. Better to leave it here for now.

2019-05-14 18:14 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/application-switcher/ApplicationSwitcher.tsx
> +      title={title && <span className="btn-link__title">{title}</span>}
Yes, I was doing this for checking if title is available then only send the element.

2019-05-14 18:27 UTC, rohitkrai03 approved these changes
LGTM

2019-05-14 19:35 UTC, christianvogt commented on frontend/public/components/utils/dropdown.jsx
> +    const defaultTitle = React.isValidElement(props.title) ? props.title : <span className="btn-dropdown__item--placeholder">{props.title}</span>;
I'm fine not removing. Just wanted to make sure I knew what it was for.

2019-05-14 19:37 UTC, christianvogt commented
@divyanshiGupta 
shouldn't `all applications` appear at the top?
![image](https://user-images.githubusercontent.com/14068621/57726898-274ef480-765e-11e9-87ae-d015f92bf899.png)

2019-05-14 19:46 UTC, divyanshiGupta commented
> @divyanshiGupta
> shouldn't `all applications` appear at the top?
> ![image](https://user-images.githubusercontent.com/14068621/57726898-274ef480-765e-11e9-87ae-d015f92bf899.png)

Yes, it should. Fixed it.

2019-05-14 20:01 UTC, christianvogt approved these changes

2019-05-14 20:02 UTC, merged