feat(import-flow):import from private git repo
talamer/console pull request #88
Opened 2019-05-12 20:46 UTC by debsmita1

This PR includes:
-  displays `Source Secret` drop-down when repository is not reachable
-  the drop-down displays a list of already created secrets of auth type `ssh-type` and `basic-type`
-  there is a provision to create a new secret
-  for creating a new secret, user needs to enter the source secret credentials
Refer Story: https://jira.coreos.com/browse/ODC-323
Note: This code doesnot validate the secret credentials entered by the user. Hence user is not refrained from clicking the create button on the import form.

2019-05-13 01:23 UTC, serenamarie125 commented
@debsmita1 can you include screenshots or an animated gif?

2019-05-13 08:24 UTC, debsmita1 commented
@serenamarie125 

![screen 1](https://user-images.githubusercontent.com/22490998/57606386-66aa1200-7586-11e9-9a8d-e9798c9bd4c0.png)
![screen 2](https://user-images.githubusercontent.com/22490998/57606396-6c075c80-7586-11e9-9f5d-8b1da4a501ed.png)
![screen 3](https://user-images.githubusercontent.com/22490998/57606421-788bb500-7586-11e9-964b-d1fc79917f5b.png)

2019-05-13 08:45 UTC, divyanshiGupta requested changes
So there are a few files that are almost same as the files already present in the console, hence a lot of duplicate code. I am not sure if this is the right way to do it. I have left a few comments

2019-05-13 08:45 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/SourceSecretDropdown.tsx
> +export default SourceSecretDropdown;
This file is same as `AppDropdown.tsx` only the resource is different, so I think you can add this resource in the  `AppDropdown`  resources array itself and then in your dropdown file use this resource to create items for the dropdown.

2019-05-13 08:45 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/SecretDropdown.tsx
> +export default SecretDropdown;
This file is same as the `LabelDropdown.tsx` only the part where you create your `unsortedList` is different, and the logic of creating the `unsortedArray` is similar so I think we can add this in the `LabelDropdown` in a way that it creates the `unsortedList` depending upon the context.

2019-05-13 08:45 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/SourceSecretSelector.tsx
> +export default SourceSecretSelector;
Can we separate out `AuthenticationType`  to make this file smaller?

2019-05-13 11:48 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import/SourceSecretSelector.tsx
> +export default SourceSecretSelector;
Done https://github.com/talamer/console/pull/88/commits/33eb693a94e8309b71d6f7b4117bb8ab8f1812e4

2019-05-13 22:15 UTC, christianvogt reviewed
- If I'm already in "create new secret" mode, clicking again on "create new secret" loses my input data.
- After entering the secret info, I changed the url and lost all my data. Even though I edited the url to exactly the same url as I had before.
- There is way too much logic now in the `ImportFlowForm` that should be separated out into utilities and other components to make this easily testable.

2019-05-13 22:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.scss
> +.odc-git-url-info {
Only one block selector per component.
`odc-import-flow-form__git-url-info`

2019-05-13 22:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    const urlRegex = /^(?:git|ssh|http(s)?(:\/\/)|(git@))?[\w.-]+(?:\.[\w.-]+)+[\w\-._~:/?#[\]@!$&'()*+,;=.]+$/;
Why the url validation change? Give examples of what you're trying to support.

2019-05-13 22:15 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          {gitRepoUrlInfo ? <span className="odc-git-url-info">{gitRepoUrlInfo}</span> : ''}
This is very odd looking:
The font on the git url info is too similar to the label:
![image](https://user-images.githubusercontent.com/14068621/57657109-5440d000-75a8-11e9-960b-8e2fa1c12483.png)

Why not have it below the input field? Are there design mocks for this?

2019-05-14 05:19 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    const urlRegex = /^(?:git|ssh|http(s)?(:\/\/)|(git@))?[\w.-]+(?:\.[\w.-]+)+[\w\-._~:/?#[\]@!$&'()*+,;=.]+$/;
The url validation has to support `https` and `ssh` urls. The regex that was already there, showed invalid for `ssh` urls. We need support for it because user might want to create a secret using `ssh` auth type, in that case user needs to enter the `ssh` url for git.

2019-05-14 05:25 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          {gitRepoUrlInfo ? <span className="odc-git-url-info">{gitRepoUrlInfo}</span> : ''}
So the invision docs had it like this. Yesterday I spoke to Parvathy and she said that it has been updated, now she is displaying it like an error message below the input field. I am updating my code accordingly.

2019-05-14 06:35 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/SourceSecretDropdown.tsx
> +export default SourceSecretDropdown;
@debsmita1 Adding this here from our conversation for reference.
Right now `AppDropdown` is very specific and it does only one thing. Gets application from the labels. But if you are thinking of making it generic enough to handle all use cases then it shouldn't be specific to only application or secret
I would suggest let app dropdown be as it is. Better make the label dropdown a generic one. Where it take a list of items which can be any kubermetes resource and it takes the selector. Based on that it renders the dropdown list.
And then you have a secret dropdown that uses the generic label dropdown. You can name this generic label dropdown as `ResourceDropdown` or `ResourceSelectorDropdown`.

2019-05-14 06:39 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/import/SourceSecretDropdown.tsx
> +export default SourceSecretDropdown;
Yes, It makes more sense. Let the `AppDropdown` be as it is and try to make the `LabelDropdown ` generic and use it in your `SourceSecretDropdown`

2019-05-14 09:08 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          {gitRepoUrlInfo ? <span className="odc-git-url-info">{gitRepoUrlInfo}</span> : ''}
Fixed : https://github.com/talamer/console/pull/88/commits/920bcc403026e49a4d918d15b13e8a74558ca9c7

2019-05-14 09:08 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import/SecretDropdown.tsx
> +export default SecretDropdown;
Done https://github.com/talamer/console/pull/88/commits/920bcc403026e49a4d918d15b13e8a74558ca9c7

2019-05-14 09:08 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import/SourceSecretDropdown.tsx
> +export default SourceSecretDropdown;
Done https://github.com/talamer/console/pull/88/commits/920bcc403026e49a4d918d15b13e8a74558ca9c7

2019-05-14 11:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    const urlRegex = /^(?:git|ssh|http(s)?(:\/\/)|(git@))?[\w.-]+(?:\.[\w.-]+)+[\w\-._~:/?#[\]@!$&'()*+,;=.]+$/;
It looks like any string starting with `git` or `ssh` is now acceptable and not just `ssh://` or `git@`.

2019-05-14 15:22 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    const urlRegex = /^(?:git|ssh|http(s)?(:\/\/)|(git@))?[\w.-]+(?:\.[\w.-]+)+[\w\-._~:/?#[\]@!$&'()*+,;=.]+$/;
Done https://github.com/talamer/console/commit/4e9524320e99b2155f74a2bb85718e3f2ee6e2ec

2019-05-14 15:23 UTC, sbose78 commented
build and deploy

2019-05-14 15:23 UTC, sbose78 commented
Your build is progress : https://console-openshift-console.apps.tkurian4.devcluster.openshift.com/k8s/ns/openshift-console/builds
 
 PR will be LIVE in https://pr-88-openshift-console.apps.tkurian4.devcluster.openshift.com

2019-05-15 21:42 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    const urlRegex = /^(((ssh|git|https?):\/\/[\w]+)|(git@[\w]+.[\w]+:))([\w\-._~/?#[\]!$&'()*+,;=])+(\/)?$/;
Why did you add `(\/)?` to the end? the `/`' is already included in the previous set.
Are you trying to support the following: `git://github.com...`?

2019-05-16 08:21 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    const urlRegex = /^(((ssh|git|https?):\/\/[\w]+)|(git@[\w]+.[\w]+:))([\w\-._~/?#[\]!$&'()*+,;=])+(\/)?$/;
@christianvogt  removed `(\/)?`.
yes I am supporting `git://<somestring>`

2019-05-16 21:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    const urlRegex = /^(((ssh|git|https?):\/\/[\w]+)|(git@[\w]+.[\w]+:))([\w\-._~/?#[\]!$&'()*+,;=])+(\/)?$/;
thanks!

2019-05-17 20:22 UTC, christianvogt commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +          ) {
This is suppose to be a generic component and therefore shouldn't have these kinds of conditions.

2019-05-18 15:42 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +          ) {
Done https://github.com/talamer/console/pull/88/commits/1c7465cbfa1dc171a9e429a34b4854aea9410fb9

2019-05-20 11:13 UTC, rohitkrai03 requested changes

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  private sourceSecretParams() {
This could easily be written as -
```suggestion
  private sourceSecretParams() {
    const isBasicAuth = this.state.secretAuthType === 'kubernetes.io/basic-auth';
    return {
      apiVersion: 'v1',
      kind: 'Secret',
      metadata: {
        name: this.state.sourceSecretName,
        namespace: this.state.namespace,
      },
      type: this.state.secretAuthType,
      [isBasicAuth ? 'data' : 'stringData']: this.state.secretCredentials,
    };
  }
```
Much more concise and readable.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  private gitSourceWithSecretParams(gitSourceName: string, gitSecretName: string) {
`gitSourceWithSecretParams` and `gitSourceParams` could easily be merged into one. I don't like adding more code to this already behemoth of a component.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    k8sCreate(SecretModel, this.sourceSecretParams())
Rather than having all these promises getting resolved inside of one another we can have separate promises for all tasks and execute it using `Promise.all`. That would be much more easy to understand and debug. And this is for all the resource creation we are doing in git import, its too complicated to reason with easily.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +                history.push(pathWithPerspective('dev', `/topology/ns/${this.state.namespace}`));
No need to use `pathWithPerspective` when you are sending hardcoded perspective as `dev`. You could easily just say `/dev/topology/ns/${this.state.namespace}` if we know that this page is only going to be used in dev perspective.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    k8sCreate(
Maybe having just one `createGitSourceComponent` with condition to create `SourceSecret` or not would be much simpler and concise here.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +      if (this.state.selectedSourceSecret === 'create-source-secret') {
Again if we have separate promises for every resource creation here and push it in an array based on some conditions, we can execute every promise from the array at once without having this type of nested if else structure here.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          if (res.status.connection.reason === 'RepoNotReachable') {
Use enum here instead of string literals. The whole reason of having enums is to use constants defined only in one place and used elsewhere.
```suggestion
          if (res.status.connection.reason === ErrorMessage.RepoNotReachable) {
```

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +          {this.state.showSourceSecretDropDown ? (
No need to use ternary operator if you only care about truthy condition.
```suggestion
          {this.state.showSourceSecretDropDown && <SourceSecretSelector />
```

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/AuthenticationType.tsx
> +export default class AuthenticationType extends React.Component<
`AuthenticationType` name doesn't give full information about what this component actually does. A better name would be `CreateSourceSecret` or something that describes that this is the source secret creation form. `AuthenticationType` is just a dropdown which is part of this form.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/AuthenticationType.tsx
> +          <BasicAuthSubform
Why are you creating your own `BasicAuthSubForm` and `SSHAuthSubForm`? Why not use what console already has in `create-secret.tsx`. AFAIK its exactly the same form.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BasicAuth.tsx
> +/* eslint-disable no-unused-vars, no-undef */
Better reuse form component from `create-secret.tsx`.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BasicAuth.tsx
> +export default class BasicAuthSubform extends React.Component<
Name of your file and name of you class should be same for consistency.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/SshAuth.tsx
> +/* eslint-disable no-unused-vars, no-undef */
Better reuse form component from `create-secret.tsx`.

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> -
This is totally wrong. You've removed all the logic from `LabelSelector` and moved that logic to its parent. Now it's just getting some props from parent and passing it down to `Dropdown` component. You can easily use `Dropdown` in your parent component. And now you have the same aggregation logic in two of such parent components which is why this component was created in the first place. Now every time i need to get a dropdown with some labels from a resource, i'll have to rewrite all that logic into the parent component and use this `LabelDropdown`.

Also, now the props name and direction doesn't make sense. Like why does this component care about if list is sorted or not?

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +  getSortedList = (resources, labelSelector, allSelectorItem) => {
if you have all the logic in here for getting the list and sorting the list of item why not use `Dropdown` directly?

2019-05-20 11:13 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/SourceSecretDropdown.tsx
> +  getSortedList(resources, labelSelector, allSelectorItem) {
if you have all the logic in here for getting the list and sorting the list of item why not use `Dropdown` directly?

2019-05-20 11:17 UTC, rohitkrai03 commented
@debsmita1 The change in `LabelDropdown` now breaks the `ApplicationSwitcher` at the top. It doesn't render anything in the list now.
<img width="1422" alt="Screenshot 2019-05-20 at 4 45 54 PM" src="https://user-images.githubusercontent.com/6041994/58017852-e43dc700-7b1e-11e9-9567-dbda79fb4e08.png">

2019-05-20 11:18 UTC, rohitkrai03 commented
@debsmita1 Also, selecting already created source secret doesn't show anything as title of the dropdown. I guess this bug is also related to changes in `LabelDropdown.`
<img width="709" alt="Screenshot 2019-05-20 at 4 19 41 PM" src="https://user-images.githubusercontent.com/6041994/58017918-0cc5c100-7b1f-11e9-836d-7bdb7ddd347b.png">

2019-05-20 15:32 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    k8sCreate(SecretModel, this.sourceSecretParams())
I am not too worried about this right now. We'll be removing all this code while refactoring for Git Import without CRDs story. So, you can skip over this one.

2019-05-20 17:44 UTC, rohitkrai03 commented
@debsmita1 You can add a generic `propertySelector` or `dataSelector` prop to `LabelDropdown` and send different property paths like below to make it generic and work with any kind of property in a resource that you want to aggregate in the dropdown.
```
    _.each(resources, ({ data }) => {
      _.reduce(
        data,
        (acc, resource) => {
          const labelValue = _.get(resource, ['metadata', 'labels', 'app.kubernetes.io/part-of']);
          if (labelValue) {
            acc[labelValue] = { name: labelValue };
          }
          return acc;
        },
        unsortedList,
      );
    });
```

`['metadata', 'labels', 'app.kubernetes.io/part-of']` could be a prop coming down from parent. Checkout `lodash` implementation to see how they've added type checking for the function parameter. We can do the same thing here.

2019-05-21 09:45 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  private sourceSecretParams() {
Done https://github.com/talamer/console/pull/88/commits/d7910bada1f9cb9471f43a5f4355ea5f6b775c82

2019-05-21 09:46 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +  private gitSourceWithSecretParams(gitSourceName: string, gitSecretName: string) {
Done https://github.com/talamer/console/pull/88/commits/d7910bada1f9cb9471f43a5f4355ea5f6b775c82

2019-05-21 09:46 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +                history.push(pathWithPerspective('dev', `/topology/ns/${this.state.namespace}`));
Done https://github.com/talamer/console/pull/88/commits/d7910bada1f9cb9471f43a5f4355ea5f6b775c82

2019-05-21 09:47 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import/SshAuth.tsx
> +/* eslint-disable no-unused-vars, no-undef */
Done https://github.com/talamer/console/pull/88/commits/d7910bada1f9cb9471f43a5f4355ea5f6b775c82

2019-05-21 09:47 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> -
Fixed https://github.com/talamer/console/pull/88/commits/d7910bada1f9cb9471f43a5f4355ea5f6b775c82

2019-05-21 09:47 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/dropdown/AppDropdown.tsx
> +  getSortedList = (resources, labelSelector, allSelectorItem) => {
Fixed https://github.com/talamer/console/pull/88/commits/d7910bada1f9cb9471f43a5f4355ea5f6b775c82

2019-05-21 09:47 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import/SourceSecretDropdown.tsx
> +  getSortedList(resources, labelSelector, allSelectorItem) {
Fixed https://github.com/talamer/console/pull/88/commits/d7910bada1f9cb9471f43a5f4355ea5f6b775c82

2019-05-21 09:49 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +    k8sCreate(
Done d7910ba

2019-05-21 09:49 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/import/BasicAuth.tsx
> +export default class BasicAuthSubform extends React.Component<
Removed this file Done d7910ba

2019-05-21 10:12 UTC, rohitkrai03 requested changes

2019-05-21 10:12 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +        Promise.all([this.createSecret(), this.createGitSource(), this.createGitSourceComponent()])
Here if you push your promises into the array based on the conditions, you would not have to duplicate same `.then().catch()` for every condition.

2019-05-21 10:12 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +        k8sCreate(GitSourceComponentModel, this.catalogParams()).then(
You already have this function `createGitSourceComponent` defined which returns exactly same thing.

2019-05-21 10:12 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  shouldComponentUpdate(nextState) {
First parameter of `shouldComponentUpdate` sends `nextProps`. So now you are getting next props in `nextState` variable.

2019-05-21 10:12 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  filterData?: (resource: any) => boolean;
rename it to `filterData` -> `resourceFilter`.

2019-05-21 10:12 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  dataSelector: string[];
Add type similar to what `lodash` does.

2019-05-21 12:15 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  filterData?: (resource: any) => boolean;
Done

2019-05-21 12:16 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  shouldComponentUpdate(nextState) {
Fixed

2019-05-21 12:17 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +        k8sCreate(GitSourceComponentModel, this.catalogParams()).then(
Done https://github.com/talamer/console/commit/39c79cc6d1aee5d7b326aff4fb7009ec393d4f61

2019-05-21 12:17 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +        Promise.all([this.createSecret(), this.createGitSource(), this.createGitSourceComponent()])
Done https://github.com/talamer/console/commit/39c79cc6d1aee5d7b326aff4fb7009ec393d4f61

2019-05-21 15:25 UTC, rohitkrai03 requested changes

2019-05-21 15:25 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +        const promise = Promise.all([
I think this would work here as well - 
```
let promises = [this.createGitSourceComponent()];
if (this.state.showSourceSecretDropDown && this.state.selectedSourceSecret === 'create-source-secret') {
  promises.unshift(this.createGitSource());
  promises.unshift(this.createSecret());
} else {
  promises.unshift(this.createGitSource());
}
```

2019-05-21 19:11 UTC, debsmita1 commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +        const promise = Promise.all([
Done https://github.com/talamer/console/commit/2a4d63879aa46061535553e6a06d53b97ae306ff

2019-05-21 19:11 UTC, debsmita1 commented on frontend/public/extend/devconsole/shared/components/dropdown/LabelDropdown.tsx
> +  dataSelector: string[];
Done https://github.com/talamer/console/commit/2a4d63879aa46061535553e6a06d53b97ae306ff

2019-05-22 08:22 UTC, rohitkrai03 approved these changes

2019-05-22 08:23 UTC, divyanshiGupta approved these changes

2019-05-22 08:42 UTC, merged