Add builder image selector in card layout and import flow refactor
talamer/console pull request #89
Opened 2019-05-13 12:57 UTC by rohitkrai03

Related JIRA story - https://jira.coreos.com/browse/ODC-690

This PR
- Adds a new Builder Image Selector which is based on Card layout.
- Also adds a builder image version selector which show the tag selected for builder image.
- Based on the builder image and tag selected, builder image information will be showed.
- Now auto detected image will be shown as recommended image with a green check icon.
- User will be able to select a different builder image than recommended image.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.scss
> +  margin-bottom: 10px;
Remove the margins. The spacing is applied through form groups.

Add extra padding to the box to give even spacing around the outside to equal the spacing between items:
![image](https://user-images.githubusercontent.com/14068621/57636759-ccdb6880-7577-11e9-836a-7b6218db3295.png)

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +.odc-builder-image-selector__card {
```suggestion
.odc-builder-image-card {
```

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +  &-icon {
```suggestion
  &__icon {
```
Same pattern for all the other element selectors.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    border: var(--pf-global--active-color--100) 2px solid;
Use `outline` instead of border to prevent the card from bouncing in size.
Modifiers should use the format `is-<modifier>`.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    color: #3f9c35;
Use a PF color variable.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    border: var(--pf-global--active-color--100) 2px solid;
Use `outline` instead of `border` and join this selector with the selected one above.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    line-height: 18px;
Use patternfly variables.
I think you need `font-weight: 700` to make it bold like the design mock up.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +  margin: 8px;
PF uses size increments of 8px. Could you update your sizes accordingly.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +      }`}
Use the library `classnames` to create class strings.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +const BuilderImageCard = ({ image, selected, recommended, onChange }) => {
Need prop types definition.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +    <Card
```suggestion
    <Card component="button" aria-label={image.title}
```
You'll have to adjust the styles a bit and fix the removal of the focus outline that console removes in `_base.scss` for whatever reason. But if you do this then you can tab through the buttons instead of just using the mouse.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +  gitUrlValidationStatus,
Do not bring the definition of `gitUrlValidationStatus` into this component. If it is just being used to show a loading image, make a specific prop for that purpose.

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +    const title = displayName && displayName.length < 14 ? displayName : prettifyName(name);
Why use `displayName` only if the length is < 14?

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +  builderImageStreams.map((imageStream) => {
`map` => `each`
or use `reduce`

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageTagSelector.tsx
> +  imageTags: any[];
Can you use a type that's not `any`?

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +  }
Use a prop `loading` to indicate whether the loading component should be shown. Let the parent set `loading={!builderImages}`

2019-05-13 20:16 UTC, christianvogt commented on frontend/public/extend/devconsole/components/ImportFlowForm/ImportFlowForm.tsx
> +              {nameError ? nameError : 'Identifies the resources created for this application'}
```suggestion
              {nameError || 'Identifies the resources created for this application'}
```

2019-05-13 20:16 UTC, christianvogt commented
Bug: When the user has already chosen a builder image, the version and description is shown. If the user then goes and changes the git URL, detection is re-run and then the builder image version description disappears.

2019-05-13 21:20 UTC, christianvogt commented
@rohitkrai03 as seen in your screenshot, the builder image selector expands beyond the bounds of the form. It should be the same width as the rest of the form.

2019-05-14 02:08 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +    const title = displayName && displayName.length < 14 ? displayName : prettifyName(name);
Because card size we cannot show display name with more than 14 characters. So instead of truncating it with `...` i am using spec name after prettifying it which is generally shorter.

2019-05-14 02:43 UTC, rohitkrai03 commented
@christianvogt I've updated the PR with fixes according to review comments. Please review again. Also fixed the bug you mentioned.
About the size of builder image selector, i've done this based on the designs in https://redhat.invisionapp.com/share/G2RH3HM4HMT#/screens/358681874. It seemed odd to me as well that only the card layout is supposed to be full width and i had to actually add extra styling to make this happen. I am happy to make it same as other if you want.

2019-05-14 02:44 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +  }
Done

2019-05-14 13:50 UTC, invincibleJai commented
@rohitkrai03 shall we make use of https://github.com/typicode/react-fake-props , this will eliminate having props in code

2019-05-14 13:52 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +    const title = displayName && displayName.length < 14 ? displayName : prettifyName(name);
@rohitkrai03 is this common to have longer names? Are they single words or multiple words that can wrap?
Did you bring this up with UX?

2019-05-14 13:56 UTC, christianvogt commented
@invincibleJai with typescript the props are only a compile time artifact. For plain JS, the proptypes are typically removed via a babel plugin. Not sure if console uses it but regardless we use typescript.

2019-05-14 14:55 UTC, invincibleJai commented
thanks, @christianvogt I was thinking `react-fake-props` can eliminate having props from test as in  https://github.com/talamer/console/blob/master-next/frontend/public/extend/devconsole/components/ImportFlowForm/__tests__/ImportFlowForm.spec.tsx#L12-L79  and maybe look cleaner.

2019-05-14 15:01 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +    const title = displayName && displayName.length < 14 ? displayName : prettifyName(name);
Yes, i did bring this up with UX - https://coreos.slack.com/archives/CHC2R6AGG/p1557398418064500. We have names like `Nginx HTTP server and a reverse proxy (nginx)`. The response i got from UX was to truncate the name and add `...` but it doesn't seem right to me. That is why i chose to display spec name which is shorter.

2019-05-14 18:11 UTC, christianvogt commented
@invincibleJai ah sorry. I didn't pick up exactly on what it's intent was.

2019-05-14 18:51 UTC, christianvogt commented
While the builder image is loading we see this; missing the label:
![image](https://user-images.githubusercontent.com/14068621/57723904-adb40800-7657-11e9-8daa-1a1322137548.png)

2019-05-14 19:16 UTC, rohitkrai03 commented
@christianvogt Fixed. Now the loading animation is shown along with label.

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +.odc-builder-image-card {
add `cursor: pointer` if the supplied `component` to the `Card` is not a semantic HTML element that provides the `pointer` cursor by default.

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    color: var(--pf-global--success-color--200);
![image](https://user-images.githubusercontent.com/14068621/57724486-e1dbf880-7658-11e9-8c26-c28653b36082.png)

This looks dark. Maybe use the `100` variant? Ask UX.
Also the recommended text above doesn't have the same color for the star.
![image](https://user-images.githubusercontent.com/14068621/57724450-d1c41900-7658-11e9-8f06-b9a3fbecb4b3.png)

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +    <Card className={classes} onClick={() => onChange(image.name)}>
By default a `Card` is an `article` which doesn't fit semantically for this usage.

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +  }
Looks odd to not show the label while the data is loading. The form group should still be present.

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +  if (isGitUrlValidated && !recommendedImage && !builderImageError) {
Replace with a prop `loadingRecommendedImage` and move the logic for setting the value `true|false` to the parent.

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageTagSelector.tsx
> +      {selectedImageTag && (
Use `imageTag` since it's the data that is passed to the child component.
```suggestion
      {imageTag && (
```

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/source-to-image/SourceToImage.tsx
> +    );
Same thing done twice now. Looks like a good candidate for a utility.

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/imagestream-utils.ts
> +    const title = displayName && displayName.length < 14 ? displayName : prettifyName(name);
Thanks for the clarification. We go with this unless told otherwise :)

2019-05-14 19:17 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +          <i className="fa fa-star" aria-hidden="true" />
use patternfly react-icons

2019-05-14 19:18 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +          <i className="fa fa-star" aria-hidden="true" /> icon)
use patternfly react-icons

2019-05-14 19:19 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    color: var(--pf-global--success-color--200);
Not going to hold up the PR on a color, but both stars should at least be the same color.

2019-05-14 19:26 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +          <i className="fa fa-star" aria-hidden="true" />
The new Patternfly 4 docs didn't have star icon listed - https://www.patternfly.org/v4/design-guidelines/styles/icons that's why i used font awesome. Just now looked at http://patternfly-react.surge.sh/patternfly-4/icons/Icons/ and found star. Will use it.

2019-05-14 19:47 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    color: var(--pf-global--success-color--200);
Well, i used lighter colour at first but that doesn't catch user's attention easily. So switched to darker ones.
<img width="347" alt="Screenshot 2019-05-15 at 1 15 16 AM" src="https://user-images.githubusercontent.com/6041994/57727416-17abcc00-76af-11e9-8fe1-498570e606b8.png">
<img width="144" alt="Screenshot 2019-05-15 at 1 01 12 AM" src="https://user-images.githubusercontent.com/6041994/57727430-1e3a4380-76af-11e9-8504-0e05c1145867.png">

If it looks ok to you then i am fine.

2019-05-14 19:51 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    color: var(--pf-global--success-color--200);
I wasn't sure if we wanted to replace the validation icons as well. I don't really don't care at this point :P

2019-05-14 21:03 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +    <Card
Done.

2019-05-14 21:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +    <Card className={classes} onClick={() => onChange(image.name)}>
Fixed it. Now the buttons are also accessible through tabs.

2019-05-14 21:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/source-to-image/SourceToImage.tsx
> +    );
Done. Added a utility function that finds the tag and display name and returns both.

2019-05-14 21:04 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +          <i className="fa fa-star" aria-hidden="true" /> icon)
Done

2019-05-14 21:05 UTC, rohitkrai03 commented
@christianvogt Updated PR with fixes according to review comments.

2019-05-14 21:06 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +          <i className="fa fa-star" aria-hidden="true" /> icon)
done

2019-05-14 21:06 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.tsx
> +  if (isGitUrlValidated && !recommendedImage && !builderImageError) {
Done

2019-05-15 02:57 UTC, vikram-raj requested changes
When I change the autodetected builder image by selecting the other card then it submits the form which should not happen.
![Peek 2019-05-15 08-23](https://user-images.githubusercontent.com/2561818/57745563-4ba4e280-76eb-11e9-8709-47b4e7626e6c.gif)

2019-05-15 03:03 UTC, vikram-raj commented
Card shadows look darker than the actual design. 

Current implementation
![Screenshot from 2019-05-15 08-29-00](https://user-images.githubusercontent.com/2561818/57745722-dd145480-76eb-11e9-8eca-a22e3b6be1c7.png)

Actual design
![Screenshot from 2019-05-15 08-32-24](https://user-images.githubusercontent.com/2561818/57745759-ff0dd700-76eb-11e9-9213-11bc4c805e29.png)

2019-05-15 15:29 UTC, christianvogt commented
The buttons look like this for me now:
![image](https://user-images.githubusercontent.com/14068621/57788176-a26ae600-7704-11e9-84ee-ca83110c6fac.png)

You need to remove the border that's applied to buttons.

2019-05-15 15:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.tsx
> +    <Card
To fix the form submit, you also need to set `type="button"`

2019-05-15 15:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +    outline: var(--pf-global--active-color--100) 3px solid;
If continuing with using outline:
```
  &.is-selected,
  &:hover,
  &:focus,
  &:active {
    outline: var(--pf-global--active-color--100) 3px solid;
    outline-offset: -3px;
  }
```

2019-05-15 15:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageCard.scss
> +.odc-builder-image-card {
Add `outline: 0;` if using outline for your border. Otherwise set a transparent border equal to the size of the hover / active / focus border.

2019-05-15 15:46 UTC, christianvogt commented on frontend/public/extend/devconsole/components/import/BuilderImageSelector.scss
> +  button:focus {
Remove this. If needed it should be part of the card itself and not here.

2019-05-15 19:38 UTC, rohitkrai03 commented
@christianvogt @vikram-raj Updated PR with fixes to above issues.

2019-05-15 21:36 UTC, christianvogt approved these changes

2019-05-15 21:36 UTC, merged