fix(pipelinerun): Check status using condition[0].status instead of type
talamer/console pull request #91
Opened 2019-05-14 09:55 UTC by abhinandan13jan

Fixes  https://jira.coreos.com/browse/ODC-785:
Changed status to populate out of conditions[0].status instead of conditions[0].type
@christianvogt @rohitkrai03 Please review

2019-05-14 13:49 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +            pipelinerun.status.conditions && pipelinerun.status.conditions[0].status === 'True'
Will there always be a `condition[0]`? What if the pipeline is still running or hasn't started yet?

2019-05-14 13:50 UTC, christianvogt commented on frontend/public/extend/devconsole/utils/pipeline-filter-reducer.ts
> +  if (pipelineRun.status && pipelineRun.status.conditions[0].status === 'True') {
Need unit tests.

2019-05-14 17:08 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +            pipelinerun.status.conditions && pipelinerun.status.conditions[0].status === 'True'
should I add a safety check for 'condition'?

2019-05-14 17:08 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/utils/pipeline-filter-reducer.ts
> +  if (pipelineRun.status && pipelineRun.status.conditions[0].status === 'True') {
will add.

2019-05-14 17:24 UTC, christianvogt commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +            pipelinerun.status.conditions && pipelinerun.status.conditions[0].status === 'True'
Yes. Absolutely ensure your code will never throw an unexpected error because you're trying to read a property from an undefined object.

2019-05-15 14:44 UTC, abhinandan13jan commented
@christianvogt updated

2019-05-15 15:59 UTC, christianvogt commented
@abhinandan13jan why are you always looking at `condition[0]` what about the rest of them? What if `condition[0]` type isn't `Succeeded`, should you move on to next condition?

2019-05-15 19:00 UTC, abhinandan13jan commented
@christianvogt I've updated to check for the first existence of a successful condition

2019-05-15 19:20 UTC, christianvogt commented on frontend/public/extend/devconsole/components/__tests__/pipeline-filter-reducer.spec.ts
> +import { pipelineRunFilterReducer } from '../../utils/pipeline-filter-reducer';
This is in the wrong directory.

2019-05-16 06:47 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/__tests__/pipeline-filter-reducer.spec.ts
> +import { pipelineRunFilterReducer } from '../../utils/pipeline-filter-reducer';
moved

2019-05-16 12:01 UTC, divyanshiGupta requested changes

2019-05-16 12:01 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +        pipelinerun.spec.trigger.type
Properly format your code

2019-05-16 12:01 UTC, divyanshiGupta commented on frontend/public/extend/devconsole/components/pipelineruns/__tests__/pipeline-filter-reducer.spec.ts
> +});
Run prettier on this file.

2019-05-16 13:29 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelineruns/__tests__/pipeline-filter-reducer.spec.ts
> +});
The formatting is done by prettier code formatter. Do I need to change some settings for the extension?

2019-05-16 13:29 UTC, abhinandan13jan commented on frontend/public/extend/devconsole/components/pipelineruns/PipelineRunRow.tsx
> +        pipelinerun.spec.trigger.type
The formatting is done by prettier code formater

2019-05-16 21:34 UTC, christianvogt commented
@abhinandan13jan  lol why'd you reformat `pipeline-filter-reducer.ts `? It was fine!

2019-05-17 07:51 UTC, abhinandan13jan commented
> Make sure to enable `prettier-eslintIntegration` in your vscode because we cannot strictly format with prettier; we must adhere to eslint rules too.
@christianvogt @divyanshiGupta 
I tested a few times and am not getting any 'lint' errors and this is also formatted using prettier. please merge this, I need some functionalities from this PR in the other PR.

![Screenshot from 2019-05-17 13-18-43](https://user-images.githubusercontent.com/24852534/57911847-8010ce00-78a6-11e9-9bf3-645fe882cec4.png)

2019-05-17 10:55 UTC, divyanshiGupta approved these changes

2019-05-17 17:48 UTC, merged