Add labels when Deploying image
talamer/console pull request #97
Opened 2019-05-15 15:35 UTC by debsmita1

This PR includes:
- an application dropdown in the `Deploy Image` form
- user can select an application from the dropdown or can create a new one
- applies label when image is deployed

Refer Story: https://jira.coreos.com/browse/ODC-595

![Screenshot from 2019-05-15 20-32-04](https://user-images.githubusercontent.com/22490998/57787038-44fd8600-7752-11e9-9a7c-cfbdf82bcfcb.png)

2019-05-16 18:12 UTC, rohitkrai03 requested changes

2019-05-16 18:12 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
You also need to add `app.kubernetes.io/instance` label here.

2019-05-16 18:25 UTC, debsmita1 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
Yes its added. Line no. 196

2019-05-16 18:38 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
Sorry, i meant `app.kubernetes.io/component`

2019-05-16 21:23 UTC, christianvogt commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
How do we determine its value?
https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

2019-05-17 06:39 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@christianvogt We use `name` for both `component` and `instance` labels in git import and source to image forms for now.

2019-05-17 06:40 UTC, vikram-raj commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
Can we use this ```getAppLabels``` function https://github.com/talamer/console/blob/94ac7dd1651bbccececb128a037427a4aed35cd1/frontend/public/extend/devconsole/utils/resource-label-utils.ts#L1 here instead of adding all the labels manually?

2019-05-17 06:50 UTC, debsmita1 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@vikram-raj the `getAppLabels` takes `imageStreamName` as a parameter, how do we get that information ?

2019-05-17 10:59 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
To make use of that function we need to make `imageStreamName` as optional parameter in the function. I actually thought of doing it when i wrote the function but then there were no such use case back then.

2019-05-17 11:06 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
Actually you can get the `imageStream` info here as well. This form lets you search for a docker image from a image registry and pull that image to use as `imageStream` resource. Check for the resource objects that are used while creating all the resources. I think it's `isi.name` which you want.

2019-05-17 11:12 UTC, debsmita1 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@vikram-raj  @rohitkrai03 Done https://github.com/talamer/console/pull/97/commits/ff4065a88f133aa84ff9522e27a8e96be3e0b87e

![Screenshot from 2019-05-17 16-35-51](https://user-images.githubusercontent.com/22490998/57924418-a3e20d00-78c2-11e9-932b-251180137f6f.png)

2019-05-17 11:20 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
Actually you can get the `imageStream` info here as well. This form lets you search for a docker image from a image registry and pull that image to use as `imageStream` resource. Check for the resource objects that are used while creating all the resources. I think it's `isi.name` which you want.

2019-05-17 11:50 UTC, debsmita1 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@rohitkrai03 the `isi.name` is the Image name, which is `debsmitas/my-nodejs-image` here.

2019-05-18 14:23 UTC, christianvogt commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@sbose78 @gorkem what value in this case should be used for the `name` label.

2019-05-18 16:56 UTC, sbose78 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
An image could have labels, but we don't have recommendations for that as far as I know. The closest thing we could look for is - What is the label that our s2i process applies to images? If that label is present in the image, we should use that.

2019-05-20 08:16 UTC, debsmita1 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@sbose78 In s2i process `app.kubernetes.io/name` is the label that takes the builder image name as the value

2019-05-20 11:27 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@sbose78 @debsmita1 These labels are not getting applied to just the `ImageStream` that is being created here. Its getting applied to all the resources we create including `DeploymentConfig` and `Service`.

It's similar to what happens in s2i except that the builder image is a custom image provided by user from any registry. That is why the `name` attribute that comes from s2i builder image is something like `nodejs` but `name` attribute that comes here in deploy image form can be something like `quay.io/redhat-developer/console`.

So, the question would be can we use this `name` attribute as the value for `app.kubernetes.io/name` in case of deploy image flow?

2019-05-21 10:15 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@sbose78 Can you please take another look at the question i asked above?

2019-05-21 18:19 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@debsmita1 You can go ahead and use `isi.name` and pass it to `getAppLabels` as `imageStreamName`.

2019-05-21 19:14 UTC, sbose78 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
Realistically, you won't be able to get a meaningful `app.kubernetes.io/name` other than inspecting the image layers because the _name_ available for that image might not even be associated with any build type. The image being imported/deployed is not a builder image, rather a deployable image which gets tracked as an image stream.

`app.kubernetes.io/name` should really just be placeholder text in case of _Deploy image_ .

2019-05-21 19:57 UTC, rohitkrai03 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
@sbose78 What do you mean by placeholder text? Is it okay then to just not apply this label?

2019-05-21 21:10 UTC, christianvogt commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
probably ok for now to not apply it and we can discuss later for another pr

2019-05-21 21:11 UTC, christianvogt approved these changes

2019-05-21 21:26 UTC, rohitkrai03 approved these changes

2019-05-21 22:29 UTC, sbose78 commented on frontend/public/components/deploy-image.tsx
> +      'app.kubernetes.io/instance': name,
Rohit, yes.

2019-05-21 22:40 UTC, merged