Pod Visualization using Victory Pie
talamer/console pull request #98
Opened 2019-05-15 16:53 UTC by sahil143

[Done]:
- create an initial Component for Pod Visualization
- Create a separate component To show Tooltip in Victory Pie.
- Pod state colors match design.
- Number of segments correspond to the number of unique pod states currently active.
- Segment lengths correspond to the number of pods in a given state where all pods add up to 360deg - arc.
- Segments are placed in order according to the order of the states defined in the UX doc.
- Tooltips are available per segment and describe how many pods are in the current state.

[TODO]
- [ ] Make PodStatus component generic as a Donut Component
- [x] - create separate scss for tooltip component

![Screenshot from 2019-05-15 22-19-26](https://user-images.githubusercontent.com/9278015/57793854-f6ef7f00-775f-11e9-95d9-652c44dd6b60.png)
![Screenshot from 2019-05-15 22-19-20](https://user-images.githubusercontent.com/9278015/57793855-f7881580-775f-11e9-9b4f-73b4cde18ae1.png)
Updated podColors: ![Screenshot from 2019-05-15 22-19-20](https://user-images.githubusercontent.com/9964343/58071580-cd4cb280-7bba-11e9-9d4a-7d71cda54772.png
)

2019-05-16 03:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +type PodStatusProps = {
Need to accept standalone prop to make it reusable outside topology.

2019-05-16 03:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  width: number;
Probably shouldn't accept x and y.
Instead of width and height accept size since this will always be a uniform size. Or just use outer radius to calc size.

2019-05-16 03:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  data: any;
Just an fyi. If this is supposed to be reusable beyond topology we need this to accept an array of pods.
But we can also have this be very specific data structure.
Just do the use type `any`.

2019-05-16 03:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  componentDidUpdate({ data }: PodStatusProps) {
Remove this and do any data transform in the tender function.

2019-05-16 03:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  createDataForVisualization = () => {
Remove internal state and do this transformation in the render function.

2019-05-16 03:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +    const centerTransform = `translate(-63, -63)`;
Magic numbers?

2019-05-16 03:52 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +      <g className={'odc-default-group__label'}>
This really should be referencing its own style. In its own scss file.

2019-05-17 02:10 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +    const centerTransform = `translate(-63, -63)`;
yes ;)

2019-05-17 02:10 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +type PodStatusProps = {
fixed in https://github.com/talamer/console/pull/98/commits/720f6b099afb1d19795391a96056dc1708183922

2019-05-17 02:11 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  width: number;
fixed in https://github.com/talamer/console/pull/98/commits/720f6b099afb1d19795391a96056dc1708183922

2019-05-17 02:11 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  data: any;
changed the data type to array of pods. https://github.com/talamer/console/pull/98/commits/720f6b099afb1d19795391a96056dc1708183922

2019-05-17 02:12 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  createDataForVisualization = () => {
fixed in https://github.com/talamer/console/pull/98/commits/7acfdccd9d4190f1ed6d4e459de79727745c4acb

2019-05-17 02:12 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/VictoryPodStatus.tsx
> +  componentDidUpdate({ data }: PodStatusProps) {
fixed in https://github.com/talamer/console/pull/98/commits/7acfdccd9d4190f1ed6d4e459de79727745c4acb

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/WorkloadNode.tsx
> +        standalone={false}
remove as standalone = false should be the default.

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +  const vData = [];
This needs a type.

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +const podStatus = [
```suggestion
const podStatus = Object.keys(podColor);
```

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
>  export const podColor = {
Confirm colors align with UX:
https://docs.google.com/document/d/1ERBQxCiA9HCIA7duhnrX46rTmQYIiSTrYLfUh_Uo0Pk/edit

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +import Tooltip from './../SvgPodTooltip';
```suggestion
import Tooltip from '../SvgPodTooltip';
```

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +import './DefaultGroup.scss';
Move scss imports to end of list.

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +      groupComponent={x && y ? <g transform={centerTransform} /> : <g />}
```suggestion
      groupComponent={x && y ? <g transform={`translate(${x}, ${y})`} /> : <g />}
```
Do you have to provide the else clause as `<g />` or will `undefined` or `null` work?

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +      labelComponent={<Tooltip x={outerRadius + 2} y={-12} />}
Why `+ 2` ?

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +const PodStatus: React.FunctionComponent<PodStatusProps> = ({
```suggestion
const PodStatus: React.FC<PodStatusProps> = ({
```

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/SvgPodTooltip.tsx
> +import { podColor } from './shapes/PodStatus';
We do not want to import from other components like this. It should otherwise be a util.
That being said we talked about refactoring this component and the existing `SvgBoxedText` component. So i don't care that it's done this way right now as it'll be cleaned up later.

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +          : []
Does this have to be `[]` or can it be null or undefined?

2019-05-17 19:47 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +  standalone: boolean;
make `standalone` optioonal

2019-05-18 05:45 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +          : []
yes, this has to be an empty array else we will get error `can not read property of null`.

2019-05-18 05:49 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +const podStatus = [
This array has status in the order we need to show but I can rearrange the podColor object to keep the order.

2019-05-18 05:53 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +      labelComponent={<Tooltip x={outerRadius + 2} y={-12} />}
Oops! this should be size/2

2019-05-18 06:28 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +  standalone: boolean;
fixed https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:29 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +          : []
undefined works here. fixed https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:29 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/SvgPodTooltip.tsx
> +import { podColor } from './shapes/PodStatus';
fixed! moved to topology-utils.tsx https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:29 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +      labelComponent={<Tooltip x={outerRadius + 2} y={-12} />}
fixed https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:30 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +      groupComponent={x && y ? <g transform={centerTransform} /> : <g />}
null doesn't but undefined does. fixed https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:30 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +import './DefaultGroup.scss';
Don't need this import. Removed! https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:30 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +const podStatus = [
fixed https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:30 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +  const vData = [];
fixed https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:31 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/WorkloadNode.tsx
> +        standalone={false}
fixed https://github.com/talamer/console/pull/98/commits/116ad0e7e32c3724225c931a7528ea4fdf0ff6e1

2019-05-18 06:34 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
>  export const podColor = {
All of the color aligned with colors mentioned in the except "Pulling" because it's not mentioned so keeping the "Pulling" color same as before.

2019-05-18 13:59 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +const podStatus = [
Oh ya forgot about the status was used to order the rings.

2019-05-21 06:05 UTC, karthikjeeyar commented
@sahil143  Pod colors look different from what you have posted in the PR description and the highlighted node has two pods, the separator is not showing up in between each pod.
 
![Screenshot from 2019-05-21 11-19-30](https://user-images.githubusercontent.com/9964343/58071580-cd4cb280-7bba-11e9-9d4a-7d71cda54772.png)

2019-05-21 06:14 UTC, sahil143 commented
> Pod colors look different from what you have posted in the PR description and the highlighted node has two pods, the separator is not showing up in between each.

Yeah, pod colors in your screenshot are correct. I will update the screenshot in the description.
The separator is going to be in between the pod status not in between each pod.

2019-05-21 06:38 UTC, karthikjeeyar approved these changes
LGTM

2019-05-21 17:06 UTC, christianvogt commented
@sahil143 I can only see the `running` and `pending` pod states. Even though in the server I'm testing the pods have errors. Please look at this:
https://github.com/openshift/console/blob/3a183148f2955c3ad17972127bdc21f7378845e7/frontend/public/module/k8s/pods.ts#L175

It seems the logic for determining state is much more involved than what you've done and therefore we aren't seeing the correct values in the topology.

2019-05-21 18:28 UTC, rohitkrai03 requested changes

2019-05-21 18:28 UTC, rohitkrai03 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +            {
Can you extract this events data out in a separate variable at the top and use it here for better readability?

2019-05-21 20:55 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +            {
Now that I look at this closer, it could actually be a constant outside of the render function.

2019-05-21 20:55 UTC, christianvogt commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +      if (podPhaseFilterReducer(element) === pod) {
`podPhaseFilterReducer` creates phases that are not always found in your list of legal phases. eg. `Init${terminated.reason}`, `Init${waiting.reason}`, `CrashLoopBackOff`

2019-05-22 08:43 UTC, rohitkrai03 approved these changes

2019-05-22 12:08 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +      if (podPhaseFilterReducer(element) === pod) {
fixed! used the same logic as it was used in 3.11 with a bit of modification.

2019-05-22 12:09 UTC, sahil143 commented on frontend/public/extend/devconsole/components/topology/shapes/PodStatus.tsx
> +            {
fixed! Created a `const TooltipEvent`: https://github.com/talamer/console/pull/98/files#diff-eeae528d8eb118ffb21e7309b7f8b04dR46

2019-05-22 12:33 UTC, merged